### ISSUE TITLE
Crash With CoFH Lib?

### ISSUE THREAD

**Issue by kenijey** [CoFH/Feedback#269] opened 2017-06-18 12:13 UTC
[crash-2017-06-18_15.11.20-client.txt](https://github.com/CoFH/Feedback/files/1083064/crash-2017-06-18_15.11.20-client.txt)
please help :(
used forge 2315 on mc 1.11.2

**Comment by KingLemming** [comment] 2017-06-18 12:21
Duplicate of #265.

**Comment by kenijey** [comment] 2017-06-18 12:21
sry

**Closed by KingLemming** 2017-06-18 12:21 UTC
