### ISSUE TITLE
[1.12] [Bug report] Crash when placing impulse item duct in a mixed network

### ISSUE THREAD

**Issue by Ruchian** [CoFH/Feedback#449] opened 2017-08-03 21:55 UTC
Good day.

So I made this weird construction of all kinds of ducts mixed through eachother. At a particular part (a seperate part) I have 8 machines connected to the same line of redstone energy ducts, Those six machines also have several hardened liquid ducts over them and I also placed a couple of pulsating item ducts. Now I happen to notice that for some reason it crashes the client when I stop building it symmetrical, I don't know if that is a thing.

I'm playing on the MMD Public Pack (a modpack and server), v 1.3.5.
It uses forge 14.21.1.2426
Thermal Foundation version 2.3.3.10
Thermal dynamics version 2.3.3.10

Here's a screenshot.

![screenshot thermal dynamics bug](https://user-images.githubusercontent.com/24900404/28945470-ef0b557a-78a6-11e7-9917-348f33a9e363.png)

If I place the pipe anywhere on this part of the structure, which isn't connected to the whole network yet, it crashes the client. (which is annoying), although the pipe does get placed.

I noticed a slight delay in the pipe block being rendered. I think it maybe because of rendering and getting stuck together with the other pipes it causes the crash, but I don't know for sure.

Here's the crash log:

[crash-2017-08-03_23.37.45-client.txt](https://github.com/CoFH/Feedback/files/1198690/crash-2017-08-03_23.37.45-client.txt)

I hope you can fix this problem.

**Comment by KingLemming** [comment] 2017-08-03 22:06
Duplicate of #410. Almost definitely not actually us.

**Closed by KingLemming** 2017-08-03 22:06 UTC

**Comment by Ruchian** [comment] 2017-08-03 22:15
I see, I'll report it to the mod pack issue board instead. Thanks for your quick answer.
(Sorry, it wasn't very clear to me that this would be the same issue as #410, else I would have updated that.)

**Comment by KingLemming** [comment] 2017-08-03 22:35
Unfortunately, the crash log here is kind of nebulous. It's basically crashing in something that's entirely outside of our control. And we absolutely under no circumstances can make it happen with only our mods.

**Comment by Ruchian** [comment] 2017-08-03 22:50
I think I have figured out what was causing this issue.
It seems BetterFPS is somehow causing the problem.
I disabled it and could run it without any issues. Thanks for the hint.

**Comment by KingLemming** [comment] 2017-08-03 22:59
Ah ha. Thank you.
