### ISSUE TITLE
[Thermal Dynmics] Retrievers bug

### ISSUE THREAD

**Issue by SirWilli** [CoFH/Feedback#330] opened 2015-03-19 08:53 UTC
Version: ThermalDynamics-[1.7.10]1.0.0RC2-77

It seems that you can dupe items with Retrievers (maybe with others too) and an Inscriber from AppliedEnergistics.
Setup:
http://i59.tinypic.com/elcxzr.jpg
Inscriber:
http://i57.tinypic.com/25ho947.jpg
ME Interface:
http://i59.tinypic.com/24boxac.jpg
Me System after a while:
http://i60.tinypic.com/2805xeb.jpg

**Comment by FireBall1725** [comment] 2015-03-29 23:50
What version of AE2

**Comment by FireBall1725** [comment] 2015-03-30 00:10
Not able to reproduce http://screenshot.tsr.me/FZf2

**Comment by KingLemming** [comment] 2015-03-30 00:36
I can't reproduce either. Are you on RC7?

**Comment by SirWilli** [comment] 2015-03-30 02:02
appliedenergistics2-rv2-beta-8

**Comment by Parker8283** [comment] 2015-03-30 10:50
Update all your mods. You are using an outdated TD.

**Comment by KingLemming** [comment] 2015-03-31 21:30
Ah. Indeed. Closing this then. Please update.

**Closed by KingLemming** 2015-03-31 21:30 UTC
