### ISSUE TITLE
 [Bug report][Thermal Expansion] 1.12-2.3.7.18

### ISSUE THREAD

**Issue by aeiberra** [CoFH/Feedback#678] opened 2017-12-02 18:40 UTC
When you do Hardened Glass, if you put first Pulverised Obsidian and then Lead Ingot in the Induction Smelter the recepie change and use 1 Pulverised Obsidian and 1, 2, 3 or 4 Lead Ingot (max 4), per 2  Hardened Glass.

Video: [https://vimeo.com/245532067](https://vimeo.com/245532067)

**Comment by KingLemming** [comment] 2017-12-02 19:10
Your version is nonsensical. I'm betting it's not the latest on Curseforge though.

**Comment by KingLemming** [comment] 2017-12-02 19:16
Actually yeah, duplicate of #669. Please update.

**Closed by KingLemming** 2017-12-02 19:16 UTC
