### ISSUE TITLE
[MFR] Fruit Picker does not destroy Forestry leaves

### ISSUE THREAD

**Issue by Nentify** [CoFH/Feedback#699] opened 2015-07-15 12:15 UTC
http://i.nentify.me/l7XWZ19h.mp4

As shown in the video above, the fruit picker is not destroying the Forestry leaves and is infinitely creating fruit (Forestry 3.6). This is in SP with the latest versions of Forge, CoFH, MFR, Forestry, etc.

**Comment by KingLemming** [comment] 2015-07-17 19:55
Paging @skyboy

**Comment by skyboy** [comment] 2015-07-20 03:47
Duplicate of https://github.com/skyboy/MineFactoryReloaded/issues/436

**Closed by skyboy** 2015-07-20 03:47 UTC
