### ISSUE TITLE
[FPS Drops] Thermal Dynamics - Cryo-Stabilized Fluxduct

### ISSUE THREAD

**Issue by LokeYourLord** [CoFH/Feedback#1238] opened 2016-08-16 17:18 UTC
So, basically what the title says. If you use too many Cryo-Stabilized Fluxducts at one place, the FPS drops are bad, very bad. I can use any other power cable from any other mod, but using like 100 Cryo-Stabilized Fluxducts at one place makes my FPS go from 45-60 (in a HEAVILY modded environment) to 15-20, which is very bad. Not much of logs i could provide as this is more an issue you guys would have to look into, and screenshots don't prove much. Basically, try putting a LOT of Cryo-Stabilized Fluxducts in a very dense spot, or even over a larger area, and you start noticing FPS drops.

**Comment by KingLemming** [comment] 2016-08-16 17:51
A video would work. And maybe posting the stats of your computer.

This isn't something any of us see. :/

**Comment by LokeYourLord** [comment] 2016-08-16 17:52
PC Stats (taken from my Steam page):
OS: Windows 10 Pro x64 
MOTHERBOARD: ASRock Z97 Extreme4 
CPU: Intel Core i7-4790K 4.5 GHz 
RAM: Crucial DDR3 BallistiX Sport 1600MHz 16GB x2 (32GB RAM) 
PSU: EVGA SuperNova 750B 
GPU: ASUS STRIX 970 SLI (x2) 
SSD-1: MTFDDAK256MAY (Dell SSD) (240GB) 
SSD-2: OCZ-TRION100 (Toshiba SSD) (240GB) 
HDD-1: WDC WD30EURS (Western Digital) (3TB) 
HDD-2: WDC WD1001FALS (Western Digital) (1TB) 
CASE: NZXT Phantom 820 White 
CPU - COOLING: NZXT Kraken X61 
MONITOR-1: Acer XB280HK (3840x2160@60Hz) (28") 
MONITOR-2: Samsung S22D390 (1920x1080@60Hz) (22") 
MONITOR-3: LCDTV16 (1920x1080@60Hz) (22") 
MOUSE: Logitech G502 Proteus Core 
KEYBOARD: Logitech G910 Orion Spark

I will see if i can upload a video at some point, but right now, due to all the FPS drops and such, i removed all Fluxducts from all my bases and those of others, but i will see if i can reverse it.

**Comment by bookerthegeek** [comment] 2016-08-16 20:47
I should be able to get you some screenshots tonight @KingLemming

@LokeYourLord can you post some screenshots to imgur and link to them here please?

**Comment by LokeYourLord** [comment] 2016-08-17 05:11
Here the screenshots with the FPS to the upper left. The more Cryoducts, the worse the FPS becomes. I will also set up a video, since the FPS bumps up to 60 if you don't move at all, once you move, FPS goes down to 14 and below (if enough Cryoducts are around).

1:
![2016-08-17_07 04 31](https://cloud.githubusercontent.com/assets/5807595/17725237/ab7abc46-6449-11e6-8064-7388aaac9393.png)

2:
![2016-08-17_07 05 54](https://cloud.githubusercontent.com/assets/5807595/17725241/b1d5282e-6449-11e6-9fd3-270d7e0449e5.png)

3:
![2016-08-17_07 06 49](https://cloud.githubusercontent.com/assets/5807595/17725246/b6742164-6449-11e6-9d69-6b205f52dc04.png)

4:
![2016-08-17_07 07 19](https://cloud.githubusercontent.com/assets/5807595/17725249/b98e7fb6-6449-11e6-87af-e6b3272a4eb9.png)

5:
![2016-08-17_07 08 02](https://cloud.githubusercontent.com/assets/5807595/17725253/be812a28-6449-11e6-818b-b2e7ebe37151.png)

6:
![2016-08-17_07 08 42](https://cloud.githubusercontent.com/assets/5807595/17725260/c33aa9cc-6449-11e6-9e59-0615fd7b56a8.png)

**Comment by KingLemming** [comment] 2016-08-17 05:26
Need a mod list. Also need you to try it with only CoFH mods installed. Absolutely no FastCraft or Optifine.

**Comment by skyboy** [comment] 2016-08-17 08:57
I have similar specs to you:
```
Motherboard: GIGABYTE GA-Z97X-SLI
CPU: Intel i7-4790K @ 4.4GHz
Cooler: Corsair H100i GTX
Memory: G.SKILL Trident X 16GB DDR3 @ 2400MHz
Video Card: ZOTAC GeForce GTX 970
```

And I do not see the kind of drop you do; There is some stuttering while moving as minecraft redraws the alpha layer, but I don't *see* any drops under 100 FPS while that happens, and while standing still I maintain 700 FPS.

Heavy redraws of an area with that many cryoducts is expected to be slow, due to the complexity of the model, but for normal usage - maybe 50 or so in a 16x16x16 area for a heavy user, they shouldn't notice the redraws being worse than standing still, until around 300 or so total visible and nearby, and nothing notable while standing still.

However, you might try CoFHTweaks and see if that improves anything here.

**Comment by LokeYourLord** [comment] 2016-08-17 09:49
@skyboy It's also the stuttering i am talking about, yes. But i am running 250 mods in my modpack, so a framerate of 100FPS or higher is un-achievable, and i tried everything as of optimizing it, and FastCraft and Optifine barely help it. The fact you have that high FPS is because you only play with either just the CoFH mods or maybe up to 20 mods, at my absurd amount of mods, a high frame rate just is impossible. Here a modlist from another thread i opened at the MCF (i really need help on that one too, in case anyone can help with that, but my mods are listed there). [MCF Thread](http://www.minecraftforum.net/forums/support/server-support/2727372-problem-with-entity-distance)

**Comment by Fabboz** [comment] 2016-08-19 02:47
I think you may try to repeat the test but with a lot of fences to see if it`s the same

**Comment by bookerthegeek** [comment] 2016-08-19 03:14
@skyboy We have some rather large bases on our servers. As we are running a bunch or modpacks if you give me a name of a pack with a mod set close to your dev environment I will go and create this issue for you on one of our production servers.

**Comment by Fabboz** [comment] 2016-08-19 08:52
In my test only unsane amount of connections drop fps,the other cables work perfect even in unsane amount like your screens!but i`m sure that is client side lag.

**Comment by skyboy** [comment] 2016-08-19 12:01
@bookerthegeek and @LokeYourLord, @Fabboz is fairly well correct. A few thousand connections and you'll start seeing some frame drop regardless of pack simply because of how complex the model is: fences do the same thing, even glass panes do to some extent. Add in just a handful of really crappy code running every frame and you can see massive drops for very small numbers of connections.

Such a drop with just 100 cryoducts is entirely excessive, but you know what, you if you want to install every mod you can find then you're going to get more than a handful of crappy code running.
<hr>
I'm just going to close this as "too many other mods for anything to matter anymore."

**Closed by skyboy** 2016-08-19 12:01 UTC
Labels: TD

**Comment by LokeYourLord** [comment] 2016-08-19 12:54
Uhm, sorry but no, i don't have this issue with "fences" or alike. I tried stacking them up in the same amount as the cables, and as you see in my screenshots, it's only a small amount of cables before the stuttering appears. I had to end up banning Cryoducts on my servers due to this,  since multiple people were having this problem. We ended up using EnderIO Conduits with just the transfer amount boosted by 128x, and we replaced ALL the Cryoducts in the bases that earlier were causing (yes, Client Side, not Server Side lag), and these Conduits from EnderIO cause no FPS lag or stuttering, but are in the same amount as the Cryoducts. If you want to shove the blame on us for having many mods, fine, but it doesn't make it any better that they are faulty and cause, even in Medium amounts, FPS lags and terrible stuttering. You know that the CoFH mods ALWAYS are played in multi-mods environments, because that's why they are in about any modpack. You can blame us for finding the bug, but you cannot shove this away as never having happened. This issue is NOT invalid, we proved that the issue well exists, and the issue does NOT exist with fences or glass panes in the same amount, which can easily be proven. I filled out an entire chunk with glass panes and fences, FPS was about the same. But filling out 1/4th of a chunk with the Cryoducts causes insane stutter.

**Comment by anubisalpha** [comment] 2016-08-19 13:20
I can confirm that this does exist, i had about  200 cryoducts, and althought i was getting 30-40 fps, it was lagging my movement, as in when i move it would be more like a jumnp than move forwards, I have since change the cryoducts to enderIO cables and the issue is completely gone.

My PC Spec is:
 Operating System: Windows 10 Pro 64-bit (10.0, Build 10586) (10586.th2_release.160802-1857)
 Processor: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 CPUs), ~4.0GHz
 Memory: 16384MB RAM

Client Mods used:
[1.7.10]bspkrsCore-universal-6.16.jar
Baubles-1.7.10-1.0.1.10.jar
CodeChickenLib-1.7.10-1.1.3.140-universal.jar
commons-codec-1.9.jar
commons-compress-1.8.1.jar
ForgeMultipart-1.7.10-1.2.0.347-universal.jar
ForgeRelocation-1.7.10-0.0.1.4-universal.jar
ForgeRelocationFMP-0.0.1.2-universal.jar
MrTJPCore-1.1.0.33-universal.jar
slick-util-0.0b9db0b2.jar
vorbis-java-core-0.8-20150201.161816-1.jar
EJML-core-0.26.jar
rhino-1_7r4.jar
WorldEdit-5.6.2.jar
advanced-machines-59.0.2.jar
AdvancedLightsabers-1.7.10-1.0.5.jar
AdvancedSolarPanel-1.7.10-3.5.1.jar
adventurebackpack-1.7.10-0.8c.jar
ae2stuff-rv3-0.5.1.9-mc1.7.10.jar
AgriCraft-1.7.10-1.5.0.jar
appliedenergistics2-rv3-beta-6.jar
Aroma1997Core-1.7.10-1.0.2.16.jar
Aroma1997s-Dimensional-World-1.7.10-1.1.0.1.jar
AsieLib-1.7.10-0.4.5.jar
bdlib-1.9.4.109-mc1.7.10.jar
BetterRecords-1.7.10-1.2.0.jar
BetterSleeping-1.7.10-1.2.27.jar
BiblioCraft[v1.11.5][MC1.7.10].jar
BiblioWoods[Forestry][v1.7].jar
BiblioWoods[Natura][v1.5].jar
BigReactors-0.4.3A.jar
BiomeTweaker-1.7.10-2.0.182.jar
Bookshelf-1.7.10-1.0.4.187.jar
BrandonsCore-1.0.0.12.jar
Carpenter's Blocks v3.3.7 - MC 1.7.10.jar
[carpentersblocks]
Chisel2-2.4.0.38.jar
chocolateQuest-1.7.10-1.0.jar
ChunkAnimator-MC1.7.10-1.0.1.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
CoFHCore-[1.7.10]3.1.3-327.jar
CompactSolars-1.7.10-4.4.41.316-universal.jar
ComputerCraft1.75.jar
CookieCore-1.7.10-1.4.0-11.jar
cookingbook-mc1.7.10-1.0.140.jar
coroutil-1.7.10-1.1.5.jar
CustomMainMenu-MC1.7.10-1.9.2.jar
DefenseTech-1.7.10-1.0.1.46.jar
denseores-1.6.2.jar
dimensional-anchor-59.0.3.jar
Ding-MC1.7.10v2.jar
DogeMod-[1.7.10]-0.5.3.jar
Draconic-Evolution-1.7.10-1.0.2h.jar
DynamicLights-1.7.10.jar
EasyCrafting-1.7.10-2.0.1.16.jar
Emotes 1.0.1.jar
EnchantingPlus-1.7.10-4.0.0.74.jar
EnderCore-1.7.10-0.2.0.36_beta.jar
EnderIO-1.7.10-2.3.0.424_beta.jar
EnderStorage-1.7.10-1.4.7.37-universal.jar
EnderTech-1.7.10-0.3.2.405.jar
EngineersToolbox-1.2.3.0-BETA.jar
ExtraCells-1.7.10-2.3.14b197.jar
ExtraTiC-1.7.10-1.4.6.jar
extrautilities-1.2.12.jar
fastcraft-1.23.jar
FlatSigns-1.7.10-universal-2.1.0.19.jar
FloodLights-1.7.10-1.2.8-137.jar
Fluxed-Crystals2-1.0.7.jar
forestry_1.7.10-4.2.14.62.jar
FoxLib-1.7.10-0.7.0.jar
Galacticraft-Planets-1.7-3.0.12.463.jar
GalacticraftCore-1.7-3.0.12.463.jar
GalaxySpace-1.1.0 STABLE.jar
gendustry-1.6.4.135-mc1.7.10.jar
GlibysVC-1.7.10-0.6.1.jar
GraviSuite-1.7.10-2.0.3.jar
GravityGun-4.0.0-beta.jar
Guide-API-1.7.10-1.0.1-29.jar
[ic2]
IC2 Backpack HUD v3.0 - MC 1.7.10.zip
IC2NuclearControl-2.3.4a.jar
IC2Tweaks-1.7.10-1.2.0.jar
iChunUtil-4.2.2.jar
IGW-Mod-1.7.10-1.1.12-34-universal.jar
ImmersiveEngineering-0.7.7.jar
immersiveintegration-0.6.8.jar
immibis-core-59.1.4.jar
immibis-peripherals-59.0.3.jar
industrialcraft-2-2.2.820-experimental.jar
infinitubes-59.0.5.jar
INpureCore-[1.7.10]1.0.0B9-65.jar
InventoryTweaks-1.59-dev-153.jar
ironchest-1.7.10-6.0.62.742-universal.jar
IvToolkit-1.2.jar
Jabba-1.2.2_1.7.10.jar
journeymap-1.7.10-5.1.1rc1-unlimited.jar
LagFix-2.0.1-mc1.7.10-forge.jar
liquid-xp-59.0.2.jar
liteloader-1.7.10.jar
lookingglass-1.7.10-0.2.0.00.jar
LunatriusCore-1.7.10-1.1.2.21-universal.jar
malisiscore-1.7.10-0.14.3.jar
malisisdoors-1.7.10-1.13.2.jar
Mantle-1.7.10-0.3.2b.jar
[mcheli]
Mekanism-1.7.10-9.1.0.281.jar
MekanismGenerators-1.7.10-9.1.0.281.jar
MekanismTools-1.7.10-9.1.0.281.jar
MicdoodleCore-1.7-3.0.12.463.jar
MineFactoryReloaded-[1.7.10]2.8.2B1-198.jar
MineTweaker3-1.7.10-3.0.10B.jar
[moarperipherals]
MoarPeripherals-1.7.10-1.7-1.52.jar
MobiusCore-1.2.5_1.7.10.jar
mods.txt
ModTweaker2-0.9.5.jar
ModularPowersuits-0.11.0.300.jar
mod_worldeditcui_1.7.10_00_mc1.7.10.litemod
mod_worldeditwrapper_1.2.0_we5.6.2_mc1.7.10.litemod
Morph-Beta-0.9.2.jar
MouseTweaks-2.4.4-mc1.7.10.jar
MrCrayfishFurnitureModv3.4.8(1.7.10).jar
natura-1.7.10-2.2.0.1.jar
neiaddons-1.12.15.41-mc1.7.10.jar
NEIIntegration-MC1.7.10-1.1.2.jar
NetherOres-[1.7.10]2.3.2B1-23.jar
NotEnoughItems-1.7.10-1.0.5.120-universal.jar
NuclearCraft-0.0.1.5--1.7.10.jar
Numina-0.4.0.131.jar
ObsidiPlates-1.7.10-universal-3.0.0.18.jar
OpenBlocks-1.7.10-1.5.1.jar
OpenComputers-MC1.7.10-1.5.22.46-universal.jar
OpenEye-0.6-1.7.10.jar
OpenGlasses-1.0.46.jar
OpenModsLib-1.7.10-0.9.1.jar
OpenModularTurrets-1.7.10-2.2.3-220.jar
OpenPeripheral-1.7.10-AIO-7.jar
OptiFine_1.7.10_HD_D1.jar
OreDictionaryConverter-1.6.1.jar
Pam's HarvestCraft 1.7.10Lb.jar
Patcher.jar
Ping-1.7.X-1.0.3.B7-universal.jar
PneumaticCraft-1.7.10-1.12.7-150-universal.jar
Portal Blocks v1.0_1.7.10.jar
PortalGun-4.0.0-beta-6.jar
PortalGunSounds.pak
PowerConverters-1.7.10_3.3.0-jenkins.76.jar
pressure-1.3.0.131-mc1.7.10.jar
ProjectBlue-1.1.4-mc1.7.10.jar
ProjectRed-1.7.10-4.7.0pre12.95-Base.jar
ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar
ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar
ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar
ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar
ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar
ProjectRed-1.7.10-4.7.0pre12.95-World.jar
qCraft1.2_1.7.10.jar
RadixCore-1.7.10-2.1.1-universal.jar
[railcraft]
Railcraft_1.7.10-9.12.2.0.jar
RandomThings-2.2.4.jar
RedstoneArsenal-[1.7.10]1.1.3B1-94.jar
RefinedRelocation-mc1.7.10-1.1.28.jar
ResourceLoader-MC1.7.10-1.3.jar
RoadStuff-mc1.7.10-1.0.1.jar
RTG-1.7.10-1.1.1.jar
Schematica-1.7.10-1.7.6.131-universal.jar
secretroomsmod-1.7.10-4.7.1.413.jar
SGCraft-1.11.2-mc1.7.10.jar
SolarExpansion-Basic-1.6a.jar
SoundFilters-0.8_for_1.7.X.jar
[Streak Flavours]
supercraftingframe-1.7.10.3.jar
switchescontinued-0.0.1.jar
Tails-1.7.10-1.3.1.jar
TConstruct-1.7.10-1.8.8.jar
TF2Dispenser-1.7.10.jar
TF2Sentry-1.7.10.jar
TF2Teleporter-1.7.10.jar
thermalcasting-0.0.3.jar
ThermalDynamics-[1.7.10]1.2.0-171.jar
ThermalExpansion-[1.7.10]4.1.4-247.jar
ThermalFoundation-[1.7.10]1.2.5-115.jar
ThermalRecycling-1.7.10-1.1.0.5.jar
ThermalSmeltery-1.7.10-1.2.1.jar
TiCTooltips-mc1.7.10-1.2.5.jar
TMechworks-1.7.10-0.2.15.106.jar
Torcherino-1.7.10-2.2s.jar
tropicraft-6.0.5.jar
tubestuff-59.0.4.jar
Turbo-1.7.10-1.2.0.jar
[VoxelMods]
Waila-1.5.10_1.7.10.jar
WailaHarvestability-mc1.7.10-1.1.6.jar
WAILAPlugins-MC1.7.10-0.2.0-23.jar
WarpDrive-1.7.10-1.3.26.-.jar
Wawla-1.3.3-1.7.10.jar
weather2-2.3.10 for MC v1.7.10.jar
[WorldEdit]
worldedit-forge-mc1.7.10-6.0-beta-01.jar
WR-CBE-1.7.10-1.4.1.9-universal.jar
Ztones-1.7.10-2.2.1.jar
[1.7.10] SecurityCraft v1.8.1.jar
[1.7.10]Better_Furnaces_V4.3.jar
[1.7.10]DamageIndicatorsMod-3.2.3.jar
[1.7.10]Treecapitator-universal-2.0.4.jar


Any sugestions would be appreciated.

Marc

**Comment by skyboy** [comment] 2016-08-19 23:43
As I have said: Cryoducts have a *more complex model*. Fences are simpler than them, but more complex than standard flux ducts, which you should use in this case: the enderium ones have more than enough throughput for anything not asininely over powered. There is no bug here, this is simply lag caused by complex models being what they are: *<b>complex</b> models* made worse by being transparent and having other mods drag your framerate down low enough you notice their effect on framerate.

Stop insisting I, the experienced programmer, don't know what I'm talking about.

**Comment by anubisalpha** [comment] 2016-08-20 17:43
Um wow that very strange ending to a responce, as i have never spoken to you before this post please explain how i have insisted anything, i was just asking for suggestions on how to overcome this, if this is touching a nerve for some strange reason then it is your issue not mine, i am just trying to be helpful and report what i personally have found.

I have simply confirmed that there is an issue with lower fps when using the cryo ducts, it was that simple, nothing sinister or devlish about it.

Marc

**Comment by bookerthegeek** [comment] 2016-08-20 19:09
@skyboy Just to preface this I love CoCH mods and use them all the time. 

Some things as a base explanation:
- Cryo ducts are for many reasons the best there is for moving RF.
- Yes, Enderium ducts work 95% of the time and Cryo Ducts are not needed.

For most of the players on our server (Which I'd be more than happy to give a tour to any of the CoFH devs) people would use the Cryo Ducts only. Mainly for the same reason people used glass fiber cable for everything in IC2 back in the day. Why take the extra time to have other ducts when this is the best? So people do start using them, all the time, everywhere.

Our servers are all big packs. so people usually do not have the best FPS anyways at their bases. We try to give them advice on how to reduce FPS lag. While we have not and will not ban your Cryo Ducts, we do advise people to only use them when necessary. They do not all have to be in the same chunks to cause an issue, just all within render distance and in you FOV.

As you pointed out the lag is comming from the model of the ducts. I suppose that is better than comming from the pipes themself? I will not as for you to modify the model, but would it be an option to add a client side config for players to maybe display a less graphic heavy version of it? 

Also I would like to point out that these do not cause any TPS lag on our server. So thank you for the wonderful items in that regard.


> Keep calm and code on!
