### ISSUE TITLE
[Thermal Expansion 5.0.1.73] Fluid Transposer Output bug

### ISSUE THREAD

**Issue by Tydesson** [CoFH/Feedback#113] opened 2017-03-20 10:46 UTC
I'm not sure if it's a bug or intended, but if you auto input buckets and fill them with any liquid inside (tested with destabilized redstone), if you have one bucket in the fill slot, and one bucket in the output slot, when you remove the bucket in the output slot, the bucket in the fill slot does not go to the output slot automatically.

This means that you have to empty the output slot BEFORE the next bucket is filled, if you don't, the Fluid Transposer is stuck until you manually remove the last filled bucket.

I tested on FTB Beyond 1.0.1

Can provide screenshots if needed.

**Comment by KingLemming** [comment] 2017-03-20 11:06
Duplicate of #70 and fixed literally over a week ago. Please only report bugs if you're on the latest version of the mod. -_-

**Closed by KingLemming** 2017-03-20 11:06 UTC
