### ISSUE TITLE
ThermalExpansion & ElectriCraft - Tesseract wont work & RF Transfer cable omits cell settings

### ISSUE THREAD

**Issue by Hiranus** [CoFH/Feedback#52] opened 2015-01-26 09:25 UTC
Modlist:
http://pastebin.com/t9xiDfci

Here's link to Reika's mods
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more

RF Transfer Cable and RF Storage Battery from ElectriCraft wont connect to tesseract, no matter what i do. 
RF Transfer Cable can omit cells output setting, and is able to pull about 40k RF from resonant cell (tested with EnderIO capacitors to get exact number).

**Comment by Hiranus** [comment] 2015-01-26 10:31
I forgot to write that i informed about this Reika too.

**Comment by bochen415** [comment] 2015-01-26 10:47
@Hiranus And what did he say about it? (sorry I couldn't help it)

**Comment by KingLemming** [comment] 2015-01-26 15:53
Okay, please tell Reika to use the API properly then I guess?

**Comment by ReikaKalseki** [comment] 2015-01-26 16:38
What exactly am I doing wrong? The RF api is, as you have said yourself, extremely simple and thus hard to misuse.

Also not mentioned by Hiranus is that this seems to have only started with the new RF update.
https://github.com/ReikaKalseki/ElectriCraft/blob/master/Network/RF/RFNetwork.java

**Comment by KingLemming** [comment] 2015-01-26 17:18
I have no idea what you're doing wrong. But if you're bypassing Cell Limits, it's in your cables. Sounds like you can double extract. Are you adding them to the network twice?

**Comment by ReikaKalseki** [comment] 2015-01-26 21:15
I do not think I am doing anything twice; the internal logic is basically "simulate adding Int.MAX to each tile, build a cache of how much can theoretically go where, then collect as much as possible from all sources up to totalDeliverable-energyBuffer, then distribute it".

I think I might be doing it both client and server, but that should matter little.


Also, Hiranus is using a version of the network that is built on the old API (and IEnergyHandler); the one on GitHub, being updated, may work better, though again, the internal logic should not really care.

**Comment by skyboy** [comment] 2015-01-27 01:03
The cell is probably connected on multiple faces; they presently permit both extraction and pumping energy out in the same tick, so connecting on 2 faces would allow 40k/t being removed from the cell.

**Comment by KingLemming** [comment] 2015-01-27 01:09
They'll always permit that too. :) I think it's a fun feature.

**Comment by ReikaKalseki** [comment] 2015-01-27 01:46
That could well be it; my network logic is not designed to distinguish between that, as there are several real use cases I can think of where the tile can accept more energy in one side than it can emit from another or where sidedness otherwise matters.

@Hiranus: Check for this, and try separating the network into two "halves", one in, and one out.

**Comment by KingLemming** [comment] 2015-01-27 04:37
Nono - there's no NEED to check for that. A cell connected on multiple sides is intended to be able to send extra RF. It's a surface area thing.

**Comment by ReikaKalseki** [comment] 2015-01-27 08:09
I mean disabling it from both inserting and removing from the same block, but that makes batteries more of a pain...

**Comment by Hiranus** [comment] 2015-01-27 10:35
That's how it looks like

http://imgur.com/gUr8FWu,jnwrVxD#0
http://imgur.com/gUr8FWu,jnwrVxD#1

and cable setting is 100.100 MRF/tick

**Comment by ReikaKalseki** [comment] 2015-01-27 17:58
So in terms of RF flow, it is working correctly, but it is simply transferring more than the cell is capable of emitting?

How are cells coded? I know they have a 10k RF/t limit per side, but what enforces that (ie is there some sort of "transferred this tick" cache)?

**Comment by KingLemming** [comment] 2015-01-27 18:03
If that check were failing, it'd be pulling what the cable asked for. It's not doing that.

I'm wondering if this is a corner case where the cable sees two energy providers, and two energy receivers, and iterates 4 times.

**Comment by ReikaKalseki** [comment] 2015-01-27 18:13
It only runs once a tick, but seeing two providers (both being the same TileEntity) would cause a 2x drain, yes. Seeing extra sinks would not affect it, as that would only increase the maximum "transferrable this tick".

Also, I am not sure it would be pulling what the cable asked for; the EnderIO capacitor may have an input limit as well.

As for cables receiving energy, it appears they can, and doing so will add to the network's internal buffer (subtracting from the total "intakeable" that tick, to help clear the buffer). Come to think of it, I should probably remove this, as it is not necessary to network function, but I do not think it is the problem: because it would run in the same tick as (and after) the network's cycle, would the cell not skip the RF push if the network already drained 10kRF that tick?

**Comment by KingLemming** [comment] 2015-01-27 18:25
No, the cell does not maintain an internal check like that. I sort of operated under a "push-only" assumption when they were coded. Sort of dates back to when we used MJ.

I'll consider changing around internal limits. I'm generally not a fan of having to maintain an extra variable and keep up with the extra arithmetic. it's trivial, but one more thing that adds to server issues.

**Comment by ReikaKalseki** [comment] 2015-01-27 18:29
I am already going to remove the pushability into RF cables, which should also fix this issue.

**Comment by KingLemming** [comment] 2015-01-27 18:32
Don't do that. Tiles need to be able to push in the absence of a network, and there are good reasons to not support extract. Dynamos, for example.

**Comment by ReikaKalseki** [comment] 2015-01-27 18:37
Then what is a better approach? The former is not good for performance - you said so yourself last time we discussed RF distribution - and the latter, because it makes it difficult or impossible to run "can I distribute this" checks on addition, runs the possibility of accumulating a large buffer that will be lost if the network object is destroyed (eg breaking a cable, restarting the game...).

**Comment by KingLemming** [comment] 2015-01-27 18:42
You need to save energy when the network changes, for starters.

You also need to not 2x count - that's an outright bug and needs to be fixed before you consider a redesign.

**Comment by ReikaKalseki** [comment] 2015-01-27 18:54
That does not help me with cases like restarting the game or unloading chunks, where the only thing I can think of is trying to write the network's buffer to the world NBT, which is messy and raises the question of reading it again (how does a network know which NBT tag was for it as opposed to some other network?).

Also, what do you mean by 2x count? As far as I know, the network only maintains one entry for each side of each tile, and though I can make that one entry per tile, that would break tiles which have different rules per side, including the TE3 cells.

**Comment by KingLemming** [comment] 2015-01-27 18:56
You already said you were double draining; that'd be a bug.

And yes - saving the energy does help you with chunk and game reload cases. I didn't mean temporarily save. ;)

But if disabling the receive on cables is going to work well enough for you, go for it. Just know that there are some tiles that aren't going to play nicely with that. I can be sure everything in TE will, but beyond that, no guarantees.

**Comment by ReikaKalseki** [comment] 2015-01-27 19:05
I am going to have to ponder this for a while...

**Comment by skyboy** [comment] 2015-01-28 01:55
Y'all discuss a lot while I'm asleep: This is an issue on the cell, it permits both extract and push in the same tick (said above). Cables that support both tend to do double-rate extracts as a result, and it's somewhat non-trivial to resolve: cables may extract at the end of the tick or beginning, which poses issues for tracking state and preventing both from happening in one tick.

**Comment by ReikaKalseki** [comment] 2015-01-28 05:26
Alright, keep me updated. :)

I am willing to rewrite my network logic, so long as I do not have to resort to ugly or volatile (i.e. "not always valid") hacks.

**Comment by KingLemming** [comment] 2015-01-28 06:51
Thing is skyboy, this isn't a "double" extract - it's a quadruple. This isn't entirely in the cell.

**Comment by skyboy** [comment] 2015-01-28 07:57
@ReikaKalseki You may want to verify the TickRegistry in DAPI is respecting canFire. or otherwise ensure ElectriNetworkTickEvent isn't being fired twice (e.g., two ticker instances (leaking on re-joining servers?))

**Comment by ReikaKalseki** [comment] 2015-01-28 11:40
I can confirm it does respect it.
https://github.com/ReikaKalseki/DragonAPI/blob/master/Auxiliary/Trackers/TickRegistry.java#L84

As for double tickhandler instances, I highly doubt it; the instance is created and registered at launch time.

Now, two *network* instances is theoretically possible, though I have checked for that in the past (it would also cause things like 2x drain on the ElC batteries), and that is much more difficult to test. I will check again, and I may have a way to prevent it if it is happening.

**Comment by ReikaKalseki** [comment] 2015-01-29 06:07
Alright, testing has showed no indication of another network object; if it is there, it is not ticking and thus is not transferring energy.

**Comment by 016Nojr** [comment] 2015-03-14 08:46
EnderIO item conduits doesnt seem to connect aswell

**Comment by ReikaKalseki** [comment] 2015-03-14 21:41
Item conduits? Why would they connect to energy cells and/or RF transfer cables? Also, that is a different issue for a different thread.

**Comment by 016Nojr** [comment] 2015-03-19 06:31
Updated the comment

**Closed** 2015-04-01 19:46 UTC
Labels: wtf
