### ISSUE TITLE
Crash ?

### ISSUE THREAD

**Issue by runescapejon** [CoFH/Feedback#1224] opened 2016-08-02 02:45 UTC
I am recently getting this crash report and my server wont start up without a world reset and i had to do it but i am wonder why did it crash randomly like that the crash report: http://pastebin.com/xjdUvXTC

**Comment by skyboy** [comment] 2016-08-02 12:00
Duplicate of https://github.com/CoFH/Feedback/issues/1206

**Closed by skyboy** 2016-08-02 12:00 UTC

**Comment by runescapejon** [comment] 2016-08-02 21:23
how is this a duplicate when at line 12 its different ?
