### ISSUE TITLE
Induction smelter uses too few items

### ISSUE THREAD

**Issue by Purzelpu** [CoFH/Feedback#685] opened 2017-12-03 19:50 UTC
Making bronze in the induction smelter consumes only 1copper and 1 tin instead of 3copper/1tin.
A similar issue occurs with hardened glass where only 1 obsidian dust is consumed.

Tested with:
CoFH core 4.3.7.25
TF 2.3.7.18
TE 5.3.7.29

**Comment by KingLemming** [comment] 2017-12-03 20:16
That isn't what's happening here, no.

Duplicate of #669. Unsure why you seem to be getting this as my local copy of .29 works correctly. Maybe a Curse thing.

**Comment by KingLemming** [comment] 2017-12-03 20:45
Had to upload a .30 to apparently correct it. I guess something didn't build right remotely. But I've confirmed this one to be fixed.

**Closed by KingLemming** 2017-12-03 20:45 UTC
