### ISSUE TITLE
Redstone-Arsenal Flux-Infused Bow acts weirdly

### ISSUE THREAD

**Issue by ELChris414** [CoFH/Feedback#28] opened 2017-03-05 14:42 UTC
The bow acts very weirdly. The animation of the item when pulling seems random and not proper. The 3d model does not get consistently the arrow model on it:
![2017-03-05_16 35 29](https://cloud.githubusercontent.com/assets/8685248/23588183/658836ac-01c2-11e7-9efb-aa7fbd406201.png)
![2017-03-05_16 39 34](https://cloud.githubusercontent.com/assets/8685248/23588182/6588367a-01c2-11e7-94bd-18dfc7771a10.png)
Also, the position where the arrow is being spawned seems buggy:
![2017-03-05_16 39 45](https://cloud.githubusercontent.com/assets/8685248/23588187/789fc2a0-01c2-11e7-917b-8d00d2e6d034.png)
![2017-03-05_16 40 55](https://cloud.githubusercontent.com/assets/8685248/23588197/8c6f2532-01c2-11e7-8181-4e55d454c219.png)

After multiple tries I have noticed that it has something to do with where are you looking. If you stay still, it is consistent, although wrong.

**Comment by KingLemming** [comment] 2017-03-05 15:51
Duplicate of #10 .

As far as the arrow goes, that's a Mojang bug and it's purely visual. The arrow still goes where it should.

**Closed by KingLemming** 2017-03-05 15:51 UTC

**Comment by ELChris414** [comment] 2017-03-06 14:24
Man, am I awful at this.
