### ISSUE TITLE
[1.12] Machine "Dupe" glitch when breaking any machine with any pickaxe

### ISSUE THREAD

**Issue by Fogrits** [CoFH/Feedback#501] opened 2017-08-26 12:08 UTC
Some machines drop itself along with another machine.
(when breaking a Pulverizer, it drops itself along with a Redstone Furnace, and when breaking an Arboreal Extractor, it drops itself along with an Aqueous Accumulator).
I didn't test with other machines/devices, though.
This also happens with Dynamos, dropping 2 instead of just one.

I'm using Thermal Expansion v5.3.4.16 at the moment

My Mod List
![Mod List](https://user-images.githubusercontent.com/14002834/29741177-bc439dd4-8a3d-11e7-9636-70f489ba1e11.PNG)

**Comment by covers1624** [comment] 2017-08-26 13:10
What are you using to break the block?

**Comment by covers1624** [comment] 2017-08-26 13:14
You have Psi / MultiMine installed. Duplicate of https://github.com/CoFH/Feedback/issues/139 https://github.com/CoFH/Feedback/issues/93 https://github.com/CoFH/Feedback/issues/365

**Closed by covers1624** 2017-08-26 13:14 UTC
