### ISSUE TITLE
Thermal Foundation for 1.7.10 causes cr!

### ISSUE THREAD

**Issue by tallpasha1** [CoFH/Feedback#964] opened 2018-03-03 23:15 UTC
I've downloaded Thermal Foundation for 1.7.10, but it seems that crashes are happening whenever I start the game!                      
Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/network/IGuiHandler

Note: I've downloaded Thermal foundation from Minecraft CurseForge.
Also, the MC version I use is 1.7.10, and I was downloading the mod for that version.

**Comment by covers1624** [comment] 2018-03-03 23:30
`net/minecraftforge/fml/common/network/IGuiHandler` In 1.8 FML moved from `cpw.mods.fml` to `net.minecraftforge.fml`. You have installed the incorrect version of a mod for the minecraft version you are using. It should be fairly obvious from jar names, they usually include the name of the minecraft version in the file name. Closing as user error.

**Closed by covers1624** 2018-03-03 23:30 UTC

**Comment by tallpasha1** [comment] 2018-03-04 01:15
But the downloaded jar mod said it was 1.7.10!

**Comment by gigabit101** [comment] 2018-03-04 02:51
Link, image or it did not happen.

**Comment by tallpasha1** [comment] 2018-03-04 03:06
Link and the downloaded .jar said it was 1.7.10

**Comment by KingLemming** [comment] 2018-03-04 03:11
Look, you either downloaded a mod for the wrong version, somehow downloaded Forge for the wrong version, or you had the wrong version of Minecraft. Those are literally the only options.

TF does not cause a crash on 1.7.10.

**Comment by tallpasha1** [comment] 2018-03-04 05:15
MC was 1.7.10, the mod said it was for that specific version and I had the correct version of forge.

**Comment by covers1624** [comment] 2018-03-04 05:33
Look, this crash IS caused by a mod you have installed being for the incorrect version of mc, this is not a debate. It may not be TF, it could be another mod in your pack, but as you have provided no logs as i don't need them to diagnose this issue, i cannot tell you witch mod it is. You NEED start removing mods untill you find the issue. And please, take this to discord if you want some general support.

**Comment by covers1624** [comment] 2018-03-04 05:33
https://discord.gg/uRKrnbH
