### ISSUE TITLE
Factorizer Gives 9x Prismarine Shards From Prismarine Block, But You Need Only 4x Prismarine Shards To Obtain Prismarine Block to Craft It

### ISSUE THREAD

**Issue by kenijey** [CoFH/Feedback#1102] opened 2018-05-23 12:22 UTC
![1](https://user-images.githubusercontent.com/24831406/40424054-17192e7a-5e9d-11e8-9f05-660ea67637b2.PNG)
![2](https://user-images.githubusercontent.com/24831406/40424058-17f2fbfa-5e9d-11e8-9027-b7e21fc44a9b.PNG)
is it forgotten?..

**Comment by KingLemming** [comment] 2018-05-23 16:10
Duplicate of #1071.

**Closed by KingLemming** 2018-05-23 16:10 UTC
