### ISSUE TITLE
[MP] Overlay Tesseract Crash

### ISSUE THREAD

**Issue by DerMistkaefer** [CoFH/Feedback#983] opened 2015-12-26 08:43 UTC
When I overlay with the mouse a privat Tesseract in the Multiplayer then the Game is crashing.

Used Mods:

forge-1.7.10-10.13.4.1558-1.7.10-universal
CoFHCore-[1.7.10]3.1.0B1-321
ThermalExpansion-[1.7.10]4.1.0B1-234
ThermalFoundation-[1.7.10]1.2.1-109

Yes i know I use Alpha but i hope i can help you.

Client Crash:
```
---- Minecraft Crash Report ----
// Sorry :(

Time: 12/26/15 9:34 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at cofh.core.render.customcharrendering.RenderPlayerFace.loadTextures(RenderPlayerFace.java:54)
	at cofh.core.render.customcharrendering.RenderPlayerFace.setProfile(RenderPlayerFace.java:74)
	at cofh.core.render.customcharrendering.RenderPlayerFace.loadProfile(RenderPlayerFace.java:69)
	at cofh.core.render.CoFHFontRenderer.loadFontRendererStack(CoFHFontRenderer.java:271)
	at cofh.core.item.ItemBlockBase.getFontRenderer(ItemBlockBase.java:65)
	at net.minecraftforge.client.GuiIngameForge.renderToolHightlight(GuiIngameForge.java:596)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:154)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cofh.core.render.customcharrendering.RenderPlayerFace.loadTextures(RenderPlayerFace.java:54)
	at cofh.core.render.customcharrendering.RenderPlayerFace.setProfile(RenderPlayerFace.java:74)
	at cofh.core.render.customcharrendering.RenderPlayerFace.loadProfile(RenderPlayerFace.java:69)
	at cofh.core.render.CoFHFontRenderer.loadFontRendererStack(CoFHFontRenderer.java:271)
	at cofh.core.item.ItemBlockBase.getFontRenderer(ItemBlockBase.java:65)
	at net.minecraftforge.client.GuiIngameForge.renderToolHightlight(GuiIngameForge.java:596)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:154)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['DerMistkaefer'/262, l='MpServer', x=-186.55, y=64.62, z=96.46]]
	Chunk stats: MultiplayerChunkCache: 140, 140
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-188,64,52), Chunk: (at 4,4,4 in -12,3; contains blocks -192,0,48 to -177,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 34328 game time, 34328 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 67 total; [EntityClientPlayerMP['DerMistkaefer'/262, l='MpServer', x=-186.55, y=64.62, z=96.46], EntityCreeper['Creeper'/139, l='MpServer', x=-176.97, y=37.00, z=42.56], EntityZombie['Zombie'/140, l='MpServer', x=-190.50, y=40.00, z=107.50], EntityBat['Bat'/141, l='MpServer', x=-190.75, y=22.10, z=151.66], EntityCreeper['Creeper'/142, l='MpServer', x=-176.38, y=18.00, z=163.16], EntityZombie['Zombie'/143, l='MpServer', x=-180.53, y=48.00, z=176.25], EntityBlitz['Blitz'/148, l='MpServer', x=-175.34, y=36.00, z=47.38], EntitySkeleton['Skeleton'/149, l='MpServer', x=-156.06, y=34.00, z=51.50], EntityZombie['Zombie'/150, l='MpServer', x=-164.50, y=25.00, z=91.50], EntitySkeleton['Skeleton'/153, l='MpServer', x=-152.47, y=11.00, z=91.69], EntitySpider['Spider'/154, l='MpServer', x=-157.50, y=14.00, z=141.72], EntityBat['Bat'/155, l='MpServer', x=-147.75, y=15.10, z=144.25], EntityChicken['Chicken'/170, l='MpServer', x=-131.50, y=77.00, z=21.50], EntityChicken['Chicken'/171, l='MpServer', x=-139.53, y=66.38, z=17.16], EntityChicken['Chicken'/172, l='MpServer', x=-132.50, y=78.00, z=19.50], EntityChicken['Chicken'/173, l='MpServer', x=-131.19, y=69.00, z=22.75], EntitySheep['Sheep'/175, l='MpServer', x=-130.22, y=69.00, z=21.56], EntitySpider['Spider'/176, l='MpServer', x=-128.66, y=20.00, z=125.72], EntitySpider['Spider'/305, l='MpServer', x=-116.95, y=28.00, z=59.24], EntitySkeleton['Skeleton'/177, l='MpServer', x=-134.69, y=12.00, z=168.69], EntitySkeleton['Skeleton'/178, l='MpServer', x=-133.25, y=15.00, z=176.16], EntitySpider['Spider'/179, l='MpServer', x=-131.72, y=12.00, z=166.44], EntityCreeper['Creeper'/180, l='MpServer', x=-142.03, y=14.00, z=161.50], EntityCreeper['Creeper'/181, l='MpServer', x=-128.63, y=15.00, z=162.00], EntitySkeleton['Skeleton'/182, l='MpServer', x=-133.47, y=11.76, z=167.69], EntitySkeleton['Skeleton'/183, l='MpServer', x=-129.88, y=12.00, z=163.50], EntitySkeleton['Skeleton'/195, l='MpServer', x=-121.50, y=31.00, z=54.09], EntitySkeleton['Skeleton'/196, l='MpServer', x=-115.31, y=28.00, z=60.28], EntitySkeleton['Skeleton'/197, l='MpServer', x=-124.22, y=29.00, z=67.25], EntityBat['Bat'/199, l='MpServer', x=-130.56, y=17.84, z=91.93], EntityBat['Bat'/200, l='MpServer', x=-118.00, y=23.10, z=125.84], EntitySheep['Sheep'/72, l='MpServer', x=-245.44, y=69.00, z=18.66], EntityEnderman['Enderman'/201, l='MpServer', x=-117.69, y=37.00, z=126.63], EntityZombie['Zombie'/202, l='MpServer', x=-116.50, y=15.00, z=137.13], EntitySpider['Spider'/203, l='MpServer', x=-127.94, y=14.00, z=130.00], EntitySkeleton['Skeleton'/204, l='MpServer', x=-117.31, y=17.00, z=140.69], EntityZombie['Zombie'/205, l='MpServer', x=-115.94, y=16.00, z=139.47], EntityBat['Bat'/206, l='MpServer', x=-121.10, y=33.97, z=120.95], EntityEnderman['Enderman'/207, l='MpServer', x=-115.50, y=17.00, z=145.25], EntitySheep['Sheep'/80, l='MpServer', x=-229.91, y=62.57, z=135.97], EntitySkeleton['Skeleton'/208, l='MpServer', x=-113.50, y=17.00, z=147.50], EntitySheep['Sheep'/81, l='MpServer', x=-239.40, y=64.47, z=142.09], EntitySkeleton['Skeleton'/209, l='MpServer', x=-123.09, y=16.00, z=140.50], EntitySquid['Squid'/82, l='MpServer', x=-224.50, y=58.00, z=129.50], EntityZombie['Zombie'/210, l='MpServer', x=-114.50, y=17.00, z=145.94], EntitySquid['Squid'/83, l='MpServer', x=-226.75, y=59.31, z=129.50], EntityZombie['Zombie'/211, l='MpServer', x=-109.53, y=20.00, z=143.97], EntitySquid['Squid'/84, l='MpServer', x=-221.47, y=58.00, z=124.50], EntityBat['Bat'/212, l='MpServer', x=-116.61, y=18.10, z=146.99], EntitySheep['Sheep'/85, l='MpServer', x=-228.50, y=68.00, z=139.50], EntitySheep['Sheep'/86, l='MpServer', x=-239.50, y=66.00, z=144.16], EntitySkeleton['Skeleton'/216, l='MpServer', x=-107.50, y=26.00, z=50.06], EntitySkeleton['Skeleton'/217, l='MpServer', x=-111.03, y=23.00, z=52.66], EntitySpider['Spider'/219, l='MpServer', x=-111.72, y=39.00, z=92.47], EntityCreeper['Creeper'/220, l='MpServer', x=-109.75, y=15.00, z=130.16], EntityBat['Bat'/222, l='MpServer', x=-107.28, y=44.10, z=135.50], EntityZombie['Zombie'/100, l='MpServer', x=-217.41, y=23.00, z=22.88], EntitySheep['Sheep'/101, l='MpServer', x=-216.88, y=71.00, z=63.16], EntitySquid['Squid'/102, l='MpServer', x=-219.50, y=58.22, z=127.38], EntitySquid['Squid'/103, l='MpServer', x=-221.06, y=58.34, z=128.50], EntityHorse['Donkey'/115, l='MpServer', x=-203.56, y=68.00, z=22.19], EntityHorse['Donkey'/116, l='MpServer', x=-195.47, y=69.00, z=27.78], EntityHorse['Donkey'/117, l='MpServer', x=-199.73, y=68.00, z=25.27], EntityHorse['Donkey'/118, l='MpServer', x=-197.72, y=68.00, z=26.91], EntitySheep['Sheep'/119, l='MpServer', x=-206.50, y=70.00, z=71.50], EntitySheep['Sheep'/120, l='MpServer', x=-206.50, y=66.00, z=77.22], EntitySheep['Sheep'/121, l='MpServer', x=-206.69, y=71.00, z=86.47]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 267826320 bytes (255 MB) / 596115456 bytes (568 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCHIJA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCHIJA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJA	CoFHCore{1.7.10R3.1.0B1} [CoFH Core] (CoFHCore-[1.7.10]3.1.0B1-321.jar) 
	UCHIJA	ThermalFoundation{1.7.10R1.2.1} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.1-109.jar) 
	UCHIJA	ThermalExpansion{1.7.10R4.1.0B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.0B1-234.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 361.43' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	CoFHCore: -[1.7.10]3.1.0B1-321
	ThermalFoundation: -[1.7.10]1.2.1-109
	ThermalExpansion: -[1.7.10]4.1.0B1-234
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.5.0 NVIDIA 361.43, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
```
[crash-2015-12-26_09.34.38-client.txt](https://github.com/CoFH/Feedback/files/72386/crash-2015-12-26_09.34.38-client.txt)

Server log:
Client Server leave:
```
java.io.IOException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_66]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_66]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_66]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_66]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_66]
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:436) ~[UnpooledUnsafeDirectByteBuf.class:?]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:870) ~[AbstractByteBuf.class:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208) ~[NioSocketChannel.class:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:87) [AbstractNioByteChannel$NioByteUnsafe.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
```

**Comment by skyboy** [comment] 2015-12-27 00:01
Duplicate of https://github.com/CoFH/Feedback/issues/980

**Closed by skyboy** 2015-12-27 00:01 UTC
