### ISSUE TITLE
Crash on placing any energy cell client side

### ISSUE THREAD

**Issue by Kvasyr** [CoFH/Feedback#859] opened 2015-09-30 22:36 UTC
Crash log: http://pastebin.com/QaJWmTwx

The server is still running but client crashes
I dont really know what's going on, I would really appreciate if you guys could lend a hand 
thanks!

**Comment by KingLemming** [comment] 2015-09-30 23:42
Duplicate of #818. Caused by client-server item mismatch, as far as we can tell. Can you make it happen with *only* CoFH mods? I'm about 99% sure this is entirely x-mod and/or the fault of a script.

**Closed** 2015-10-01 19:45 UTC
