### ISSUE TITLE
[Thermal Dynamics] Divide by zero crash for fluids with zero viscosity

### ISSUE THREAD

**Issue by Zekrom64** [CoFH/Feedback#1116] opened 2016-03-19 02:03 UTC
Mod: Thermal Dynamics 1.7.10-1.1.0-161
List of mods installed: http://pastebin.com/ihW3edFW
Crash report: 
[crash-2016-03-18_17.53.42-server.txt](https://github.com/CoFH/Feedback/files/180581/crash-2016-03-18_17.53.42-server.txt)

When trying to transport a fluid with a viscosity of zero (In my case, liquid helium from Nuclearcraft) in a fluiduct, the game crashes with a divide by zero error. After finding the offending code using the stack trace and JD-GUI, this appears to be caused by trying to determine the fluid throughput by dividing a number by the viscosity and not checking if the viscosity is zero. This crashes both client and server as I had first discovered this bug on a friend's server. This exception occurs whenever the fluiducts transporting the liquid are loaded, making it impossible to keep the world loaded.

**Comment by KingLemming** [comment] 2016-03-19 14:21
Duplicate of #1070 and was supposedly fixed on their end. Update your mods.

**Closed by KingLemming** 2016-03-19 14:21 UTC
