### ISSUE TITLE
ClientSideCrash

### ISSUE THREAD

**Issue by CatAndHorse** [CoFH/Feedback#410] opened 2017-07-22 12:59 UTC
Time: 7/22/17 8:48 PM
Description: Tessellating CCL block in world

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Unknown Source)
	at java.nio.DirectByteBuffer.putFloat(Unknown Source)
	at net.minecraft.client.renderer.BufferBuilder.func_187315_a(BufferBuilder.java:208)
	at codechicken.lib.render.CCRenderState.writeVert(CCRenderState.java:187)
	at codechicken.lib.render.CCRenderState.render(CCRenderState.java:167)
	at codechicken.lib.render.CCModel.render(CCModel.java:460)
	at codechicken.lib.render.CCModel.render(CCModel.java:448)
	at cofh.thermaldynamics.render.RenderDuct.renderBase(RenderDuct.java:168)
	at cofh.thermaldynamics.render.RenderDuct.renderBlock(RenderDuct.java:394)
	at codechicken.lib.render.block.BlockRenderingRegistry.renderBlock(BlockRenderingRegistry.java:90)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:52)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:172)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:975)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1307)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1250)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1053)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.nio.Buffer.checkIndex(Unknown Source)
	at java.nio.DirectByteBuffer.putFloat(Unknown Source)
	at net.minecraft.client.renderer.BufferBuilder.func_187315_a(BufferBuilder.java:208)
	at codechicken.lib.render.CCRenderState.writeVert(CCRenderState.java:187)
	at codechicken.lib.render.CCRenderState.render(CCRenderState.java:167)
	at codechicken.lib.render.CCModel.render(CCModel.java:460)
	at codechicken.lib.render.CCModel.render(CCModel.java:448)
	at cofh.thermaldynamics.render.RenderDuct.renderBase(RenderDuct.java:168)
	at cofh.thermaldynamics.render.RenderDuct.renderBlock(RenderDuct.java:394)
	at codechicken.lib.render.block.BlockRenderingRegistry.renderBlock(BlockRenderingRegistry.java:90)

-- Block being tessellated --
Details:
	Block type: ID #722 (tile.cofh.duct // cofh.thermaldynamics.block.BlockDuct)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (3008,86,-2978), Chunk: (at 0,5,14 in 188,-187; contains blocks 3008,0,-2992 to 3023,255,-2977), Region: (5,-6; contains chunks 160,-192 to 191,-161, blocks 2560,0,-3072 to 3071,255,-2561)
Stacktrace:
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:52)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:172)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:975)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1307)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1250)

**Comment by KingLemming** [comment] 2017-07-22 17:19
We need a modlist, version, some other info.

If you have Optifine, it's probably not us.

**Comment by CatAndHorse** [comment] 2017-07-23 04:38
I reproduced this crash.By put a large number of thermal ducts together and have the vanilla vertex buffer option turned on.
The Vanilla vertex buffer is too small for mods

**Comment by covers1624** [comment] 2017-07-23 12:03
Well the buffer increases its size if it cant fit another quad. We need your FULL crash report, it contains data we need to debug this.

**Comment by CatAndHorse** [comment] 2017-07-24 06:50
https://pastebin.com/wW1KgJhe

FULL crash report is here

**Comment by Dr-Zoidberg-de** [comment] 2017-08-02 13:12
anything new on htis? i got the same error. a network of 40-60 itemducts (opaque) is enough to let the client crash randomly. 
[https://pastebin.com/pMLWswJ9](url)

**Comment by KingLemming** [comment] 2017-08-02 20:16
Nope. Can't replicate this at all. Likely x-mod or OS/hardware specific.

**Comment by covers1624** [comment] 2017-08-22 13:02
So i can't replicate this at all. Placed a [16x16x16 cube of Ducts](http://ss.covers1624.net/eujghgy.png) down and no issues. This is likely one of the following:
1. The buffer was never allocated the requested space. (This is extremely bad, update java.)
2. An FPS improvement mod is breaking the buffer somehow. (Remove any Optifine, BetterFPS, FastCraft, FoamFix If removing fixed the issue report to them link back here.)
3. Outdated video card drivers (Update them, Unlikely that its an issue with drivers but do it anyway.)

If nothing fixes the issue, provide a world download, and a minimal mods list that this is replicatable for you.

**Comment by wcdanh2** [comment] 2017-09-06 03:18
I believe I encountered this same Issue.  [pastebin](https://pastebin.com/htee2Yuf) 
I was unable to login without an almost immediate crash.  I was able to fix my server by using MCedit to remove the Fluid-duct mentioned in the crash report.

A few things I find interesting:
1: the fluidduct was not one that was recently placed, and replacing it will cause the crash again after a short period of time.
2:  I got the crash on both my Win7 PC and Ubuntu laptop.  On the laptop I logged in with a different user who had no inventory (had only been logged in once prior)
3:  I got the same crash when I transferred the server's world files and opened the game as single player.

I have saved a copy of the aromaBackup zipped world. (100MB zipped not sure of a good way of transferring it)  The current mod list is default Forever Stranded 1.9.1

**Comment by Cobra1117** [comment] 2017-09-14 01:47
Also seeing this issue. Crash log: https://pastebin.com/W6wE8HzS

**Comment by Cobra1117** [comment] 2017-09-14 01:49
Also, possibly related, possibly not: https://pastebin.com/dR6nqmiH

If this happens in a chunk w/ Thermal Expansion machines, every servo disappears and every machine has its outputs set to the same configuration.

(Shooting in the dark here, just in case any of this is useful in debugging!)

**Comment by covers1624** [comment] 2017-09-14 03:04
The issue with machines and ducts looking weird is due to a forge issue that was recently introduced and then fixed again, its un related. The actual issue here is impossible to debug, strip your mods list down to the minimal set required to make this happen, update your video card drivers and java.

**Comment by Cobra1117** [comment] 2017-09-14 03:58
Testing results (will update as I try things):

Updating Drivers: Client crash
Updating Java: N/A (already running latest--1.8.0_144-b01)
Downloaded world from remote dedicated server, ran as single player map: Works as expected, no obvious corruption of surrounding area
Downloaded world from remote dedicated server, ran on local dedicated server: Client crash

**Comment by covers1624** [comment] 2017-09-14 08:29
Poke me over on IRC, #ThermalExpansion on Esper.net, it may be something with your world, i don't want to dirty this issue with something that can be discussed on irc.

**Comment by Cobra1117** [comment] 2017-09-28 01:45
Sorry--haven't been able to catch you on Curse. Here's the smallest mod list I could replicate this issue with:
appliedenergistics2-rv5-alpha-4.jar                                   
CodeChickenLib-1.12-3.1.2.311-universal.jar                           
CoFHCore-1.12-4.3.5.13-universal.jar                                  
CoFHWorld-1.12-1.0.1.8-universal.jar                                  
RedstoneFlux-1.12-2.0.1.2-universal.jar                               
mcjtylib-1.12-2.4.4.jar                                               
rftools-1.12-6.13.jar                                                 
rftoolsdim-1.12-5.04.jar                                              
ThermalDynamics-1.12-2.3.5.12-universal.jar                           
ThermalExpansion-1.12-5.3.5.19-universal.jar                          
ThermalFoundation-1.12-2.3.5.14-universal.jar                         

Also, this issue has only occurred with opaque impulse itemducts, although I'm not using a lot of other itemducts. (This issue has never occurred with fluiducts.)

Suggestion: If you could add a try/catch to that rendering code and have it just render something obvious (missing block texture for example) or don't render it and just log the x/y/z location, then I could hunt down where exactly this happens and give you more details. (This happens regularly in my world now. I can temporarily fix it by removing ducts with WorldEdit, but the issue comes back, usually after a server restart.)

**Comment by covers1624** [comment] 2017-09-28 04:03
Yeah sorry haven't been arround much lately, chuck me a world download aswel for good measure if you don't mind and ill check it out later this week.

**Comment by Cobra1117** [comment] 2017-09-29 04:09
Here's the server download link: https://www.dropbox.com/s/zsgqemv4llrisiq/server.zip?dl=0

I've cut down the download as much as possible, so if the issue doesn't occur for you then I'll upload the entire server.

The broken blocks are in the bottom floors of the base in RFTools Dimension 4.  You should be able to get there via the command ```/rfttp tp 4 0 200 0```. From there, just fall down the elevator shaft into the base.

**Comment by covers1624** [comment] 2017-10-18 12:46
@Cobra1117 I've loaded up your world in dev and have not experienced any crashes. Poke me over on twitch chat, If you don't mind, i may have to join your server and see if i can get it to occur.

**Comment by covers1624** [comment] 2017-10-18 15:34
Ok, Ive gotten a map from another person and have been able to reproduce the issue locally.

**Comment by covers1624** [comment] 2017-10-29 13:43
Ok i have tracked down this issue, It seems that its somewhat a vanilla bug. It seems that the buffer is indeed not expanding at all only when things happen a specific order. BakedQuads are added to the buffer via `addVertexData` this method will only ever ensure that there is enough space for the current quad being inserted. Where as the way TD adds the duct's quads is via the `pos` `tex` `endVertex` methods. `endVertex` has to be called at the end of each vertex and it ensures that there is enough space for the next vertex, IF the buffer is almost filled by a BakedQuad with `addVertexData` literelly bytes from being full, then subsequent calls using `pos` `tex` etc, will cause the buffer to overflow. Waiting on a response from mezz as to the best route to fix this issue. It all boils down to the Buffer used for the cutout layer having a smaller initial capacity than the solid layer, TD ducts render entirely on the cutout layer as their texture has alpha. We can either patch `addVertexData` to ensure there is enough room for the current quad AND the next vertex or we can just bump the initial size of the buffer. IMO, the first option is cleaner and the buffer expanding / filling doesnt happen all too often and honestly wont be too bad on performance.

**Comment by Cobra1117** [comment] 2017-11-01 04:46
Ack! Apologies for not getting back to you quickly, but glad you were able to find the bug without me!

**Comment by KingLemming** [comment] 2017-11-30 01:04
This has now been handled in Forge and there is a vanilla ticket submitted as well, as it should be.

**Closed by KingLemming** 2017-11-30 01:04 UTC
Labels: bug - forge, bug - mojang

**Comment by Maulkin12** [comment] 2018-03-28 08:27
If I understand this thread correctly, the problem is with Forge/Mojang. While this ticket was submitted for 1.12, I'm encountering the same issue in 1.10.2 - is there a fix for it?

**Comment by covers1624** [comment] 2018-03-28 08:53
No there is no fix for 1.10. Update to 1.12 is your only option.
