### ISSUE TITLE
[Crash] At mine ExtraUtils 2 Crusher in cofh.core.proxy.EventHandler.handleHarvestDropsEvent

### ISSUE THREAD

**Issue by VladimirMangos** [CoFH/Feedback#1309] opened 2018-10-02 22:02 UTC
https://paste.dimdev.org/gobewimodo.mccrash

java.lang.UnsupportedOperationException
    at com.google.common.collect.ImmutableList.replaceAll(ImmutableList.java:553)
    at cofh.core.proxy.EventHandler.handleHarvestDropsEvent(EventHandler.java:294)

At mine ExtraUtils 2 Crusher

**Comment by KingLemming** [comment] 2018-10-02 23:20
Duplicate of #1306. Please check closed issues before posting if you would. :)

**Closed by KingLemming** 2018-10-02 23:20 UTC
