### ISSUE TITLE
Thermal Expansion crash on startup

### ISSUE THREAD

**Issue by tristan1301** [CoFH/Feedback#270] opened 2017-06-18 14:29 UTC
Updated the COFH mods in my client, and it has crashed in this manner consistently since. No other changes made to either configs or mod updates/additions.

Crash Log: https://paste.ee/p/axTcL

**Comment by covers1624** [comment] 2017-06-18 14:33
Duplicate of https://github.com/CoFH/Feedback/issues/265

**Closed by covers1624** 2017-06-18 14:33 UTC

**Comment by tristan1301** [comment] 2017-06-18 14:38
I hate to push this, but if the mitigation was included in the updates from just over an hour ago, this is after those updates.
