### ISSUE TITLE
[Thermal Foundation/Expansion] - Issues with Tinker's Construct Parts

### ISSUE THREAD

**Issue by Caeldeth** [CoFH/Feedback#161] opened 2015-02-23 04:12 UTC
I >think< I'm on the right mod for the source of the issue, but it was hard to determine if TiC had built in support for MFR/TF, or if MFR/TF was inserting parts into TiC.  Either way, if this needs to go over to TiC's github, just let me know!

Using the latest release versions:
ThermalExpansion rc1-119
ThermalFoundation rc1-69
TinkersConstruct 1.8.2a
MineFactoryReloaded rc7-71
ExtraTiC 1.0.3 (also tested without this mod installed)
Libs:
COFHCore rc1-181
COFHLib b9-112
Mantle 0.3.2

Any of the tool parts (tool rod, heavy plate, hammer head, etc) cannot be melted down if they are made with TF/E materials (Electrum, Platinum/Shiny, etc).  Also, any TiCon tool made with any of those parts that drive the "Repair material" part (i.e., pickaxe head) cannot be repaired in the Tool Forge with the correct ingot or storage block.

A few people have mentioned it in the ExtraTiC thread (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1445212-extratic-tinkers-construct-mod-support-add-on), but the ExtraTiC versions of the materials (electrum, platinum, etc) work as expected - these parts are no longer directly accessible (must be spawned in creatively) because of the new added support.

The MFR material related tools (pink slime, plastic) function as expected though!   Also, as one of those people who do bad things (ie, use the alpha versions), I've noticed this has been occurring through-out the builds issued from mid-January-ish on.  I don't know the exact build that it started in though!

**Comment by codewarrior0** [comment] 2015-02-23 09:12
Hi! I'm almost certain this is an issue for TinkersConstruct itself. That mod has a built in Thermal Expansion plugin that has seen a lot of work done in the past few weeks, so maybe this issue is already fixed. You can report it here: https://github.com/SlimeKnights/TinkersConstruct/issues

**Comment by codewarrior0** [comment] 2015-02-23 09:17
So sorry! Ignore what I said. It looks like both TiCon and TE have built in support for each other, and in the mod versions you are using, it is TE that is adding electrum et al. as material parts to TiCon.

**Comment by codewarrior0** [comment] 2015-02-23 10:47
This seems to be partly fixed in the development version of TiCon. I was able to reproduce the issue with TiCon 1.8.2a. When building TiCon from the latest source on GitHub, the issue is half-fixed: I can repair electrum tools with ingots, but still cannot smelt electrum parts back down to molten metal.

**Comment by KingLemming** [comment] 2015-02-23 10:54
Ah. Interesting. Good to know.

**Comment by codewarrior0** [comment] 2015-02-23 11:12
Found it. TiCon's addPartCastingMaterial IMC needs to take the tool parts it creates and register melting recipes with the smeltery. Definitely not a TE issue. I opened an issue with TiCon, so this one could probably be closed.

**Comment by codewarrior0** [comment] 2015-02-23 12:21
Pretty sure I just fixed it. SlimeKnights/TinkersConstruct#1423

It's worth noting that the ExtraTiC versions of these tool parts could be smelted back into metal because ExtraTiC doesn't use IMC to register its parts, instead it gets intimate with TiC's internals (and thus would have to be updated whenever tools or tool parts are added to TiC).

**Comment by skyboy** [comment] 2015-02-23 14:31
Closing as the resolution is on TCon's end

**Closed by skyboy** 2015-02-23 14:31 UTC
