### ISSUE TITLE
[Thermal Dynamics] Signalum-Plated Impulse Itemduct connecting to Cryostabilized Fluxduct

### ISSUE THREAD

**Issue by Gorden211** [CoFH/Feedback#621] opened 2017-11-07 23:51 UTC
I just encountered another crash probably related to Thermal Dynamics, when connecting a Signalum-Plated Impulse Itemduct to a Cryostabilized Fluxduct.
Here's the crashlog: https://pastebin.com/0c0RBxaT
Unfortunately I cannot provide a screenshot here, because I had to roll-back the world since rejoining immediately crashed the client again. The local server I have set up however still runs.
The modpack is All The Mods 3.

**Comment by KingLemming** [comment] 2017-11-08 00:02
Duplicate of #410. This is a Mojang / Forge issue.

**Closed by KingLemming** 2017-11-08 00:02 UTC
