### ISSUE TITLE
Redstone relay not updating when on comparator mode

### ISSUE THREAD

**Issue by kmork1** [CoFH/Feedback#874] opened 2018-01-21 17:23 UTC
Not sure if this is you guys or botanic. But I have a Redstone relay attached to a mana pool in comparator mode so I can’t track fullness. However the relay power and duct power only update if I open the GUI of the Redstone relay. Other wise it’ll be stuck on wherever I checked it on last. Like if it was 10 it’ll stay 10 even if the pool is full until I right click it. I’m minecraft 1.12. Thermal dynamics 2.3.9.3. On direwolf20 1.12 pack v 1.5 on a server.

**Comment by KingLemming** [comment] 2018-01-21 17:51
Duplicate of #840. Don't expect a fix.

**Closed by KingLemming** 2018-01-21 17:51 UTC
