### ISSUE TITLE
CoFH and EnderIO bug, EnderIO says its you

### ISSUE THREAD

**Issue by enterprise12nx** [CoFH/Feedback#589] opened 2015-06-08 00:21 UTC
Here is the report https://github.com/SleepyTrousers/EnderIO/issues/2555#issuecomment-109798813

Please say you can fix it, because i report bugs between you EnderIO and Mekanism so much but they all say "its not me"

really hoping this can be fixed

**Comment by KingLemming** [comment] 2015-06-08 01:05
Duplicate of #475. Search? ;)

**Closed by KingLemming** 2015-06-08 01:05 UTC
