### ISSUE TITLE
[Thermal Expansion] When trying to add a recipe that includes slag to a schematic, the game crashes

### ISSUE THREAD

**Issue by monsterlyrics** [CoFH/Feedback#1034] opened 2016-02-01 03:34 UTC
Mod in question: Thermal Expansion 4.1.1-237

Problem originally occurred in my modpack, but it continues to occur when only using the absolute necessary mods (Expansion, Foundation, and CoFH Core)

Crash log: http://pastebin.com/1ZWBqyKt

When I try to add any recipe that contains slag to a schematic, the game instantly crashes. I haven't found any other items that cause the same problem. 

The issue does not occur in 4.1.0B1-235.

Any ideas?

**Comment by skyboy** [comment] 2016-02-01 07:58
Duplicate of https://github.com/CoFH/Feedback/issues/1018

**Closed by skyboy** 2016-02-01 07:58 UTC
