### ISSUE TITLE
Tesseracts won't output items on world reload/losing frequency on reload?

### ISSUE THREAD

**Issue by bluewave41** [CoFH/Feedback#729] opened 2015-07-24 01:48 UTC
CoFHCore-[1.7.10]3.0.3-303
ThermalDynamics-[1.7.10]1.1.0-161
ThermalExpansion-[1.7.10]4.0.3B1-218
ThermalFoundation-[1.7.10]1.2.0-102
forge-1.7.10-10.13.4.1492

These are the only 4 mods I have testing this.

This here is my setup: http://puu.sh/jaALC/4e98b1dc05.jpg

Both tesseracts on frequency 1. Left is set to send items right is set to receive items

Frequency 1: Put item in chest on left side, item goes in left side and comes out inside right chest.
Reload world
Frequency 1: Put item in chest on left side, item goes in left tesseract, never comes out the right side.
Change frequency of both tesseracts to 2
Frequency 2: Put item in chest on left side, item goes in left side and comes out inside right chest.
Reload world
Frequency 2: Put item in chest on left side, item goes in left tesseract, never comes out the right side.
Change frequency of both tesseracts to 1
Change frequency of both tesseracts to 2
Frequency 2: Put item in chest on left side, item goes in left side and comes out inside right chest.

Tesseracts seem to unlink or forget their frequencies on world reload causing items that go through them to disappear forever.

**Comment by KingLemming** [comment] 2015-07-24 13:59
Can't make this happen.

**Comment by KingLemming** [comment] 2015-07-24 16:26
Found the cause. Forge bug where a specific event is not firing when it should be. I'll have a workaround later.

For now, it's an easy fix on your end. Don't reload a world. Exit the game fully.

**Comment by bluewave41** [comment] 2015-07-24 20:04
I switched to ender chests for now.  It was pretty annoying losing items but I'm glad it can be fixed.

**Comment by KingLemming** [comment] 2015-07-24 20:19
It's somewhat surprising that nobody has ever seen this til now, but given that it can only happen in single player, and only when you play, go back to the main menu, and play again...ehh.

**Comment by ZeldoKavira** [comment] 2015-07-25 03:22
Fixed in dev, will be in the next release.

**Comment by expl0s1ve** [comment] 2015-09-04 09:01
When is the next release? There's not even a dev build released after his.

**Comment by Rasmun** [comment] 2015-10-03 04:29
Hi KingLemming,

I found a problem with Tesseracts transferring less power in a similar situation, after logging out of Minecraft in single player and logging back in.  I was using it with Big Reactors, but below is an easy way to test it with a Creative Energy Cell.

1) Connect a Tesseract to a somewhat large Ender IO Capacitor Bank multi-block (I used a bank of 18 Vibrant Capacitor Banks) and create an input frequency for energy.
2) Use the wrench on the Capacitor Bank a few times to show the IO panel (to monitor input).
3) Connect a Tesseract to a Creative Energy Cell and setup this Tesseract to send power on the same frequency.
4) After connecting the above, you will see 100K transfer rate in a few seconds.
5) Logout, but do not close, Minecraft.
6) Login to Minecraft.
Result:
7) Only a 50K transfer rate after logging in again.  If I delete the channel and create a new one, I can get it back to transferring 100K again (or if I completely close/open Minecraft, which takes forever with all these mods and texture packs LOL)

Note:  I am using Minecraft 1.7.10 with the latest Direwolf20 pack and ThermalExpansion-[1.7.10]4.0.3B1-218

Anyway, is this fixed in Dev with the issue reported here, or should I create a new issue for this?

Thanks

**Closed** 2016-01-25 23:52 UTC
Labels: bug, fixed, fixed in dev, TE
