### ISSUE TITLE
[Thermal Dynamics] Preventing ducts from connecting on placement

### ISSUE THREAD

**Issue by RoqueDeicide** [CoFH/Feedback#517] opened 2015-05-12 07:01 UTC
I might be missing something but I have no idea how to prevent ducts from connecting to already placed ones when placed. This is not really an issue for itemducts or fluxducts, this is an issue for fluiducts: When I need to run a line of fluiducts that is adjacent to another one that already has a fluid inside the new line always connects to existing one and that causes liquid from it to go into the new one, which is not something I want: I don't need, for instance, water in my liquifacted coal pipeline. Currently what I have to do is:
 1) Place all of the ducts that are adjacent to already existing ones;
 2) Disconnect them from the existing pipeline;
 3) Drain them of any liquid they got from the old ducts.

This process is as annoying as it might sound. I just wish there was a way to stop ducts from connecting. May go back to the olden days of new fluiducts not connecting to ducts that have fluid already in them?

**Comment by KingLemming** [comment] 2015-05-12 13:26
Duplicate of #147

**Closed by KingLemming** 2015-05-12 13:26 UTC
