### ISSUE TITLE
I have this in my logs of server + freeze every 2 seconds on client side

### ISSUE THREAD

**Issue by boistordu** [CoFH/Feedback#494] opened 2017-08-23 15:13 UTC
Maybe it's not related but still it's a problem. version 1.10.2 as you can see in the logs 
version2422 for forge.

```
Server thread/WARN - FML 23/08/2017 14:04:56
14:04:56****************************************
* The API cofhapi from source /home/AMP/.ampdata/instances/myadmin/Minecraft/mods/CoFHCore-1.10.2-4.1.11.16-universal.jar is loaded from an incompatible classloader. THIS WILL NOT WORK!
* at net.minecraftforge.fml.common.ModAPIManager$APIContainer.validate(ModAPIManager.java:113)
* at net.minecraftforge.fml.common.ModAPIManager.registerDataTableAndParseAPI(ModAPIManager.java:173)
* at net.minecraftforge.fml.common.ModAPIManager.manageAPI(ModAPIManager.java:231)
* at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:532)
* at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
* at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)...
****************************************
****************************************
* The API cofhapi|block from source /home/AMP/.ampdata/instances/myadmin/Minecraft/mods/CoFHCore-1.10.2-4.1.11.16-universal.jar is loaded from an incompatible classloader. THIS WILL NOT WORK!
* at net.minecraftforge.fml.common.ModAPIManager$APIContainer.validate(ModAPIManager.java:113)
* at net.minecraftforge.fml.common.ModAPIManager.registerDataTableAndParseAPI(ModAPIManager.java:173)
* at net.minecraftforge.fml.common.ModAPIManager.manageAPI(ModAPIManager.java:231)
* at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:532)
* at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
* at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)...
****************************************
****************************************
* The API cofhapi|energy from source /home/AMP/.ampdata/instances/myadmin/Minecraft/mods/CoFHCore-1.10.2-4.1.11.16-universal.jar is loaded from an incompatible classloader. THIS WILL NOT WORK!
* at net.minecraftforge.fml.common.ModAPIManager$APIContainer.validate(ModAPIManager.java:113)
* at net.minecraftforge.fml.common.ModAPIManager.registerDataTableAndParseAPI(ModAPIManager.java:173)
* at net.minecraftforge.fml.common.ModAPIManager.manageAPI(ModAPIManager.java:231)
* at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:532)
* at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
* at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)...
```

**Comment by KingLemming** [comment] 2017-08-23 15:23
This isn't caused by us, sorry.

Also, I would really advise moving to 1.12.

**Closed by KingLemming** 2017-08-23 15:23 UTC

**Comment by boistordu** [comment] 2017-08-23 15:25
wand by who is it causing then?
and I can't moving to 1.12 since not every mods are in 1.12

**Comment by KingLemming** [comment] 2017-08-23 15:30
Whoever is mucking with the classloader. There's nothing in the log that really explains much. I just know that we don't screw with the classloader in such a fashion that this would happen.

Also, times change. There are new mods on 1.12. Try them.

**Comment by boistordu** [comment] 2017-08-23 15:31
not railcraft dear nor buildcraft :p

**Comment by boistordu** [comment] 2017-08-23 15:31
but thanks for the specification.

**Comment by KingLemming** [comment] 2017-08-23 15:32
Buildcraft is very close, and Railcraft has kind of been a shell of itself in the entire 1.10+ era.

**Comment by boistordu** [comment] 2017-08-23 15:33
Maybe but I'm patreon man, can't really move away from that :)

**Comment by KingLemming** [comment] 2017-08-23 15:34
You should lean on CJ to update then. ;) It really is a trivial process compared to moving up from 1.7.

**Comment by boistordu** [comment] 2017-08-23 15:37
Yeah yeah sure but at how much big of a team and we are in the process to rewrite first the whole code for every items of railcraft first.  but thanks anyway

**Comment by covers1624** [comment] 2017-08-23 15:43
This is caused by us having API annotations and also being a coremod in 1.10. just ignore it.
