### ISSUE TITLE
Thermal expansion & Thermal dynamics crash:

### ISSUE THREAD

**Issue by TheFjonG** [CoFH/Feedback#588] opened 2015-06-07 22:02 UTC
Thermal dynamics version: 4.0.1 -182
Thermal dynamics version: Latest (->1.0.0-122->1.0.0-130)

Report: http://pastebin.com/VXCTK0cx

My case: I clicked through the different modes on one of the sides and it crashed

**Comment by KingLemming** [comment] 2015-06-07 22:34
Duplicate of #475. It's specific to the Insolator.

**Closed by KingLemming** 2015-06-07 22:34 UTC
