### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by MikeArclight** [CoFH/Feedback#56] opened 2015-01-27 22:45 UTC
So here's the thing; I'm trying to download Thermal Expansion for 1.7.10 for better tech integration with the Big Reactors mod. I have seen it done on a few mod showcases and am envious of their results (so far, I can not achieve the same with my current mods). In any event, I'll never know since this keeps happening: 

http://hastebin.com/ruqupejoda.coffee 

I have tried every CoFH Core, Thermal Expansion, and Thermal Foundation download for 1.7.10 that I could find; all with either the same result or some sort of conflict (ie - minimum dependency not met). I also tried it with *just* CoFH Core (3.0.0.B9-40), Thermal Foundation(1.0.0RC1-27), and Thermal Expansion (4.0.0B8-23) loaded. By the looks of it, CoFH Core is trying something illegal that Java doesn't like; but then again, I'm no good with code so it very well could be aliens. (I know I'm running Forge v. 1236, but it's the most stable version for me - if that's the issue, I don't know what to say)

I don't expect a silver bullet fix here; just dropping this on you to let you know that something weird is going on.

**Comment by KingLemming** [comment] 2015-01-27 23:11
Seems like access transformers aren't working for you for some reason. This is particular to your setup and is not a code issue.

Try with only the latest *release* versions. Nothing fancy, no alphas, nothing from CurseForge. Curse *only.*

**Comment by KingLemming** [comment] 2015-01-28 00:49
Are you running this on a Mac by chance?

**Comment by cheeseonhead** [comment] 2015-01-28 01:50
He's on Windows 7 I believe, by the CR he provided.

**Comment by simon-itch** [comment] 2015-01-28 19:39
Dear TeamCOFH
I have a similar problem - been unable to update from -
COFHCORE 1.7.10 3.0.0B8-36
COFHLIB 1.7.10 1.0.0B7-29
THERMALEXPANSION 1.7.10 4.0.0B6-16
THERMALFOUNDATION 1.0.0B3-8

These are the only versions i can run i've tried every new version since - As and Bs - always crashes

Crash messages seem to vary from version to version - latest versions give this crash 


PS - sorry can't workout how to hide the binking crash report - sorry for visual pollution...

Any suggestion what to do my side?

---- Minecraft Crash Report ----
// You're mean.

Time: 1/28/15 8:28 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: thermalexpansion.item.tool.ItemWrench.setMaxStackSize(I)Lnet/minecraft/item/Item;
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: thermalexpansion.item.tool.ItemWrench.setMaxStackSize(I)Lnet/minecraft/item/Item;
	at thermalexpansion.item.tool.ItemWrench.<init>(ItemWrench.java:35)
	at thermalexpansion.item.TEItems.preInit(TEItems.java:30)
	at thermalexpansion.ThermalExpansion.preInit(ThermalExpansion.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.9.4
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 5846498120 bytes (5575 MB) / 6429081600 bytes (6131 MB) up to 6429081600 bytes (6131 MB)
	JVM Flags: 8 total; -XX:PermSize=4G -XX:MaxPermSize=4G -Xmx6G -Xms6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1277 Minecraft Forge 10.13.2.1277 71 mods loaded, 71 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.85.1277} [Forge Mod Loader] (forge-1.7.10-10.13.2.1277.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.2.1277} [Minecraft Forge] (forge-1.7.10-10.13.2.1277.jar) Unloaded->Constructed->Pre-initialized
	appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	monnef-core{0.7.2} [monnef Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) Unloaded->Constructed->Pre-initialized
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	lotr{Beta v21.3 for Minecraft 1.7.10} [The Lord of the Rings Mod] ([1.7.10] The Lord of the Rings Mod B21.3.jar) Unloaded->Constructed->Pre-initialized
	DamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed->Pre-initialized
	appliedenergistics2{rv1-stable-1} [Applied Energistics 2] (appliedenergistics2-rv1-stable-1.jar) Unloaded->Constructed->Pre-initialized
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized
	Thaumcraft{4.2.3.4} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.4.jar) Unloaded->Constructed->Pre-initialized
	Automagy{0.18} [Automagy] (Automagy-1.7.10-0.18.jar) Unloaded->Constructed->Pre-initialized
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1057-universal.jar) Unloaded->Constructed->Pre-initialized
	CoFHCore{1.7.10R3.0.0B9} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B9-103.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Core{6.2.6} [BuildCraft] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Transport{6.2.6} [BC Transport] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Silicon{6.2.6} [BC Silicon] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Builders{6.2.6} [BC Builders] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Energy{6.2.6} [BC Energy] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Factory{6.2.6} [BC Factory] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized
	craftguide{1.6.8.1} [CraftGuide] (CraftGuide-1.6.8.1.zip) Unloaded->Constructed->Pre-initialized
	dungeonpack{1.7.10-1.0} [Dungeon Pack] (dungeonpack-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized
	EnderIO{1.7.10-2.2.6.317} [Ender IO] (EnderIO-1.7.10-2.2.6.317.jar) Unloaded->Constructed->Pre-initialized
	EnderStorage{1.4.5.27} [EnderStorage] (EnderStorage-1.7.10-1.4.5.27-universal.jar) Unloaded->Constructed->Pre-initialized
	ThermalFoundation{1.7.10R1.0.0RC1} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC1-31.jar) Unloaded->Constructed->Pre-initialized
	ThermalExpansion{1.7.10R4.0.0B8} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0B8-23-dev.jar) Unloaded->Constructed->Errored
	enhancedportals{3.0.10} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.10.jar) Unloaded->Constructed->Pre-initialized
	extrabuttons{1.7.10.1} [ExtraButtons] (ExtraButtons-1.7.10.1.jar) Unloaded->Constructed->Pre-initialized
	ExtraUtilities{1.2.1} [Extra Utilities] (extrautilities-1.2.1.jar) Unloaded->Constructed->Pre-initialized
	FastCraft{1.16} [FastCraft] (fastcraft-1.16.jar) Unloaded->Constructed->Pre-initialized
	GalacticraftCore{3.0.7} [Galacticraft Core] (GalacticraftCore-1.7-3.0.7.254.jar) Unloaded->Constructed->Pre-initialized
	GalacticraftMars{3.0.7} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.7.254.jar) Unloaded->Constructed->Pre-initialized
	ganysnether{1.7.7} [Gany's Nether] (Ganys Nether-1.7.7.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft{2.1.0a} [Growthcraft] (growthcraft-core-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar] (growthcraft-cellar-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Apples{2.1.0} [Growthcraft Apples] (growthcraft-apples-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo] (growthcraft-bamboo-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Bees{2.1.0} [Growthcraft Bees] (growthcraft-bees-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap] (growthcraft-fishtrap-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Grapes{2.1.0} [Growthcraft Grapes] (growthcraft-grapes-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Hops{2.1.0} [Growthcraft Hops] (growthcraft-hops-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Rice{2.1.0a} [Growthcraft Rice] (growthcraft-rice-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
	IronChest{6.0.49.733} [Iron Chest] (ironchest-1.7.10-6.0.49.733-universal.jar) Unloaded->Constructed->Pre-initialized
	monnef-core-helper{0.7.2} [monnef Core ~] (monnef_core_0.7.3.jar) Unloaded->Constructed->Pre-initialized
	Jaffas{0.7.3} [Jaffas and more!] (jaffas_0.7.3.jar) Unloaded->Constructed->Pre-initialized
	Jaffas-Trees{0.7.2} [Jaffas - Trees] (jaffas_0.7.3.jar) Unloaded->Constructed->Pre-initialized
	Jaffas-Technic{0.7.2} [Jaffas - Technic] (jaffas_0.7.3.jar) Unloaded->Constructed->Pre-initialized
	Jaffas-Power{0.7.2} [Jaffas - Power] (jaffas_0.7.3.jar) Unloaded->Constructed->Pre-initialized
	Jaffas-Xmas{0.7.2} [Jaffas - Xmas] (jaffas_0.7.3.jar) Unloaded->Constructed->Pre-initialized
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized
	Mystcraft{0.11.0.00} [Mystcraft] (mystcraft-1.7.10-0.11.0.00.jar) Unloaded->Constructed->Pre-initialized
	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6-snapshot-291.jar) Unloaded->Constructed->Pre-initialized
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3-snapshot-543.jar) Unloaded->Constructed->Pre-initialized
	Railcraft{9.4.0.0} [Railcraft] (Railcraft_1.7.10-9.4.0.0.jar) Unloaded->Constructed->Pre-initialized
	Roguelike{1.3.5} [Roguelike Dungeons] (roguelike-1.7.10-1.3.5.jar) Unloaded->Constructed->Pre-initialized
	superMassiveTech{0.2.0-alpha} [Super Massive Tech] (SuperMassiveTech-MC1.7.10-0.2.0-alpha-85.jar) Unloaded->Constructed->Pre-initialized
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2a.jar) Unloaded->Constructed->Pre-initialized
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-162.jar) Unloaded->Constructed->Pre-initialized
	erebus{0.2pre11c} [Erebus] (TheErebus-0.2pre11c.jar) Unloaded->Constructed->Pre-initialized
	kitchen{1.3.7} [The Kitchen Mod] (TheKitchenMod-1.3.7-1.7.2-10.jar) Unloaded->Constructed->Pre-initialized
	TMechworks{1.7.10-86.e500b88} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.10.jar) Unloaded->Constructed->Pre-initialized
	Translocator{1.1.1.14} [Translocator] (Translocator-1.7.10-1.1.1.14-universal.jar) Unloaded->Constructed->Pre-initialized
	TwilightForest{2.3.2} [The Twilight Forest] (twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized
	VillagersNose{1.3a} [Villager's Nose] (VillagersNose-1.7.10-1.3c.jar) Unloaded->Constructed->Pre-initialized
	witchery{0.22.0} [Witchery] (witchery-1.7.10-0.22.0.jar) Unloaded->Constructed->Pre-initialized
	OpenModsLib crash transformers: [gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED],[map_gen_fix:FINISHED],[movement_callback:FINISHED],[stencil_patches:FINISHED]
	AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Stencil buffer state: Function set: ARB, pool: internal, bits: 8

**Comment by skyboy** [comment] 2015-01-29 08:07
@simon-itch You're using a developer (dev) jar.

@MikeArclight Since no one seems to be able to reproduce your issue, I'm going to close this; you can try re-downloading versions (from http://www.curse.com).

**Closed by skyboy** 2015-01-29 08:07 UTC

**Comment by MikeArclight** [comment] 2015-01-29 17:31
Wow, I honestly did not expect you to respond so fast; so I feel that it is I who must apologize for not being attentive enough/

@skyboy  I know you closed this thread, which is fine. My build is a house of cards held together with spit and frustration. To be honest, I am glad that it is just me and not something inherent to the mod; it means that at some point I'll unscrew my Minecraft and be able to enjoy it. Thank you for your prompt attention and help - Keep up the good work and thank you.
