### ISSUE TITLE
phytogenetic Insolator configuring sides with AE attatched to side crashes server.

### ISSUE THREAD

**Issue by Virezz** [CoFH/Feedback#535] opened 2015-05-19 01:35 UTC
Hi,
I got a server crash when toggling the configurations of a phytogenetic Insolator
http://pastebin.com/RQWXrP50

Crashed when i have a config like this:
https://imgur.com/a/FwMcT
and changed the export bus side in the configuration "tab" in the interface.

**Comment by KingLemming** [comment] 2015-05-19 03:59
Duplicate of #475.

**Closed by KingLemming** 2015-05-19 03:59 UTC
