### ISSUE TITLE
Thermal Dynamics redstone relay 1.12.2-2.3.10.4

### ISSUE THREAD

**Issue by alphanerd132** [CoFH/Feedback#997] opened 2018-03-27 16:15 UTC
Thermal dynamics redstone relay does not update on the input side. if the inventory changes with compairator mode, it doesn't update the input automatically. You have to manually update it with ether a block update or looking at the UI.

**Comment by KingLemming** [comment] 2018-03-27 18:11
Duplicate of #840.

**Closed by KingLemming** 2018-03-27 18:11 UTC
