### ISSUE TITLE
Portable tank upgrade duping

### ISSUE THREAD

**Issue by thenextelement** [CoFH/Feedback#741] opened 2017-12-18 16:49 UTC
this is happening on the latest version of thermal expansion
https://imgur.com/a/erT0J

**Comment by ImbaKnugel** [comment] 2017-12-18 21:40
Duplicate of #709. Seems to already be fixed.

**Comment by KingLemming** [comment] 2017-12-18 21:42
In Dev, yes. I'm on vacation but will see about an update.

**Closed by KingLemming** 2017-12-18 21:42 UTC

**Comment by thenextelement** [comment] 2017-12-20 22:32
i only scrolled through a few issues, i kind of figured this was noticed.
