### ISSUE TITLE
Cache / Machinist's Workbench item duplication bug

### ISSUE THREAD

**Issue by dallenwilson** [CoFH/Feedback#1241] opened 2016-08-20 07:09 UTC
Mod Versions:
- CoFHCore-[1.7.10]3.1.3-327
- ThermalFoundation-[1.7.10]1.2.5-115
- ThermalExpansion-[1.7.10]4.1.4-247

Steps to reproduce:
- Craft basic cache and fill with target item in target quantity.
- Craft second basic cache, fill with anything, amount irrelevant.
- Place first cache in Machinist's Workbench, with enough Invar Ingots to upgrade two caches to Hardened. Draw the recipe and pick up the upgraded cache from the result box.
- Without clearing the recipe, place second cache in workbench inventory, and immediately pick up the cache in the result box.

Result: Second cache, after being upgraded to hardened, is now a duplicate of the first hardened cache, with the same type and quantity of item in it.

First noticed on a SMP server, then verified in creative single-player.

**Comment by NaveNO** [comment] 2016-08-20 09:13
Wow, reproduced that method on a server-it worked! Thank you for finding a bug. Our server owner is notified to block Caches.

**Comment by skyboy** [comment] 2016-08-21 02:51
Duplicate of https://github.com/CoFH/Feedback/issues/1233

**Closed by skyboy** 2016-08-21 02:51 UTC
