### ISSUE TITLE
Random.nextInt with non-positive bound.

### ISSUE THREAD

**Issue by Jomik** [CoFH/Feedback#652] opened 2017-11-25 18:57 UTC
WorldGenSpike is causing an IllegalArgumentException.

All information you need should be here.

[crash-2017-11-25_19.52.00-server.txt](https://github.com/CoFH/Feedback/files/1503313/crash-2017-11-25_19.52.00-server.txt)
[01_cavegen.json](https://github.com/CoFH/Feedback/files/1503314/01_cavegen.txt)
Renamed to txt to be able to upload.

**Comment by KingLemming** [comment] 2017-11-25 19:04
Duplicate of #594. This is a configuration error on your end. Yes, we can (and are) improving it.

**Closed by KingLemming** 2017-11-25 19:04 UTC
