### ISSUE TITLE
cofhWorld [1.12] Biome blacklist gets ignored

### ISSUE THREAD

**Issue by ulkunderscore** [CoFH/Feedback#378] opened 2017-07-14 22:18 UTC
[pastebin](https://pastebin.com/WDSgG6zh)
The "dry" tag gets ignored, the clay still spawns in savanna biomes.

cofhWorld 1.0.0.6 and Forge 14.21.1.2412
With only JEI and World Stripper.

**Comment by KingLemming** [comment] 2017-07-14 22:59
Working as intended. Savanna biomes aren't marked as "dry."

Take it up with Forge. That's their designation.

**Closed by KingLemming** 2017-07-14 22:59 UTC
