### ISSUE TITLE
Steel with 4 iron & 1 pulverized coal

### ISSUE THREAD

**Issue by alexroeber** [CoFH/Feedback#683] opened 2017-12-03 18:29 UTC
Yeah, title says it all, put a stack coal in first, 32 iron second, got steel all the same but only 8 and instead of using the second stack pulverized coal, the iron was empty and I still had 56 coal...
Thermal Foundation 2.3.7.18

**Comment by bookerthegeek** [comment] 2017-12-03 18:35
- Was this in a mod pack?
- what other mods are installed.

**Comment by KingLemming** [comment] 2017-12-03 18:52
Duplicate of #669. Please be sure you're on the latest mods.

**Closed by KingLemming** 2017-12-03 18:52 UTC
