### ISSUE TITLE
Updated today, something has happened that kills old worlds. Have No idea what.

### ISSUE THREAD

**Issue by Stargazeer** [CoFH/Feedback#155] opened 2015-02-22 20:11 UTC
Updated to the release versions of each cofh mod today, and all my other mods that are causing the launch crashes in other issues. I have looked all over for a solution to no avail, this is most certainly not a common error.
Before updating the mods my worlds "worked" fine (modded worlds tend to have instabilities anyway) However when i try opening a save created before updating it throws a message at me saying that it is using the backup level.dat file. When i accept to continue it loads the world but it swaps modded blocks out for other modded blocks, ruining the world.
I am posting here cause, A) It happened when i updated the cofh mods and B) Other than it complaining that ive updated some mods from the last time the world was saved i get this as a warning in the console. 
[19:53:08] [Server thread/WARN] [FML]: * The object cofh.core.item.tool.ItemShovelAdv@26be8835 has been registered twice for the same name ThermalFoundation:tool.shovelInvar.
[19:53:08] [Server thread/WARN] [FML]: *  at cpw.mods.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:357)
[19:53:08] [Server thread/WARN] [FML]: *  at cpw.mods.fml.common.registry.GameData.registerItem(GameData.java:838)
[19:53:08] [Server thread/WARN] [FML]: *  at cpw.mods.fml.common.registry.GameData.processIdRematches(GameData.java:623)
[19:53:08] [Server thread/WARN] [FML]: *  at cpw.mods.fml.common.Loader.fireMissingMappingEvent(Loader.java:929)
[19:53:08] [Server thread/WARN] [FML]: *  at cpw.mods.fml.common.registry.GameData.injectWorldIDMap(GameData.java:537)
[19:53:08] [Server thread/WARN] [FML]: *  at cpw.mods.fml.common.FMLContainer.readData(FMLContainer.java:275)...
Coupled with the console saying it cant find the invar stuff. No idea whether this error is causing the crash but it cant be a coincidence that it happens just after i update.
Cant find anywhere else to post issues with the mods so i am posting here. I have been working at trying to fix this, including updating all mods that use RF and are in any way related and trying some of the more recent alpha releases, and nothing is working.
Thanks for any assistance.

**Comment by KingLemming** [comment] 2015-02-22 20:13
Sounds like you were using alpha versions - the ones we were pretty adamant about people not using. ;)

Downgrade TE and TE to their December releases, launch the server, and THEN update.

**Comment by KingLemming** [comment] 2015-02-22 22:13
Closing this now as it's basically a duplicate of #150

**Closed by KingLemming** 2015-02-22 22:13 UTC
