### ISSUE TITLE
Server Crashing upon unloading area

### ISSUE THREAD

**Issue by PlanetBeast** [CoFH/Feedback#378] opened 2015-03-31 18:19 UTC
Hello there. I'm having an issue with either EnderIO or Thermal Expansion. I'm going to post an issue with EnderIO as well as here but anyways I'm getting a server crash whenever I am unloading my base whether its through a /tp /home or whatever. I checked the crash report on the server and it seems its an issue with EnderIO and TE interacting. I'm not quite sure but I'd appreciate some help on whats going on :)
http://pastebin.com/9ZM9maFp

**Comment by KingLemming** [comment] 2015-03-31 20:03
Duplicate of #347. But thanks for pointing out when it happens. Now I'm *very* confident this is EnderIO's fault.

**Closed by KingLemming** 2015-03-31 20:03 UTC
Labels: duplicate

**Comment by PlanetBeast** [comment] 2015-03-31 21:02
Okay thanks for the confirmation!
