### ISSUE TITLE
[1.12.2] Crash with latest TE

### ISSUE THREAD

**Issue by JonasCiss** [CoFH/Feedback#799] opened 2018-01-02 18:06 UTC
I installed the latest version recently and now the sever is unable to start. 
[crash-2018-01-02_19.02.05-server.txt](https://github.com/CoFH/Feedback/files/1598283/crash-2018-01-02_19.02.05-server.txt)
[crash-2018-01-02_19.00.26-server.txt](https://github.com/CoFH/Feedback/files/1598284/crash-2018-01-02_19.00.26-server.txt)
[crash-2018-01-02_19.04.56-server.txt](https://github.com/CoFH/Feedback/files/1598285/crash-2018-01-02_19.04.56-server.txt)
[crash-2018-01-02_18.58.49-server.txt](https://github.com/CoFH/Feedback/files/1598286/crash-2018-01-02_18.58.49-server.txt)

**Comment by KingLemming** [comment] 2018-01-02 18:10
Duplicate of #795.

**Closed by KingLemming** 2018-01-02 18:10 UTC
