### ISSUE TITLE
[Thermal Foundation] Forge Lexicon does not correctly save preferences between play sessions.

### ISSUE THREAD

**Issue by MysteriousAges** [CoFH/Feedback#795] opened 2015-08-23 23:47 UTC
Playing with a pack that contains several types of the same ingot (Tin, for example), and having set my preference to Thermal Foundation's (because let's be honest, it does look pretty good compared to the others), when I exit the game and rejoin the server, my preference seems to be reset to the first instance of tin found in the ore dictionary and unifies to that.

**Comment by KingLemming** [comment] 2015-09-02 17:15
Hrm. Odd. But will take a look. :)

**Comment by KingLemming** [comment] 2015-09-11 22:36
Hrm...I'm not able to replicate this.

What I *have* noticed is that the Lexicon doesn't open to your "preferred" ore for a given entry. And that's something I think I can fix. :)

You sure that the unification is incorrect, and not just the shown entry?

**Comment by MysteriousAges** [comment] 2015-09-12 02:43
Hm. I'll have to check again, but that does sound a lot like what might have been happening. I'll get back to you.

**Comment by MysteriousAges** [comment] 2015-09-12 05:32
Yeah, it unifies to the ingot it opens to. This is with the Forgecraft 2 configs, BTW.

**Comment by KingLemming** [comment] 2015-09-12 08:42
Hrm....that doesn't happen for me :/

**Comment by MysteriousAges** [comment] 2015-09-12 19:35
Seems like the reset occurs if the server restarts. Login/logout keeps the correct preference saved.

**Comment by masoniks** [comment] 2015-10-05 16:00
I can confirm this issue.  Where are the forge lexicon preferences saved?  I had a look through the configs and world directory but couldn't find anything other than the lexicon whitelist

**Comment by KingLemming** [comment] 2015-10-14 18:57
Lexicon preferences are saved per player. And we still can't replicate this. If it only happens when the server *crashes*, welp.

**Comment by masoniks** [comment] 2015-10-15 14:03
This isn't relating to a crash.  I run through the Lexicon setting the preferences then empower the Lexicon.  It then works exactly as expected/intended (actually better than expected) in converting all ores, ingot, blocks etc into the prefered item.  After a clean restart of the server (SSP) the preferences are removed and revert back to the first entry.  I would say that it is not a significant issue as items are still converted thus having only a cosmetic or OCD trolling effect.  

One resolution could be to have a config file to configure this?

**Comment by KingLemming** [comment] 2015-10-16 15:24
The preferences aren't removed, though. It's simply that the Lexicon doesn't open to the item that you have it set to.

There's not an easy fix for this, unfortunately. The Lexicon has to open to the beginning of the list since it's possible that the mod adding the item may have been removed.

**Comment by da3dsoul** [comment] 2015-11-06 11:39
It's plenty easy. Upon opening the gui, use a try catch on opening to the desired entry, then if it catches, set it to the first entry.

**Comment by KingLemming** [comment] 2015-11-10 01:48
Try/catch is an absolute kludge there.

**Comment by KingLemming** [comment] 2015-11-10 02:26
This is now fixed in dev to my satisfaction. If mods are removed in the course of play, I'm not promising anything. People shouldn't be dumb. :)

**Comment by da3dsoul** [comment] 2015-11-10 06:19
Fair enough. Thanks!

**Closed** 2016-01-25 23:52 UTC
Labels: fixed, fixed in dev, TE
