### ISSUE TITLE
[MFR][Mod compatibility] Harvester and planter not compatible with Pam's Harvestcraft

### ISSUE THREAD

**Issue by Cobra1117** [CoFH/Feedback#39] opened 2015-01-22 01:46 UTC
Tested with:
Forge: 10.13.2.1277
MFR: 2.8.0RC6-5
Pam's Harvestcraft: 1.7.10f

Bug 1: The planter does not convert dirt and grass into farmland before planting seeds from Pam's Harvestcraft, despite the fact that these seeds can't normally be planted on dirt or grass.

Bug 2: The harvester breaks plants instead of harvesting them. Harvestcraft uses the "right click to harvest and leave the plant alive" mechanic. I'm pretty sure MFR used to support this, but it doesn't anymore. This is a problem because Harvestcraft doesn't return seeds normally (you have to craft them), so breaking the plant greatly complicates the automation process.

**Comment by Barhandar** [comment] 2015-01-23 12:35
Based on the glimpses of Thaumcraft IMC log output, the harvesting issue's on PamHC's end: it registers and IMCs its plants as "Standard" and not "Clickable" regardless of config settings.

For seeds, you can use Factorization's Stamper, or set cropsdropseeds in HC's config to "true".

P.S. How did you even manage to make it harvest Pam's crops? Every time I tried it failed to detect them.

**Comment by thornedcrystal** [comment] 2015-01-31 03:53
Tested with:
Forge:10.13.2.1277
MFR: 2.8.0RC2-577 and  2.8.0RC3-591 (  2.8.0RC6-5 crashes my minecraft upon for some reason but this isnt the issue here )
Magicalcrops: 1.7.10_05

Harvester isnt pulling Essence seeds form the Tesseract i've tried using pipes from a chest connected to the harvester.  Not exactly sure if this fixed in later versions or if this an ability that has been taken out.  I've tried seeing if there's a whitelist config file and couldn't find anything, let me know whats going on here.

**Comment by skyboy** [comment] 2015-02-13 00:04
HarvestCraft implements support on its side: not hoeing the ground is a bug (though largely appears to be aesthetic), though breaking the plant entirely appears to be intended behavior (and is in fact consistent with how MFR harvests other crops).

MagicalCrops previously implemented support, but that is now a separate mod itself.

**Closed by skyboy** 2015-02-13 00:04 UTC
