### ISSUE TITLE
[Crash] AgSkies 2 Thermal Dynamics v1.0.0 ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by allout58** [CoFH/Feedback#477] opened 2015-04-30 03:37 UTC
Just starting out my world, so the only thing I have is two opaque itemducts pushing into 2 crucibles from Ex Nihilo, pulling out from a chest with cobblestone and obsidian using a basic servo.
This crash did not happen again when I reloaded the world.

![Setup](https://cloud.githubusercontent.com/assets/2939703/7405945/5652a280-eec8-11e4-92e9-2c38ea998bb6.png)

Crashlog: https://gist.github.com/allout58/2b5ef2eac40b6978603c

Anything else you need from me just let me know!

**Comment by allout58** [comment] 2015-04-30 03:43
It seems to happen consistantly whenever the Igneous Extruder inserts obsidian into the chest.

**Comment by KingLemming** [comment] 2015-04-30 05:00
Duplicate of #470. I'm pretty sure this is actually on Ex Nihilo.

**Comment by allout58** [comment] 2015-04-30 05:19
Oops, sorry for the dupe!
It would make sense that it is Ex Nihilo, as it only happens when the extruder puts in obsidian. However, when I get the world back up, the obsidian is still in the chest and the game isn't crashing (SSP). I wonder why it doesn't crash them.

**Comment by KingLemming** [comment] 2015-04-30 05:28
My guess is that the Crucible has a dynamically sized inventory somehow, and it's getting it right on load but not initially.

And don't worry about the dupe, the picture here helps loads.

**Comment by Erasmus-Crowley** [comment] 2015-04-30 20:30
In your SimulatedInv class, you are assuming that that the slot ID and the array index are going to be the same. In the case of crucibles, they are not. 

You are calling Crucible.getSizeInventory and I'm returning 1.
You are then initializing an array of ItemStack with a size of 1. This is correct, because the crucible only has one visible slot, but the actual item for slot 1 is at index 0 in your array.
Later, you are calling SimulatedInv.getStackInSlot and correctly passing in 1, because the slot ID is 1, but you are looking for your ItemStack index 1 instead of realizing that slot 1 is located at index 0. The index 1 is out of bounds.

Aren't inventory slot numbers arbitrary? No one has ever required them to start at 0 before.

**Comment by KingLemming** [comment] 2015-05-01 03:25
Seems like Ex Nihilo is on the case.

**Closed by KingLemming** 2015-05-01 03:25 UTC
Labels: duplicate
