### ISSUE TITLE
CoFH tweaks 0.2.0B1-31 loading issue

### ISSUE THREAD

**Issue by C0mpuviru5** [CoFH/Feedback#574] opened 2015-06-02 03:19 UTC
Using referenced cofh tweaks version results in forge freezing at initialization-cofh tweak asm and will refuse to load any further

**Comment by KingLemming** [comment] 2015-06-02 05:04
So. Log?

**Comment by C0mpuviru5** [comment] 2015-06-02 05:13
the only log ive got is my fml latest, how can i get that to you as the log itself is too long to paste?

**Comment by C0mpuviru5** [comment] 2015-06-02 05:26
https://drive.google.com/file/d/0B-3vqJ_4tb5caW1Sb3ZKaEtiV3c/view?usp=sharing

That may work, if so you can see at the bottom of the log it stops there, normally a 10 minute load on version 30 of cofh tweaks, but on 31 it wont load at all, ive left it overnight to see it stuck in the same spot

**Comment by Serifina** [comment] 2015-06-03 00:27
Just want to point out it does the precise same thing with mine, and a very different mod setup. Log can be found here:

https://drive.google.com/file/d/0B57Rjw7BNxWda2FUM01JTlBDb2M/view?usp=sharing

Basically, it sits there trying to initialize Tweaks and... nothing ever happens. I've let it sit for a couple of hours, and no reaction.

**Comment by wujekbrezniew** [comment] 2015-06-03 19:33
I have the same problem.
Loading stops on [Client thread/INFO]: Created: 2048x2048 textures/items-atlas

**Comment by C0mpuviru5** [comment] 2015-06-03 19:49
@wujekbrezniew what graphics card do you have and how much ram are you allocating to minecraft?

**Comment by wujekbrezniew** [comment] 2015-06-03 20:26
GTX 650ti Boost from MSI
I allocate 3GB for game and 512mb for permgen.
Earlier version of CoFH Tweaks([1.7.10]0.1.0B2) works fine.

**Comment by C0mpuviru5** [comment] 2015-06-03 20:29
Interesting, mine use to freeze at the same thing as yours, either I didn't have enough ram or my graphics drivers were outta date

**Comment by sandalle** [comment] 2015-06-04 16:59
See #568 for more logs and this appears to be a duplicate of that (closed) issue.

**Comment by skyboy** [comment] 2015-06-04 22:11
This is caused by fundamental design flaws in GregTech.

**Comment by C0mpuviru5** [comment] 2015-06-04 22:12
I don't have Gregtech, or ic2 for that matter

**Comment by sandalle** [comment] 2015-06-04 22:15
We have no Greg Tech/IC2 either and we're seeing this same issue as posted in #568 .

**Comment by skyboy** [comment] 2015-06-04 22:22
You're going to need to include logs then.

**Comment by C0mpuviru5** [comment] 2015-06-04 22:25
https://drive.google.com/file/d/0B-3vqJ_4tb5caW1Sb3ZKaEtiV3c/view?usp=sharing

**Comment by skyboy** [comment] 2015-06-04 22:29
Okay, what looked like gregtech was other mods depending on it. When it freezes generate a crash report with ctrl+break

**Comment by C0mpuviru5** [comment] 2015-06-04 22:43
i have tried several times now to generate a crash report with ctrl+break to no avail, it just throws minecraft into a not responding window

**Comment by skyboy** [comment] 2015-06-04 22:52
Does it add any additional info to the log? Also: a build will come up in an hour or so that'll log errors that may cause it

**Comment by C0mpuviru5** [comment] 2015-06-04 22:55
it just stops in the same spot as the log that i posted, no new info and no direction as to whats causing the freeze

**Comment by C0mpuviru5** [comment] 2015-06-04 22:55
this is where it stops in every log that i have

[16:39:56] [Client thread/TRACE] [<CoFH Tweak>/<CoFH Tweak>]: Sending event FMLInitializationEvent to mod <CoFH Tweak>

**Comment by C0mpuviru5** [comment] 2015-06-05 00:06
am trying the new build, as far as i can tell its the same issue, frozen on the loading screen at thee same spot, where would i look for it to be logging errors?

**Comment by sandalle** [comment] 2015-06-05 00:31
[CoFHTweaks-[1.7.10]0.2.0B2-32](http://minecraft.curseforge.com/mc-mods/230020-cofhtweaks/files/2241393)'s [fml-client-latest.log](https://www.dropbox.com/s/wk1sd14l5ei47ob/CoFHTweaks-%5B1.7.10%5D0.2.0B2-32-fml-client-latest.7z?dl=0) is available, but I still couldn't generate an actual crash-report, sorry.

**Comment by mechaet** [comment] 2015-06-05 01:46
https://onedrive.live.com/redir?resid=E961F5CD3E23E011!34030&authkey=!AGFIxudEKnYPvWg&ithint=file%2clog

Here's mine, on a different machine, doing the same thing.

**Comment by mechaet** [comment] 2015-06-05 01:48
If you'd like to test it yourself, here's the modpack: http://www.technicpack.net/modpack/modderation-permabanned-edition.449941

Download the Recommended build, then add CoFHTweaks to the mods directory.

**Comment by KingLemming** [comment] 2015-06-05 01:55
Yeah, problem is that it only happens if you play it on a starch-based platform. We can't replicate it on our machines, so debugging is extremely difficult.

**Comment by C0mpuviru5** [comment] 2015-06-05 01:58
Starch based?

**Comment by CannibalVox** [comment] 2015-06-05 04:00
The joke was that you're playing on a potato, but so is skyboy, so ???

**Comment by mechaet** [comment] 2015-06-05 07:11
Because a Haswell i5, 16GB RAM, SSD RAID, and GTX980 is totally slumming it.

**Comment by KingLemming** [comment] 2015-06-05 08:42
@mechaet If that's the case, then do you get the same result with Tweaks *alone*?

Basically, is this a hardware/OS thing or is this an x-mod issue?

**Comment by solomon56** [comment] 2015-06-05 10:03
seems to be hardware/OS related not x-mod. log with tweaks only here: [http://hastebin.com/vasevinobo.dos](http://hastebin.com/vasevinobo.dos). My hardware is: i7 2600k 16GB RAM, GTX 550ti

**Comment by MacGyversMullet** [comment] 2015-06-05 12:53
Tested with just Forge and COFH Tweaks and got the same error as the others here. Minecraft would not generate a crash report with ctrl+break when it froze.
http://hastebin.com/bubirococo.tex

My system is: Windows 7 x64, i5-4960k, 8 GB of ram, Nvidia GTX 970

**Comment by sandalle** [comment] 2015-06-05 18:00
In case it mattered as I see most are using Java 8, I downgraded my JRE from 8u45 to 7u80 and same error in [fml-client-latest.log](https://www.dropbox.com/s/20z5lxnukwwdbbj/CoFHTweaks-%5B1.7.10%5D0.2.0B2-32-jre-7u80-fml-client-latest.7z?dl=0), for reference.

**Comment by wujekbrezniew** [comment] 2015-06-07 13:48
I try newest version of CoFHTweaks - 0.2.0B2-32.jar and I still have the same problem.

**Comment by WJ44** [comment] 2015-06-07 14:52
I saw everyone here is using Intel/Nvidea. I have an AMD FX-8350 and a Radeon Hd 7950 and I have the same issue.

**Comment by Serifina** [comment] 2015-06-07 15:27
I just tried with the new build. Can't make it crash, it just sits there. No other mods beyond Forge and CoFHTweaks. And it still hangs trying to initialize Tweaks.

http://pastebin.com/vRF7kmk6

System: Win7, i7-2720QM, 8 Gigs RAM (3 gig allocated to Minecraft), Nvidia GT-555m3gig. Not precisely what I'd call a potato, even if it's not the greatest.

**Comment by AdrianIonut** [comment] 2015-06-09 17:55
Same to me gets stuck http://pastebin.com/jehK4YKL

**Comment by sandalle** [comment] 2015-06-09 20:59
Also tested with [Forge 10.13.3.1428](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.3.1428-1.7.10/forge-1.7.10-10.13.3.1428-1.7.10-universal.jar) in case it's a Forge bug that's [since been fixed](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.3.1428-1.7.10/forge-1.7.10-10.13.3.1428-1.7.10-changelog.txt), but same stuck case as has been reported earlier.

**Comment by wujekbrezniew** [comment] 2015-06-23 16:10
Hi,
i tested a little bit the newest version of Fastcraft and it seems to be compatible to CoFH mods. Earlier I had problems with planter and harvester (for example in tree farm) and now this problem gone. The game is working properly and i dont see any issues. Can someone try it?
(I don't use CoFH tweaker at once but I install the BetterFps mod).

**Comment by Termin8or** [comment] 2015-06-24 18:45
With CofhTweaks 0.20B2-32 it freezes on mod init 2. And the loading screen goes to not responding.

**Comment by DrasticDemise** [comment] 2015-06-29 23:45
I also cannot load 0.20B2-32 as it get stuck on init 2 on forge 1448, this is with BetterFPS and Fastcraft removed. I couldn't get anything from the log nor a force crash with CTRL + Break, so I am not sure how useful this is. Sorry!

**Comment by adudney** [comment] 2015-07-09 20:57
Versions:
Minecraft 1.7.10
MultiMC 5 0.4.7
Mac OSX 10.10.4
Java 8u45
Forge 10.13.4.1448
CoFHTweaks 0.2.0B2-32

Loads until this screen:
![screen shot 2015-07-09 at 13 49 12](https://cloud.githubusercontent.com/assets/246232/8606578/719de17a-2641-11e5-88c1-7a8cc34dc6ab.png)
Then hangs.
As Macs do not have a break key (https://en.wikipedia.org/wiki/Break_key) I was unable to force a crash (If there's a way to rebind that let me know and I'll test again.)
Logs: https://gist.github.com/adudney/110b7a6365993f2014ab

Note that CoFHTweaks 0.1.0B2-30 loads just fine, while CoFHTweaks 0.2.0B1-31 and above hang. This implies that something in this commit broke it: https://github.com/CoFH/CoFHTweaks/commit/39b81c3695f825ad7995a288404ca38284b90dde But nothing in it looks suspicious at first glance. (Although I didn't spend too long looking at it, and I'm not familiar with the code at all.)

This may very well be a Mac only error, which would be why you can't reproduce it (Do you have a linux machine perhaps? I'm not sure if it'll do the same thing on linux, but it's worth a shot.)

**Comment by Termin8or** [comment] 2015-07-09 21:23
I have the same issue on both windows 7 and windows 10 preview, so it's not an OS specific issue

**Comment by LuxusDarkangel** [comment] 2015-07-10 01:55
I'm having the same issue, but I thought it was a nice idea to profile it while its stuck to know what it's doing (using VisualVM) and this is the result: http://oi58.tinypic.com/20t2e6d.jpg

Also here you have the .nps file so you can see it by yourself: https://mega.co.nz/#!4YNXXCyS!q1_yBFbZVa6fl6L3fZn1JwUYrKymNxwHIZsAs2dUJkk

Hope it helps.

**Comment by skyboy** [comment] 2015-07-10 22:01
This is now be fixed. Apparently my IDE hadn't fully recompiled the file causing this.

**Closed by skyboy** 2015-07-10 22:01 UTC
