### ISSUE TITLE
[ThermalExpansion]Crash

### ISSUE THREAD

**Issue by a810587921** [CoFH/Feedback#466] opened 2015-04-26 07:54 UTC
java.lang.NullPointerException: Ticking block entity
	at cofh.thermalexpansion.block.cache.TileCache.func_70298_a(TileCache.java:298)
	at net.minecraft.tileentity.TileEntityHopper.func_145892_a(TileEntityHopper.java:530)
	at net.minecraft.tileentity.TileEntityHopper.func_145891_a(TileEntityHopper.java:490)
	at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:251)
	at net.minecraft.tileentity.TileEntityHopper.func_145845_h(TileEntityHopper.java:231)
	at net.minecraft.world.World.func_72939_s(World.java:2491)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Unknown Source)

ThermalExpansion Version: 4.0.1-182

**Comment by KingLemming** [comment] 2015-04-26 16:38
Duplicate of your own issue #443.

Please don't do that.

**Closed by KingLemming** 2015-04-26 16:38 UTC
