### ISSUE TITLE
Error stopping Minecraft from running

### ISSUE THREAD

**Issue by hotluck** [CoFH/Feedback#1070] opened 2018-05-02 21:10 UTC
Not sure if this is the same (or similar) to SnowyCicken's error but after updating my mods (and Forge) tonight, I get the following error (I did trying pasting it online but the link wouldn't work so sorry for pasting the whole error here) -

---- Minecraft Crash Report ----

WARNING: coremods are present:
IELoadingPlugin (ImmersiveEngineering-core-0.12-81.jar)
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
ForgelinPlugin (Forgelin-1.5.1.jar)
BCModPlugin (backpacks+1.12.2+-+3.5.0.jar)
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
BetterFontsCore (TTFR-1.12.1-1.9.1.jar)
IELoadingPlugin (ImmersiveEngineering-0.12-79-core.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 5/2/18 9:42 PM
Description: Initializing game

java.lang.NoSuchMethodError: cofh.api.util.ThermalExpansionHelper.addCompactorStorageRecipe(ILnet/minecraft/item/ItemStack;Lnet/minecraft/item/ItemStack;)V
at com.mcmoddev.lib.integration.plugins.ThermalExpansionBase.addCompactorStorageRecipe(ThermalExpansionBase.java:54)
at com.mcmoddev.lib.integration.plugins.ThermalExpansionBase.addPressStorage(ThermalExpansionBase.java:209)
at com.mcmoddev.lib.integration.plugins.ThermalExpansionBase.addPressStorage(ThermalExpansionBase.java:193)
at com.mcmoddev.basemetals.integration.plugins.ThermalExpansion.lambda$regShit$1(ThermalExpansion.java:51)
at com.mcmoddev.basemetals.integration.plugins.ThermalExpansion$$Lambda$725/1819895919.accept(Unknown Source)
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
at com.mcmoddev.basemetals.integration.plugins.ThermalExpansion.regShit(ThermalExpansion.java:47)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_247_ThermalExpansion_regShit_Register.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:746)
at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:622)
at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
at com.mcmoddev.lib.integration.plugins.ThermalExpansionBase.addCompactorStorageRecipe(ThermalExpansionBase.java:54)
at com.mcmoddev.lib.integration.plugins.ThermalExpansionBase.addPressStorage(ThermalExpansionBase.java:209)
at com.mcmoddev.lib.integration.plugins.ThermalExpansionBase.addPressStorage(ThermalExpansionBase.java:193)
at com.mcmoddev.basemetals.integration.plugins.ThermalExpansion.lambda$regShit$1(ThermalExpansion.java:51)
at com.mcmoddev.basemetals.integration.plugins.ThermalExpansion$$Lambda$725/1819895919.accept(Unknown Source)
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
at com.mcmoddev.basemetals.integration.plugins.ThermalExpansion.regShit(ThermalExpansion.java:47)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_247_ThermalExpansion_regShit_Register.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:746)
at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:622)
at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)

-- Initialization --
Details:
Stacktrace:
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
Minecraft Version: 1.12.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 3564680792 bytes (3399 MB) / 6415646720 bytes (6118 MB) up to 6415646720 bytes (6118 MB)
JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -Xms6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP 9.42 Powered by Forge 14.23.3.2677 Optifine OptiFine_1.12.2_HD_U_D2 80 mods loaded, 80 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

| State | ID | Version | Source | Signature |
|:----- |:-------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
| UCH | minecraft | 1.12.2 | minecraft.jar | None |
| UCH | mcp | 9.42 | minecraft.jar | None |
| UCH | FML | 8.0.99.99 | forge-1.12.2-14.23.3.2677.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCH | forge | 14.23.3.2677 | forge-1.12.2-14.23.3.2677.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCH | betterfonts | 1.9.1 | minecraft.jar | None |
| UCH | actuallyadditions | 1.12.2-r133 | ActuallyAdditions-1.12.2-r133.jar | None |
| UCH | architecturecraft | @VERSION@ | architecturecraft-1.12-2.68.jar | None |
| UCH | examplemod | 1.0 | autocrafter-4.0.jar | None |
| UCH | autocrafter | 4.0 | autocrafter-4.0.jar | None |
| UCH | backpacks16840 | 3.5.0 | backpacks+1.12.2+-+3.5.0.jar | None |
| UCH | ic2 | 2.8.75-ex112 | industrialcraft-2-2.8.75-ex112.jar | de041f9f6187debbc77034a344134053277aa3b0 |
| UCH | basemetals | 2.5.0-beta5 | BaseMetals-1.12-2.5.0-beta5.214.jar | d476d1b22b218a10d845928d1665d45fce301b27 |
| UCH | bedbugs | @VERSION@ | BedBugs-1.12-1.0.1.jar | None |
| UCH | bibliocraft | 2.4.3 | BiblioCraft[v2.4.3][MC1.12.0].jar | None |
| UCH | biomesoplenty | 7.0.1.2384 | BiomesOPlenty-1.12.2-7.0.1.2384-universal.jar | None |
| UCH | kjlib | 1.0.0 | kjlib-1.0.jar | None |
| UCH | caveroot | 1.0.2 | caveroot-1.0.4.jar | None |
| UCH | chameleon | 1.12-4.1.3 | Chameleon-1.12-4.1.3.jar | None |
| UCH | chickens | 6.0.4 | chickens-6.0.4.jar | None |
| UCH | chiselsandbits | 14.16 | chiselsandbits-14.16.jar | None |
| UCH | codechickenlib | 3.1.7.340 | CodeChickenLib-1.12.2-3.1.7.340-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
| UCH | redstoneflux | 2.0.1 | RedstoneFlux-1.12-2.0.1.2-universal.jar | d4f1503fbacd9b9fb767720420c5395104239ec9 |
| UCH | cofhcore | 4.4.1 | CoFHCore-1.12.2-4.4.1.12-universal.jar | None |
| UCH | cofhworld | 1.1.1 | CoFHWorld-1.12.2-1.1.1.12-universal.jar | None |
| UCH | coralreef | 2.0 | CoralReef-2.1-1.12.2.jar | None |
| UCH | corpsecomplex | 1.0.2.1 | corpsecomplex-1.12.2-1.0.2.1.jar | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
| UCH | customspawner | 3.11.3 | CustomMobSpawner-3.11.3.jar | None |
| UCH | cxlibrary | 1.6.1 | cxlibrary-1.12.1-1.6.1.jar | None |
| UCH | ptrmodellib | 1.0.2 | PTRLib-1.0.2.jar | None |
| UCH | props | 2.6.0 | Decocraft-2.6.0_1.12.2.jar | None |
| UCH | mocreatures | 12.0.3 | DrZharks MoCreatures Mod-12.0.3.jar | None |
| UCH | ezstorage | 2.5.0 | ezstorage-2.5.0-[1.12.2].jar | None |
| UCH | flatcoloredblocks | mc1.12-6.6 | flatcoloredblocks-mc1.12-6.6.jar | None |
| UCH | forgelin | 1.5.1 | Forgelin-1.5.1.jar | None |
| UCH | cfm | 4.1.5 | furniture-4.1.5-1.12.2.jar | None |
| UCH | trashcansreborn | 1.1.0 | garbagebins-1.1.0.jar | None |
| UCH | glass_shards | 1.7 | glass_shards_mc1.12-1.7.jar | None |
| UCH | grapplemod | 1.12-v10 | Grappling-Hook-Mod-1.12.jar | None |
| UCH | hatchery | 2.1.2 | hatchery-1.12.2-2.1.2.jar | None |
| UCH | hud | 1.3.9 | hud-1.3.9-1.12.jar | None |
| UCH | waila | 1.8.24 | Hwyla-1.8.24-B39_1.12.jar | None |
| UCH | ironchest | 1.12.2-7.0.42.827 | ironchest-1.12.2-7.0.42.827.jar | None |
| UCH | jei | 4.9.1.168 | jei_1.12.2-4.9.1.168.jar | None |
| UCH | lucky | 7.5.0 | LuckyBlock-1.12.zip | None |
| UCH | malisiscore | 1.12.2-6.4.0 | malisiscore-1.12.2-6.4.0.jar | None |
| UCH | malisisdoors | 1.12.2-7.3.0 | malisisdoors-1.12.2-7.3.0.jar | None |
| UCH | mantle | 1.12-1.3.1.21 | Mantle-1.12-1.3.1.21.jar | None |
| UCH | minecolonies | 1.12.2-0.8.7582 | minecolonies-universal-1.12.2-0.8.7582.jar | None |
| UCH | thermalfoundation | 2.4.1 | ThermalFoundation-1.12.2-2.4.1.15-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
| UCH | immersiveengineering | 0.12-81 | ImmersiveEngineering-0.12-81.jar | 4cb49fcde3b43048c9889e0a3d083225da926334 |
| UCH | morechickens | 3.1.0 | morechickens-1.12.2-3.1.0.jar | None |
| UCH | shear | 1.1.2 | MoreShearables1.2.3-1.12.jar | None |
| UCH | shetiphiancore | 3.5.6 | shetiphiancore-1.12.0-3.5.6.jar | None |
| UCH | multibeds | 1.4.3 | multibeds-1.12.0-1.4.3.jar | None |
| UCH | natura | 1.12.2-4.3.2.49 | natura-1.12.2-4.3.2.49.jar | None |
| UCH | notenoughroofs | 0.8.0.0 | notenoughroofs-1.12.2-0.8.0.0.jar | None |
| UCH | thermalexpansion | 5.4.2 | ThermalExpansion-1.12.2-5.4.2.27-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
| UCH | omlib | 3.0.0-138 | omlib-1.12.2-3.0.0-138.jar | None |
| UCH | ompd | 3.0.0-35 | ompd-1.12.2-3.0.0-35.jar | None |
| UCH | openmodularturrets | 3.0.0-236 | openmodularturrets-1.12.2-3.0.0-236.jar | None |
| UCH | orespawn | 3.2.1 | OreSpawn-1.12-3.2.1.109.jar | d476d1b22b218a10d845928d1665d45fce301b27 |
| UCH | harvestcraft | 1.12.2r | Pam's+HarvestCraft+1.12.2r.jar | None |
| UCH | realtimeclock | 1.12.2-1.1 | RealTimeClock-1.12.2-1.1.jar | None |
| UCH | recycler | 1.4.9 | recycler-1.4.9-1.12.jar | None |
| UCH | ropebridge | 2.0.5 | ropebridge-1.12-2.0.7.jar | None |
| UCH | shadowmc | 3.8.0 | ShadowMC-1.12-3.8.0.jar | None |
| UCH | storageboats | 3.1 | StorageBoats-3.2.1.jar | None |
| UCH | tesla | 1.0.63 | Tesla-1.12.2-1.0.63.jar | d476d1b22b218a10d845928d1665d45fce301b27 |
| UCH | thermaldynamics | 2.4.1 | ThermalDynamics-1.12.2-2.4.1.10-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
| UCH | thutcore | 5.16.2 | thutcore-1.12.2-5.16.2.jar | None |
| UCH | thutcore_compat | 1.0 | thutcore-1.12.2-5.16.2.jar | None |
| UCH | thuttech | 6.0.14 | thuttech-1.12.2-6.0.14.jar | None |
| UCH | treechopper | 1.2.4 | TreeChopper-1.12.2-1.2.4.jar | None |
| UCH | twilightforest | 3.6.345 | twilightforest-1.12.2-3.6.345-universal.jar | None |
| UCH | vampirism | 1.4.0 | Vampirism-1.12.2-1.4.0.jar | None |
| UCH | teamlapen-lib | 1.4.0 | Vampirism-1.12.2-1.4.0.jar | None |
| UCH | vc | 5.6.0 | ViesCraft-1.12.2-5.6.0.jar | None |
| UCH | wawla | 2.5.253 | Wawla-1.12.2-2.5.253.jar | d476d1b22b218a10d845928d1665d45fce301b27 |
| UCH | xaerominimap | 1.15 | Xaeros_Minimap_1.15_Forge_1.12.jar | None |
| UCH | mercurius_updater | 1.0 | MercuriusUpdater-1.12.2.jar | None |

Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-81.jar)
blusunrize.immersiveengineering.common.asm.IEClassTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)

ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
shetiphian.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.5.1.jar)

BCModPlugin (backpacks+1.12.2+-+3.5.0.jar)
brad16840.core.ClassTransformer
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
cubex2.cxlibrary.CoreModTransformer
BetterFontsCore (TTFR-1.12.1-1.9.1.jar)
cubex2.ttfr.BFClassTransformer
IELoadingPlugin (ImmersiveEngineering-0.12-79-core.jar)
blusunrize.immersiveengineering.common.asm.IEClassTransformer
Pulsar/natura loaded Pulses: 
- NaturaCommons (Enabled/Forced)
- NaturaOverworld (Enabled/Not Forced)
- NaturaNether (Enabled/Not Forced)
- NaturaDecorative (Enabled/Not Forced)
- NaturaTools (Enabled/Not Forced)
- NaturaEntities (Enabled/Not Forced)
- NaturaOredict (Enabled/Forced)
- NaturaWorld (Enabled/Not Forced)

Launched Version: 1.12.2
LWJGL: 2.9.4
OpenGL: GeForce GT 730/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'
Type: Client (map_client.txt)
Resource Packs: ChromaHills-128x-1.12.zip, [1.11.2] R3D CRAFT 128x (v0.3.1).zip
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 2x Intel(R) Core(TM)2 Duo CPU E8400 @ 3.00GHz
OptiFine Version: OptiFine_1.12.2_HD_U_D2
OptiFine Build: 20180430-132249
Render Distance Chunks: 8
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 4.6.0 NVIDIA 388.13
OpenGlRenderer: GeForce GT 730/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 2

**Comment by KingLemming** [comment] 2018-05-02 22:05
Duplicate of #1053. Please disable integration in their config file. It is no longer necessary.

**Closed by KingLemming** 2018-05-02 22:05 UTC
