### ISSUE TITLE
Version 5.1.8.16 caused a "ModelBakery" nullpoint

### ISSUE THREAD

**Issue by piedpipr314** [CoFH/Feedback#349] opened 2017-07-06 03:21 UTC
This crash is only caused by upgraded to the new version, once rolled back, no longer has this nullpoint.  I tried to isolate it to just the COFH mods included and don't honestly know where to start.
https://pastebin.com/Ph9eWaft
I'm willing to take insert mods or remove as necessary and work with you guys on this.

Edit: Wrong crashlog, my mistake

**Comment by piedpipr314** [comment] 2017-07-06 03:42
This may be related to https://github.com/CoFH/Feedback/issues/302

**Comment by KingLemming** [comment] 2017-07-06 04:15
Yup, probably a duplicate of #302 and probably caused by MineFactoryReloaded.

**Closed by KingLemming** 2017-07-06 04:15 UTC
