### ISSUE TITLE
Crash Report [NullPointerException: Ticking block entity]

### ISSUE THREAD

**Issue by FirKys** [CoFH/Feedback#188] opened 2015-02-25 06:07 UTC
http://pastebin.com/Ux1UXgjh
version:
ThermalExpansion-[1.7.10]4.0.0RC2-129.jar
ThermalFoundation-[1.7.10]1.0.0RC3-56.jar
CoFHCore-[1.7.10]3.0.0RC2-195.jar

**Comment by MinecraftDevin** [comment] 2015-02-25 07:47
Other people have been having this issue in irc..wonderful.

**Comment by MinecraftDevin** [comment] 2015-02-25 07:51
Actually... This might be a cauldron issue..

**Comment by KingLemming** [comment] 2015-02-25 09:28
Duplicate of #183

**Closed** 2015-03-04 00:36 UTC
Labels: duplicate, fixed
