### ISSUE TITLE
Thermal Dynamics fluctuating itemduct crash

### ISSUE THREAD

**Issue by mayumi7** [CoFH/Feedback#230] opened 2015-03-02 14:28 UTC
The Fluxitemduct it connected to an energy cell, splits off to a standard itemduct to a chest, that seems to cause the crash.

Crash report:
http://pastebin.com/g8sdGCNb

**Comment by KingLemming** [comment] 2015-03-03 16:19
Duplicate of #172

**Closed** 2015-03-04 00:36 UTC
Labels: duplicate, fixed
