### ISSUE TITLE
client crash with numismatic dynamo

### ISSUE THREAD

**Issue by ktole1999** [CoFH/Feedback#121] opened 2017-03-23 01:51 UTC
trying to input to numismatic dynamo and it crashed

http://pastebin.com/HNfVaxbS

CoFHCore-1.10.2-4.1.0.155-universal
ThermalExpansion-1.10.2-5.0.3.86-universal
ThermalFoundation-1.10.2-2.0.3.77-universal
Forge 12.18.3.2202

**Comment by KingLemming** [comment] 2017-03-23 01:59
Duplicate of #103.

Trying to input what and how?

We absolutely cannot make this happen. We need details.

**Closed by KingLemming** 2017-03-23 01:59 UTC

**Comment by KingLemming** [comment] 2017-03-23 02:09
Ah, it's been fixed in the dev branch but not the master. That makes sense now. Wasn't even an intentional fix, funny that.

**Comment by ktole1999** [comment] 2017-03-23 02:13
Sorry for lack of details. Been a long day. Hope to see release soon. Thanks for all hard work.



Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by KingLemming** [comment] 2017-03-23 02:21
Yeah honestly I just reuploaded the fixed version to CF since almost nobody had downloaded 5.0.4 yet and this was sort of a corner case.
