### ISSUE TITLE
CofhCore errors before Pre-init and crashes the game

### ISSUE THREAD

**Issue by Borkmeir** [CoFH/Feedback#280] opened 2017-06-20 18:22 UTC
Windows 10 64 bit
intel whatever graphics
nVidia GTX 870M 6GB GDDR5 
Minecraft 1.11.2
Forge 13.20.0.2315
Current Vanilla Launcher

Java Versions:
64 bit:
1.8.0_25
1.8.0_60
1.8.0_131

Installed Mods:
        Code Chicken Lib 1.11.2-2.7.0.268-universal.jar
        CoFH Core 1.11.2-4.2.2.7-universal.jar
	Thermal Foundation 1.11.2-2.2.2.4-universal.jar
	Thermal Expansion 1.11.2-5.2.3.6-universal.jar
	Redstone Arsenal 1.11.2-2.2.2.4-universal.jar
	Thermal Dynamics 1.11.2-2.2.3.6-universal.jar

The game never launches as CoFH Core errors.  I thought it was a mod conflict so I made a new instance to check but nope.  So maybe it was java, so I tried disabling the bundled version, (1.8.0_25) and used the system install instead, (1.8.0_0, 1.8.0_131) and nope.  I would have switched forge versions but in my original test it crashed and said that build 2315 was required.  So I'm stumped.

[CoFH Test Crash.txt](https://github.com/CoFH/Feedback/files/1089226/CoFH.Test.Crash.txt)

**Comment by KingLemming** [comment] 2017-06-20 18:42
Duplicate of #48.

You have a bad Forge install.

**Closed by KingLemming** 2017-06-20 18:42 UTC
