### ISSUE TITLE
Rosin and Tar Conflict

### ISSUE THREAD

**Issue by Zeronic** [CoFH/Feedback#198] opened 2017-05-20 19:04 UTC
I'm trying to trace down an issue with Rosin and Tar not being able to be used as Furnace fuel in a Modpack I'm building. Last time I found Bookshelf it be causing the issue, but I'm slowly starting to wonder if it is a Foundation bug.

**Comment by Zeronic** [comment] 2017-05-20 20:29
[ForgeLog.txt](https://github.com/CoFH/Feedback/files/1016492/ForgeLog.txt)

**Comment by KingLemming** [comment] 2017-05-20 22:28
Duplicate of #191. It's like people don't check.

**Closed by KingLemming** 2017-05-20 22:28 UTC
