### ISSUE TITLE
[BUG]Hello,This is a Thermal Expansion bug title

### ISSUE THREAD

**Issue by CrysisDeathgun** [CoFH/Feedback#1297] opened 2017-02-05 08:53 UTC
A Chinese player here,
My Server found some interesting BUG : 
When Hungry Chest (Thaumcraft) has an Hungry Chest (Thaumcraft), the usual Chest will have a lot of Hungry Chest when using retriever and activating the other end with the Redstone signal.
When using Anvil to repair Power Until the durability until the Power will disappear
We sincerely hope you can fix this BUG

ThermalDynamics-1.7.10 1.2.0-171
ThermalFoundation-1.7.10 1.2.5-115
ThermalExpansion-1.7.10 4.1.4-247

Here is my contact information Email: 1005206880@qq.com
 
I hope you can write to me

**Comment by CrysisDeathgun** [comment] 2017-02-05 08:54
I hope you can write to me

**Comment by lLuckyLukel** [comment] 2017-02-07 10:58
@CrysisDeathgun buddy, i guess u r taling about an old known issue with retriever :)

**Comment by KingLemming** [comment] 2017-02-07 18:38
Duplicate of #1259

**Closed by KingLemming** 2017-02-07 18:38 UTC
