### ISSUE TITLE
Thermal Dynamics Itemducts and TE Machines

### ISSUE THREAD

**Issue by AnomalusCrafter** [CoFH/Feedback#298] opened 2015-03-13 22:39 UTC
Search-fu is weak, sorry if this has been addressed.

COFHCore-[1.7.10]3.0.0RC5-207
ThermalDynamics-[1.7.10]1.0.0RC5-94
ThermalExpansion-[1.7.10]4.0.0RC6-138

Issues with items backstuffing in ducts when pumping out of chests to certain TE machines, with a simple setup to explain

![thermal issue 1](https://cloud.githubusercontent.com/assets/11466369/6648139/9cb02fa4-c9ac-11e4-9102-16f3024bea3e.png)

Chest contains a stack each of Iron ore and Gold ore. Flipping the lever results in both being pulled out.
![thermal issue 2](https://cloud.githubusercontent.com/assets/11466369/6648154/c28db91c-c9ac-11e4-86cf-455310226cd8.png)

Causing one stack to enter the machine, while the other travels back and becomes stuffed
![thermal issue 3](https://cloud.githubusercontent.com/assets/11466369/6648163/e089fcb4-c9ac-11e4-8e3e-5aac81cc74c4.png)
![thermal issue 5](https://cloud.githubusercontent.com/assets/11466369/6648164/e58b6de2-c9ac-11e4-9664-547047b7c7b6.png)

Happens when multiple valid types of items are present in the chest. Does NOT stuff if it is multiple stacks of the same item though.

If the slot is already full, it will NOT try to send another type of item. So Warp Item ducts and SHORT lengths of Impulse Itemducts do not stuff, as the item arrives and fills the input slot before the next stack can be sent. If the length it too far, even Impulse Itemducts stuff

![thermal issue 4](https://cloud.githubusercontent.com/assets/11466369/6648218/9fa3e0ce-c9ad-11e4-8a19-bfffcc1c7b23.png)

![thermal issue 9](https://cloud.githubusercontent.com/assets/11466369/6648347/0f2fabca-c9af-11e4-9d89-2b652e183a93.png)
![thermal issue 6](https://cloud.githubusercontent.com/assets/11466369/6648222/a23e8c76-c9ad-11e4-9a15-a42d1b6c188c.png)

I bring this up as an issue because that configuration does function correctly with the EnderIO SAG mill and IC2 Macerator and Electric Furnace

![thermal issue 7](https://cloud.githubusercontent.com/assets/11466369/6648297/a25fcb06-c9ae-11e4-8001-db0854f84883.png)
![thermal issue 8](https://cloud.githubusercontent.com/assets/11466369/6648302/a89f02f2-c9ae-11e4-8fa5-f94c148c6960.png)

Have done limited testing, and so far the Pulverizer, Redstone Furnace, Vanilla Furnace, and EnderIO Alloy Smeltery (which while that's not necessarily your purview, i figure any and all info is relevant) will cause this effect. Could be more, but to tired to continue testing now

**Comment by KingLemming** [comment] 2015-03-13 23:17
Well, backstuffing isn't a bug. It's an intended feature.

The question is why some inventories trigger it and others don't. Offhand, I imagine the issue is a combination of tick order and how efficiently the inventory can be queried. TE is well-optimized, so the queries are pretty trivial and take next to no time.

Vanilla has no filtering whatsoever, so that is also trivial.

**Comment by rwtema** [comment] 2015-03-13 23:26
Fixed in dev.

It was simulating inserting items into the wrong side (opposite from what it should be). So if you made the pulverisers opposite side accept items then it would work properly.

**Comment by AnomalusCrafter** [comment] 2015-03-13 23:36
Alright, thanks guys, you're awesome.

**Closed** 2015-03-14 02:15 UTC
Labels: fixed
