### ISSUE TITLE
[Thermal Dynamics] Client/Server crash upon world load.

### ISSUE THREAD

**Issue by whitestarx0312** [CoFH/Feedback#342] opened 2015-03-25 03:58 UTC
This crash happened randomly while playing around with Thermal Dynamics pipes and MFR machines. Ever since then I cannot open the world, and I get a client and server crash (SMP)

Client: http://pastebin.com/arjRNc7p
Server: http://pastebin.com/eiDW9XaH

I am using all the release versions for Curse, not Curse Forge.

CoFHCore-[1.7.10]3.0.0RC7-211
CoFHLib-[1.7.10]1.0.0RC7-127
MineFactoryReloaded-[1.7.10]2.8.0RC8-86
ThermalExpansion-[1.7.10]4.0.0RC7-141
ThermalFoundation-[1.7.10]1.0.0RC7-62
ThermalDynamics-[1.7.10]1.0.0RC7-98

*I am using Optifine and Fastcraft.

**Comment by KingLemming** [comment] 2015-03-25 04:26
Duplicate of #291. Suggests something *very* bad has happened to your world and isn't actually caused by the mods. We may have a mitigation in dev, but I question if mitigating it is good, given what you're looking at.

**Closed by KingLemming** 2015-03-25 04:26 UTC
Labels: duplicate

**Comment by whitestarx0312** [comment] 2015-03-25 06:06
Works fine upon updating to the alphas on CurseForge! :)
