### ISSUE TITLE
Itemduct bug with furnaces

### ISSUE THREAD

**Issue by renzhentaxi** [CoFH/Feedback#875] opened 2018-01-22 00:51 UTC
Its hard to explain step by step so I posted a video of me doing it.
[https://streamable.com/0yi90](url) (you need to copy and paste this url into the browser to see the video)

It will eat/delete items as well as stops working for a while until u cause an "update" by placing and breaking an itemduct near the network.

I am using forge-14.23.1.2600
installed only the required mods for thermal dynamic 2.3.10.4
(codechicken, cofhcore, cofh world, redstone flux, thermal fundation)

**Comment by KingLemming** [comment] 2018-01-22 01:05
Duplicate of #472.

TD is going to be rewritten, so this won't be addressed in the 2.x line. Don't use vanilla furnaces, they are hot garbage.

**Closed by KingLemming** 2018-01-22 01:05 UTC
