### ISSUE TITLE
Mine-Factory- Crash -Meat Packer?

### ISSUE THREAD

**Issue by nuclearmario1000** [CoFH/Feedback#794] opened 2015-08-19 23:13 UTC
Using CoFHCore-[1.7.10]3.0.3-303
Using MineFactoryReloaded-[1.7.10]2.8.0-104

I loaded up a custom mod pack of my own to play with friends and later in the game, I was tinkering with a meat packer and I crashed my game. I wasn't able to get back on the server and neither were my friends, unless they were far enough away from the meat packer. And I have tried this also with just CoFH mods and it still crashed. Here is the mods I used (http://pastebin.com/hxk9dL1W) and the crash report:

---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 8/19/15 6:36 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at powercrystals.minefactoryreloaded.core.UtilInventory.dropStackInAir(UtilInventory.java:388)
	at powercrystals.minefactoryreloaded.core.UtilInventory.dropStackInAir(UtilInventory.java:326)
	at powercrystals.minefactoryreloaded.core.UtilInventory.dropStackInAir(UtilInventory.java:322)
	at powercrystals.minefactoryreloaded.core.UtilInventory.dropStack(UtilInventory.java:277)
	at powercrystals.minefactoryreloaded.core.UtilInventory.dropStack(UtilInventory.java:219)
	at powercrystals.minefactoryreloaded.tile.base.TileEntityFactoryInventory.doDrop(TileEntityFactoryInventory.java:231)
	at powercrystals.minefactoryreloaded.tile.machine.TileEntityMeatPacker.activateMachine(TileEntityMeatPacker.java:68)
	at powercrystals.minefactoryreloaded.tile.base.TileEntityFactoryPowered.func_145845_h(TileEntityFactoryPowered.java:109)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at powercrystals.minefactoryreloaded.core.UtilInventory.dropStackInAir(UtilInventory.java:388)
	at powercrystals.minefactoryreloaded.core.UtilInventory.dropStackInAir(UtilInventory.java:326)
	at powercrystals.minefactoryreloaded.core.UtilInventory.dropStackInAir(UtilInventory.java:322)
	at powercrystals.minefactoryreloaded.core.UtilInventory.dropStack(UtilInventory.java:277)
	at powercrystals.minefactoryreloaded.core.UtilInventory.dropStack(UtilInventory.java:219)
	at powercrystals.minefactoryreloaded.tile.base.TileEntityFactoryInventory.doDrop(TileEntityFactoryInventory.java:231)
	at powercrystals.minefactoryreloaded.tile.machine.TileEntityMeatPacker.activateMachine(TileEntityMeatPacker.java:68)
	at powercrystals.minefactoryreloaded.tile.base.TileEntityFactoryPowered.func_145845_h(TileEntityFactoryPowered.java:109)

-- Block entity being ticked --
Details:
	Name: factoryMeatPacker // powercrystals.minefactoryreloaded.tile.machine.TileEntityMeatPacker
	Block type: ID #503 (tile.mfr.machine.1 // powercrystals.minefactoryreloaded.block.BlockFactoryMachine)
	Block data value: 14 / 0xE / 0b1110
	Block location: World: (-193,64,85), Chunk: (at 15,4,5 in -13,5; contains blocks -208,0,80 to -193,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #503 (tile.mfr.machine.1 // powercrystals.minefactoryreloaded.block.BlockFactoryMachine)
	Actual block data value: 14 / 0xE / 0b1110
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: Survival
	All players: 1 total; [EntityPlayerMP['TheGWGunther'/212, l='Survival', x=-177.48, y=70.00, z=113.92]]
	Chunk stats: ServerChunkCache: 808 Drop: 0
	Level seed: -8465423832888665228
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (68,64,256), Chunk: (at 4,4,0 in 4,16; contains blocks 64,0,256 to 79,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2615246 game time, 2663948 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 32081 (now: false), thunder time: 6023 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.7.0_79, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1605559960 bytes (1531 MB) / 2004877312 bytes (1912 MB) up to 2004877312 bytes (1912 MB)
	JVM Flags: 2 total; -Xms2G -Xmx2G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 57 mods loaded, 57 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (MinecraftServer.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (MinecraftServer.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	BiblioCraft{1.10.5} [BiblioCraft] (BiblioCraft[v1.10.5][MC1.7.10].jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJAAAA	BuildCraft|Core{7.0.20} [BuildCraft] (buildcraft-7.0.20.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.0.20} [BC Silicon] (buildcraft-7.0.20.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.0.20} [BC Transport] (buildcraft-7.0.20.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.0.20} [BC Builders] (buildcraft-7.0.20.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.0.20} [BC Robotics] (buildcraft-7.0.20.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.0.20} [BC Energy] (buildcraft-7.0.20.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.0.20} [BC Factory] (buildcraft-7.0.20.jar) 
	UCHIJAAAA	BuildMod{v1.0} [Build Mod] (CoroUtil-1.1.1.jar) 
	UCHIJAAAA	CoroAI{v1.0} [CoroAI] (CoroUtil-1.1.1.jar) 
	UCHIJAAAA	ExtendedRenderer{v1.0} [Extended Renderer] (CoroUtil-1.1.1.jar) 
	UCHIJAAAA	ConfigMod{v1.0} [Extended Mod Config] (CoroUtil-1.1.1.jar) 
	UCHIJAAAA	EnderTech{1.7.10-0.3.2.388} [EnderTech] (EnderTech-1.7.10-0.3.2.388.jar) 
	UCHIJAAAA	HardcoreEnderExpansion{1.8.2} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.2.jar) 
	UCHIJAAAA	herdCraft{1.1} [HerdCraft] (HerdCraft-1.7.10-1.1.jar) 
	UCHIJAAAA	iChunUtil{4.1.0} [iChunUtil] (iChunUtil-4.1.0.jar) 
	UCHIJAAAA	IronChest{6.0.60.741} [Iron Chest] (ironchest-1.7.10-6.0.60.741-universal.jar) 
	UCHIJAAAA	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.12.7} [MalisisCore] (malisiscore-1.7.10-0.12.7.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.9.4} [Malisis' Doors] (malisisdoors-1.7.10-1.9.4(1).jar) 
	UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104(1).jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104(1).jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104(1).jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104(1).jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104(1).jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104(1).jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104(1).jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104(1).jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104(1).jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104(1).jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104(1).jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104(1).jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104(1).jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104(1).jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104(1).jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104(1).jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104(1).jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104(1).jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104(1).jar) 
	UCHIJAAAA	me{1.3.1.2} [More Enchantments] (More-Enchantments-Mod-1.7.10.jar) 
	UCHIJAAAA	AencEx{0.0.1} [AencEx] (More-Enchantments-Mod-1.7.10.jar) 
	UCHIJAAAA	moskeletons{1.0} [Mo'Skeletons] (MoSkeletons_1.7.10-1.0.jar) 
	UCHIJAAAA	quiverchevsky{b100} [QuiverBow] (QuiverBow_1.7.10_b100.zip) 
	UCHIJAAAA	RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
	UCHIJAAAA	rfwindmill{0.7a} [RF Windmill] (rfwindmill-1.7.10-0.7a.jar) 
	UCHIJAAAA	simplyjetpacks{1.5.1} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.5.1.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJAAAA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJAAAA	ZAMod{v1.9.5} [Zombie Awareness] (ZombieAwareness-1.9.6.jar) 
	CoFHCore: -[1.7.10]3.0.3-303
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	RedstoneArsenal: -[1.7.10]1.1.1-89
	ThermalDynamics: -[1.7.10]1.1.0-161
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 10; [EntityPlayerMP['TheGWGunther'/212, l='Survival', x=-177.48, y=70.00, z=113.92]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by skyboy** [comment] 2015-08-20 00:58
Duplicate of https://github.com/CoFH/Feedback/issues/716

**Closed by skyboy** 2015-08-20 00:58 UTC
