### ISSUE TITLE
[Thermal Dynamics] NPE Crashes on Server

### ISSUE THREAD

**Issue by GustoniaEagle** [CoFH/Feedback#265] opened 2015-03-07 13:04 UTC
Not quite sure what is causing this, started happening randomly today, and now continues to crash as soon as any player joins the world.

Initial Crash Log: http://pastebin.com/he4NdhAa
Log for Crash on World Join: http://pastebin.com/jSP7D99C

**Comment by TheJulianJES** [comment] 2015-03-07 13:06
Looks like #255

**Comment by KingLemming** [comment] 2015-03-09 17:46
Indeed a duplicate of #255

**Closed by KingLemming** 2015-03-09 17:46 UTC
Labels: duplicate
