### ISSUE TITLE
[Thermal Expansion] Crash with Cyclic Assembler

### ISSUE THREAD

**Issue by Neodark7** [CoFH/Feedback#1076] opened 2016-02-17 22:50 UTC
http://pastebin.com/Kyn5qqNX

This happen when i click on the green arrow to register the recipe for the Impregnated Frame from forestry.

**Comment by KingLemming** [comment] 2016-02-18 02:51
Duplicate of #1018. Please check for those in the future if you would. :)

**Closed by KingLemming** 2016-02-18 02:51 UTC
Labels: duplicate

**Comment by Neodark7** [comment] 2016-02-18 02:52
owe sorry about that...
