### ISSUE TITLE
[1.12.2] Crash during Initialization regarding the Compactor

### ISSUE THREAD

**Issue by Spearkiller** [CoFH/Feedback#1054] opened 2018-04-27 00:43 UTC
Title. On the latest version of Thermal Foundation (2.4.0.14) Minecraft crashes during initialization, Crash report says it has something to do with the Compactor, and Base Metals was mentioned in there somewhere so it's probably got to do with integration with that. I'm not an expert with crash reports but I figured i should send this here.

Crash Report:
https://pastebin.com/yKgxvZLK

**Comment by KingLemming** [comment] 2018-04-27 02:46
Duplicate of #1053. I'm just gonna leave this up so that people know how to fix it.

Disable TE integration in their config file.

**Closed** 2018-05-01 01:10 UTC
Labels: duplicate
