### ISSUE TITLE
Crash while launching

### ISSUE THREAD

**Issue by Sedesin** [CoFH/Feedback#48] opened 2017-03-06 19:03 UTC
I tried to add thermal expansion in my modpack but it kept crashing. So, I've just created a new instance with cofhcore related mods and it still crashes. Any idea why?
[crash-2017-03-06_18.56.43-client.txt](https://github.com/CoFH/Feedback/files/822175/crash-2017-03-06_18.56.43-client.txt)

**Comment by KingLemming** [comment] 2017-03-06 19:09
Duplicate of #39. Please update/reinstall/whatever, but it's not on us. Something went wrong with your install.

**Closed by KingLemming** 2017-03-06 19:09 UTC
