### ISSUE TITLE
1.10.2 Crash with latest version of ThermalExpansion

### ISSUE THREAD

**Issue by mcdodge34** [CoFH/Feedback#302] opened 2017-06-26 21:51 UTC
Ok, not sure which mod cause this crash cause with only cofhcore thermalExpansion and ThermalFoundation in a new 1.10.2 instance, I have 0 problems, but when I add them to my 1.10.2 modpack, I get this crash, downgrading to previous version of CofhCore and ThermalExpansion solve the issue so its probably something brand new from today version.

Here's the crash report, I didn't found any useful infos on it, but maybe you're more experienced than I am, the modelbakery doesn't tell me which mod cause this issue.

https://pastebin.com/CVPVEWsA

**Comment by KingLemming** [comment] 2017-06-26 21:54
There's nothing in the log that really says anything, sorry. :/ I'll leave it up so if you figure out the actual cause, you can let us know. At this point though - I'm quite sure it's not us.

The mods are tested by dropping them into FTB Beyond to ensure that they run, so...yeah this is basically unique to you.

**Comment by mcdodge34** [comment] 2017-06-26 22:23
I'm trying real hard to help you out right now, investigating what could cause this, can I trigger some diagnostics logs out of your mods that aren't normally there so I could check which mod does this

**Comment by mcdodge34** [comment] 2017-06-26 22:27
Hum, strange now, I upgraded to latest forge 2316 from 2281, and now it seems to work correctly, I got to test a little more.

**Comment by mcdodge34** [comment] 2017-06-26 22:36
Wow, this crash is there again, very very strange issue there, launched the pack 4 times without issues then it started again.

**Comment by mcdodge34** [comment] 2017-06-26 22:54
Hum, could it be related to Minefactory reloaded, its one of the latest mod I added to the pack along with Mo's Creatures, I'll test more tomorrow.

**Comment by KingLemming** [comment] 2017-06-27 00:35
Is it maybe possible you're just running out of RAM or something like that?

**Comment by KingLemming** [comment] 2017-06-27 03:36
Honestly, I'm betting it won't happen with MFR gone. I think this is something that MFR is doing.

**Comment by mcdodge34** [comment] 2017-06-27 04:39
Yup, I have no clue what cause this crash, tried different things tonight and conclusion for now, it happens randomly with the mods I still have in the pack, I removed MFR and will do some further testing tomorrow involving Mo's Creatures, since I've noticed no matter what I do to the config files for Mo Creatures, nothing seems to work, could be related, maybe it corrupt something in memory while running but it doesn't happen every time. For now, need to sleep. I'm in GMT-5 time zone.

**Comment by xAlicatt** [comment] 2017-07-01 02:39
Are you running a local server using Sponge by chance?

**Comment by Narwhal8** [comment] 2017-07-01 02:54
I am also having this issue

**Comment by xAlicatt** [comment] 2017-07-01 03:03
If you are running a sponge server...this is a known issue and it's COFH Core causing it...not thermal

**Comment by Narwhal8** [comment] 2017-07-01 03:03
No. I ran it as the only mod on curse and didnt work

**Comment by Narwhal8** [comment] 2017-07-01 03:12
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.9.13-universal.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 6/30/17 11:11 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CoFH Core (cofhcore)
Caused by: java.lang.NoClassDefFoundError: com/typesafe/config/ConfigException
	at cofh.CoFHCore.registerHandlers(CoFHCore.java:155)
	at cofh.CoFHCore.preInit(CoFHCore.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:624)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:259)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.typesafe.config.ConfigException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 41 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Mac OS X (x86_64) version 10.11.5
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 584524744 bytes (557 MB) / 931659776 bytes (888 MB) up to 3102212096 bytes (2958 MB)
	JVM Flags: 3 total; -Xmx3328m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2297 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2297.jar) 
	UCH	Forge{12.18.3.2297} [Minecraft Forge] (forge-1.10.2-12.18.3.2297.jar) 
	UCH	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCE	cofhcore{4.1.9} [CoFH Core] (CoFHCore-1.10.2-4.1.9.13-universal.jar) 
	Loaded coremods (and transformers): 
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.9.13-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager

**Comment by KingLemming** [comment] 2017-07-01 03:12
Forge didn't install properly for you. That's a different issue. Reinstall it.

**Comment by Narwhal8** [comment] 2017-07-01 03:13
It worked about a month before i had problems with this mod

**Comment by Narwhal8** [comment] 2017-07-01 03:15
Also here it is re-installed

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.9.13-universal.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 6/30/17 11:15 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CoFH Core (cofhcore)
Caused by: java.lang.NoClassDefFoundError: com/typesafe/config/ConfigException
	at cofh.CoFHCore.registerHandlers(CoFHCore.java:155)
	at cofh.CoFHCore.preInit(CoFHCore.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:624)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:259)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.typesafe.config.ConfigException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 41 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Mac OS X (x86_64) version 10.11.5
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 607064488 bytes (578 MB) / 964689920 bytes (920 MB) up to 3102212096 bytes (2958 MB)
	JVM Flags: 3 total; -Xmx3328m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2316 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2316.jar) 
	UCH	Forge{12.18.3.2316} [Minecraft Forge] (forge-1.10.2-12.18.3.2316.jar) 
	UCH	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCE	cofhcore{4.1.9} [CoFH Core] (CoFHCore-1.10.2-4.1.9.13-universal.jar) 
	Loaded coremods (and transformers): 
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.9.13-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager

**Comment by KingLemming** [comment] 2017-07-01 04:19
Same error. Don't know why you aren't getting the libs, but you seem to not be.

**Comment by Narwhal8** [comment] 2017-07-01 04:20
doesnt work on FTB either  and no other mod doesnt work

**Comment by Narwhal8** [comment] 2017-07-01 16:09
how can i fix it?

**Comment by KingLemming** [comment] 2017-07-01 18:04
Told you how. If Forge isn't download the libraries that it is supposed to, I'm not sure what to tell you.

**Comment by AnthonyKane5528X** [comment] 2017-07-02 16:01
I can tell you what was causing my issue, but I just want to say that **THIS DOES NOT UNIVERSALLY APPLY**  

I was getting a Null Pointer Exception whenever I tried to update to the latest version of Thermal Expansion.

Then I noticed I was getting this same Null Pointer exception if I tried to update Forestry, IC2, RFtools, ect.

So I tried uninstalling MFR.  And suddenly everything was able to update and work.  Mind you I was still using the oldest BETA version of MFR, but that was because the curse launcher didn't show any updates available since pretty much everything that's being released for MFR was in ALPHA.  But even then I couldn't update to the new Alpha, because that would cause the same exception.

No the only way to fix it (As far as I could tell) was to completely remove MFR, then update all the mods, AND THEN put MFR's latest alpha back in.

I don't know if its MFR causing it (in terms of code or programing) 

I'm just letting you know my experience, what I did to fix it, and hopefully it helps narrow down the actual cause.

**Comment by piedpipr314** [comment] 2017-07-06 05:39
I did find that downgrading Thermal Expansion fixed it on my end.  I posted the same crashlog with different mods, and didn't think to look here until afterward.  At least KingLemming knows about both.  Perhaps we can all work together to narrow this down.

**Comment by KingLemming** [comment] 2017-07-06 05:42
Removed comments related to a separate issue. I would like to know if anybody can make this happen without MFR.

**Comment by piedpipr314** [comment] 2017-07-06 06:56
I'm working on it, isolating common mods between the two packs.  I'll let you know.

**Comment by piedpipr314** [comment] 2017-07-06 07:21
It's very odd indeed.  Isolated including MFR, no crash, without MFR and not isolated, no crash.  It very well could be caused by MFR, but I can't confirm that.

**Comment by piedpipr314** [comment] 2017-07-06 14:41
Okay, so with many mods plus EnderIO and the config option that sets MFR to do vanilla only causes this problem it seems.  Without EnderIO, MFR runs smooth as silk.

**Comment by AnthonyKane5528X** [comment] 2017-07-06 14:49
@piedpipr314 
-So is it having EnderIO in the pack that's causing this issue, or is it setting the MFR recipes to use EnderIO parts that's causing the issue?

From what your last post says, it sounds like just having EnderIO in the pack is enough to cause the problem.

**Comment by piedpipr314** [comment] 2017-07-06 21:14
It's a little stranger than that I think.  If you add EnderIO first it seems, and then add MFR, it changes the config to use EnderIO recipes.  If you add EnderIO after MFR (hence after it made the config), it works without a crash.  It's almost as if MFR expects the recipes and is looking for them.

**Comment by piedpipr314** [comment] 2017-07-06 21:26
Well, I had an idea that it might have been the config causing this problem as well, but it's not.  I can tell you this, having a large pack with many mods AND EnderIO AND the config for MFR generated after EnderIO caused this problem, but I don't know why.

**Comment by piedpipr314** [comment] 2017-07-06 21:37
Update all COFH mods in the pack you're using, it seems to fix this problem entirely.  Thanks TeamCOFH and everyone involved!  You guys can probably close this one unless someone else has an issue after the update.

**Comment by piedpipr314** [comment] 2017-07-06 22:29
In other words, a smaller pack with EnderIO AND MFR does NOT cause this, I don't know that I can diagnose the actual issue.

**Comment by JSJBDEV** [comment] 2017-07-07 00:07
I had this problem and removing MFR fixed it for me. bearing in mind it uses COFH core it probably means its own recipes are changed to implement thermal expansion things, but they seem to be implemented wrongly. although it doesn't make sense that it would be a rendering error being caused by MFR to thermal expansion.

**Comment by JSJBDEV** [comment] 2017-07-07 00:09
mine however seems to be different to the aformention pastebin `java.lang.IllegalStateException: Already building!
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:187)
	at codechicken.lib.render.buffer.BakingVertexBuffer.func_181668_a(BakingVertexBuffer.java:55)
	at cofh.thermalexpansion.render.RenderMachine.bakeItemQuads(RenderMachine.java:104)
	at codechicken.lib.model.blockbakery.BlockBakery.generateItemModel(BlockBakery.java:185)
	at codechicken.lib.model.blockbakery.BlockBakery.getCachedItemModel(BlockBakery.java:160)
	at codechicken.lib.model.blockbakery.CCBakeryModel$1.handleItemState(CCBakeryModel.java:63)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:249)
	at codechicken.lib.render.item.CCRenderItem.func_184393_a(CCRenderItem.java:297)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:228)
	at codechicken.lib.render.item.CCRenderItem.func_180450_b(CCRenderItem.java:220)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:867)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:703)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:76)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:591)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

`

**Comment by piedpipr314** [comment] 2017-07-07 01:32
I duplicated this crash with a recipe lookup for a fluid in EnderIO (vapor of levity).  I may have narrowed the search down to a fluid handler.

**Comment by JSJBDEV** [comment] 2017-07-07 20:48
we should possibly be telling skyboy, as it is MFR at the source of the problem either way

**Comment by KingLemming** [comment] 2017-07-07 21:10
Yes, you should. :)

**Comment by JSJBDEV** [comment] 2017-07-07 21:11
https://github.com/skyboy/MineFactoryReloaded/issues/647 already on it

**Comment by piedpipr314** [comment] 2017-07-08 08:41
In case someone does not want to follow the links to perhaps the actual problem:
https://github.com/TheCBProject/CodeChickenLib/issues/67

**Comment by covers1624** [comment] 2017-07-08 08:51
No, this is still the phantom mfr milk bucket crash.

**Closed** 2017-07-16 17:45 UTC
Labels: another mod, wtf
