### ISSUE TITLE
Bonus Redstone Furnace (Basic)

### ISSUE THREAD

**Issue by petikesajt** [CoFH/Feedback#139] opened 2017-03-29 16:54 UTC
If you break any Thermal Expansion machine with a Psi block breaker program it will drop a bonus Redstone Furnace (Basic) machine. (Works whit the Redstone Furnace too. Just doubles it (can't stack))

**Comment by KingLemming** [comment] 2017-03-29 16:57
Duplicate of #93.

This is Psi's fault.

**Closed by KingLemming** 2017-03-29 16:57 UTC
