### ISSUE TITLE
[COFH Tweaks] crash on startup

### ISSUE THREAD

**Issue by walkerjonny** [CoFH/Feedback#1014] opened 2016-01-27 07:25 UTC
I got this crash on startup of MC:
http://pastebin.com/QFLnfUPy
I'm playing with the newest released COFH mods and Fastcraft 1.22_ctest18 and try to keep my mod folder as actual as possible.

**Comment by skyboy** [comment] 2016-01-27 08:05
Duplicate of https://github.com/CoFH/Feedback/issues/481

**Closed by skyboy** 2016-01-27 08:05 UTC
