### ISSUE TITLE
Texture glitches :/

### ISSUE THREAD

**Issue by Adc808** [CoFH/Feedback#624] opened 2015-06-29 20:14 UTC
If anyone has time I have a problem with the textures. They get glitchy when I put the mods in. Here is the list of mods http://paste.ubuntu.com/11794917/. Here is a video showing what is happening https://www.dropbox.com/s/vqptg8j0chm0j5n/Mod%20Problem%20recording.mov?dl=0

**Comment by KingLemming** [comment] 2015-06-29 21:56
So are you using Optifine? If so, that's probably the cause.

**Comment by KingLemming** [comment] 2015-06-29 23:18
Closing, since you said it was fixed in IRC.

**Closed by KingLemming** 2015-06-29 23:18 UTC

**Comment by gcewing** [comment] 2016-02-22 04:34
Can you tell me how you resolved this? I'm experiencing something very similar:
https://github.com/CoFH/Feedback/issues/1078

**Comment by Adc808** [comment] 2016-02-24 04:59
I am pretty sure that I had to update my java.
