### ISSUE TITLE
Thermal Dynamics Bug

### ISSUE THREAD

**Issue by Reyls** [CoFH/Feedback#336] opened 2015-03-23 11:10 UTC
http://pastebin.com/M0FnfCaf

Latest version from curse

the crash occurs while disabling a side of an alloy smelter an opaque itemduct is connected to.
the alloy smelter should receive items with a filter.
now the world crashs every time I try to open it.

EDIT: Meanwhile I managed to dismantle the itemduct before it crashs. Yay!

**Comment by TheJulianJES** [comment] 2015-03-23 15:31
I thought this was already fixed?

**Comment by KingLemming** [comment] 2015-03-23 17:58
This has either been fixed in dev already, or there's something else happening here and it's not being properly conveyed. Because I can't reproduce this.

**Comment by KingLemming** [comment] 2015-03-24 10:11
Marking as fixed in dev, since I'm guessing it is.

**Closed** 2015-03-31 22:11 UTC
Labels: fixed
