### ISSUE TITLE
Thermal Expansion crash when shift-clicking empty cache

### ISSUE THREAD

**Issue by jschuzter** [CoFH/Feedback#1236] opened 2016-08-15 06:13 UTC
After shift-clicking an empty hardened cache from Thermal Expansion my game crashed, was able to repeat the crash as well. I am running the FTB Infinity Evolved modpack version 2.6.0, with a few additional mods including FOVcontrol, Ztones, Chiseltones, Climate Control and Realistic Terrain Generation. The version of Thermal Expansion is 4.1.3-246

The hardened cache is hooked up to an EnderIO item conduit, to an iron chest full of items. The cache had items in it, which were completely removed by shift-clicking rapidly, once the items were removed the cache was empty and I shift-clicked the empty cache, causing a crash.

The crash report is attached.

[crash-2016-08-15_15.55.15-server.txt](https://github.com/CoFH/Feedback/files/417590/crash-2016-08-15_15.55.15-server.txt)

EDIT: Appears that the crash happens no matter the situation... If i click a cache that's empty I crash. I'm sure it didn't use to happen. Haven't changed anything in terms of mods recently except update FTB Infinity Evolved to 2.6.0

**Comment by skyboy** [comment] 2016-08-15 19:36
Duplicate of https://github.com/CoFH/Feedback/issues/1227 and fixed a week ago.

**Closed by skyboy** 2016-08-15 19:36 UTC
