### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by H3roDude** [CoFH/Feedback#1271] opened 2018-08-30 11:02 UTC
Hey peeps, when i try to start my server it crashes away.. heres the crashlog: https://pastebin.com/YaaE8TnE

**Comment by Tora-B** [comment] 2018-08-30 11:11
Duplicate of #1208. Update CoFHCore to 1.12.2-4.5.3.20, or downgrade Forge below 2739.

**Comment by H3roDude** [comment] 2018-08-30 11:14
i will try to use 2705

**Comment by H3roDude** [comment] 2018-08-30 11:33
So Udpate: I have Forge 14.23.4.2715 and CoFHCore 4.5.2.19 but its still crashing

**Comment by KingLemming** [comment] 2018-08-30 12:17
You're doing something wrong. Use 2739+ and the latest Core or 2738- and Core .19.

**Closed by KingLemming** 2018-08-30 12:17 UTC
