### ISSUE TITLE
[Thermal Expansion 1.10.2] Random rendering crash with machines... maybe?

### ISSUE THREAD

**Issue by Bobynoby** [CoFH/Feedback#133] opened 2017-03-27 05:48 UTC
(Another WTF crash I think)
Not sure about who to contact about this, But the block that crashed seemed to be yours. Playing on a server, I went to teleport to another dimension when I just crashed for no reason.

Could not seem to recreate the crash either.

Unable to list mods as there is a 140+ mods.

Forge: 1.10.2-12.18.3.2254
Thermal Expansion: 1.10.2-5.0.4.90
CoFH Core: 1.10.2-4.1.1.156
CodeChickenCore: 1.10.2-2.4.0.101
CodeChickenLib:  1.10.2-2.5.7.241

Crash Reports
Server just did nothing, It didn't crash and nothing odd showed in console
Client Crash: http://pastebin.com/6bz51t1b

**Comment by KingLemming** [comment] 2017-03-27 06:39
Hmm. I'm gonna call this a duplicate of #131.

**Comment by KingLemming** [comment] 2017-03-27 06:40
Hrm...actually wait, I don't see TE anywhere in that stack trace, so I'm not sure why you're making the accusation.

**Comment by covers1624** [comment] 2017-03-27 06:40
Err, no this isn't a duplicate and is crashing in mojang code..

**Comment by Bobynoby** [comment] 2017-03-27 06:41
Just figured it was you, It does say the tessellation was from tile.cofh.machine

**Comment by covers1624** [comment] 2017-03-27 06:59
Re opening as this may actually be an issue. Are you able to recreate this under any circumstances?

**Comment by Bobynoby** [comment] 2017-03-27 07:01
I tried a couple times in the exactly the same way but I was not able to crash agian

**Comment by KingLemming** [comment] 2017-06-06 05:06
Yep. Pretty sure this is fixed upstream.

**Closed by KingLemming** 2017-06-06 05:06 UTC
Labels: wtf
