### ISSUE TITLE
[CoFH Tweaks 1.0.0-36] Optifine crash / incompatible

### ISSUE THREAD

**Issue by Tomson124** [CoFH/Feedback#812] opened 2015-09-01 15:40 UTC
Minecraft crashes with Optifine and CoFH Tweaks at startup, if I remove Optifine ist starts up just fine.

Crashlog: http://pastebin.com/LDqmeEnj

EDIT: Is it a client only mod? I'm not seeing any info about server usage or dependence on Curse.

**Comment by skyboy** [comment] 2015-09-01 19:42
Duplicate of https://github.com/CoFH/Feedback/issues/482

**Closed by skyboy** 2015-09-01 19:42 UTC
