### ISSUE TITLE
Stored energy amount does not display properly

### ISSUE THREAD

**Issue by marcin212** [CoFH/Feedback#157] opened 2015-02-22 20:28 UTC
Stored energy amount does not display properly, if it is above 50 million (probably due to the increase in capacity)
Tested with freshly crafted cell.

https://dl.dropboxusercontent.com/u/25172450/bugs/bugs1710/8081ef23c876f6026257b61672217601.png

**Comment by KingLemming** [comment] 2015-02-22 21:01
Duplicate of #144.

**Closed by KingLemming** 2015-02-22 21:01 UTC
Labels: duplicate, fixed in dev
