### ISSUE TITLE
[1.10.2] CoFH Core Incompatibility with Sponge

### ISSUE THREAD

**Issue by yepidoodles** [CoFH/Feedback#326] opened 2017-07-01 12:08 UTC
Today I was doing an update today on my Technology based Server/ Modpack (all mods, Forge, SpongeForge); when I got the following Error from Sponge:

http://www.codesend.com/view/5fe62f796d6090aff7d5c192b26d486d/

I first backdated Forge and SpongeForge to check that it wasn't an issue with those.

I then backdated a few of the Core Mods before I found that CoFH Core was responsible (`CoFHCore-1.10.2-4.1.9.13-universal`), backdating it fixed my issue.

Not sure what the issue is exactly, but that error above is all that I have. The version I was using before and that I backdated to was `CoFHCore-1.10.2-4.1.1.156-universal`

I assume that as I haven't seen this reported and they were updated in the last 2 days that it was the latest version that the issue is in.

Many thanks for any help

- Alice Sellars
DragonTechMC

**Comment by KingLemming** [comment] 2017-07-01 12:12
Duplicate of #299. Supposedly they fixed it.

**Closed by KingLemming** 2017-07-01 12:12 UTC

**Comment by yepidoodles** [comment] 2017-07-03 11:10
It's clearly not fixed and not supporting Sponge is ridiculous as it's the only way to make public modded servers.

**Comment by covers1624** [comment] 2017-07-03 13:14
Woah calm down, there is literelly nothing we can do on our end for this, sponge claimed they had fixed it their end, read the other issue before jumping to conclusions.
