### ISSUE TITLE
Induction Smelter and Invar

### ISSUE THREAD

**Issue by Xiaminou** [CoFH/Feedback#670] opened 2017-11-30 00:18 UTC
The Induction Smelter only consumes 1 of 2 Iron Ingots when making 3 Invar Ingots with 2 Iron Ingots and 1 Nickel Ingot.
Video for clarification: https://youtu.be/5ZYo6-yjAUc

Minecraft: 1.12.2
Forge: 2556
Thermal Expansion: 1.12.2-5.3.7.25-universal
Mods: [list.txt](https://github.com/CoFH/Feedback/files/1516046/list.txt)

**Comment by KingLemming** [comment] 2017-11-30 00:53
Duplicate of #669.

**Closed by KingLemming** 2017-11-30 00:53 UTC

**Comment by Xiaminou** [comment] 2017-11-30 01:08
Damn, he beat me to it.

**Comment by KingLemming** [comment] 2017-11-30 01:11
Yep, sorry. Either way, it's fixed. :D Go download the new one. ;)

**Comment by mcdodge34** [comment] 2017-11-30 02:53
Sorry to open this one again, but its just for a quick question, should I update my mods as soon as theses bugs are fixed or I'm ok with version 24 that I got this morning, just want to be on the safe side if anything major happens, for sure I will report if I find anything that is really broken, but for now I don't mind it and won't abuse this kind of bugs, I plan to update the mods nearly each morning for awhile, I'm on the release channel so usually I assume mods there are stable apart from this kind of hickups that can happen when you add a lot of new functions and machines.

I'm keeping myself up to date on the latest fix here in case there's a major problem. But so far, I love the new build especially the tome of Knowledge, will submit a suggestion in a separate topic for it.

**Comment by KingLemming** [comment] 2017-11-30 03:02
I would probably update ASAP just for completeness reasons.
The reason I'm not bumping the version number is that ehh, this is just sort of expected and the total # of downloads is small. But these tiny updates won't cause any breaks that the major update didn't.

**Comment by mcdodge34** [comment] 2017-11-30 03:05
Ok then, will be in the updates tomorrow anyways, and I have backups of my server every 2hrs if something goes wrong. I was maniac before about updates even with alpha versions, then I got problems and decided to stick to release versions this time, playing the DW20 1.12.2 pack, but I keep the mods updated manually and added a bunch of mods to it.
