### ISSUE TITLE
[Crash]  ThermalExpansion-[1.7.10]4.0.0B8-23  (Forge 10.13.2.1264)

### ISSUE THREAD

**Issue by Carbon-Key** [CoFH/Feedback#11] opened 2015-01-11 02:30 UTC
Hello!  Long time fan of your mods, you do wonderful work. :D 
Hopefully I've just done something stupid here and we can all laugh at me and move along. http://pastebin.com/wm3z4bBf should give you a list of the mods I've put together and http://pastebin.com/z2ew0ree should be the crash log.  The list of mods is from me typing what appeared on the list in the "Mods" menu in my client.  If there is a better/more readable method of displaying what I have installed then I will try to supply you with that. On to the issue!  I got a crash apparently trying to render an energy cell inside of a lootable body container (inventory) from Dr. Cyano's Lootable Bodies mod.  The log screamed at me about Thermal Expansion so I thought to try here first but if you think the issue is with the lootable bodies mod then I will post there as well.  When I put a cell inside of a standard inventory (e.g. a vanilla chest) and attempt to access it I get no crash, it seems to just be when accessing the lootable body created after killing myself.  I was getting some funny render glitches outside of the body gui though when i had the Cell in my hand.  The included screenshot shows an example of this.
![2015-01-10_15 51 40](https://cloud.githubusercontent.com/assets/10481639/5694086/c94ed53e-990e-11e4-92a1-f2adf954c218.png)
The effect stopped as soon as I switched to another slot in my hotbar.  That screenshot was taken using Forge 10.13.2.1236, after upgrading to 10.13.2.1264 I have been able to reproduce the crash consistently, but not the weird rendering bug from the screenshot. Hope you can make more sense of this than I can! I look forward to hearing from you soon, thanks. :D

**Comment by KingLemming** [comment] 2015-01-11 03:54
So what's happened here is that you had some sort of ID reassignment happen and Lootable bodies failed to correct for it.

Metadata 32 is one that we use in our items, but not our blocks. The fact that it's looking for metadata 32 on the cell means that a few things got swapped under the hood. I don't know if it's specific to your world or the Lootable Bodies mod. Does it happen with anything else?

**Comment by Carbon-Key** [comment] 2015-01-11 04:21
The cell is the only thing I have seen this happen with, as you can see in the screenshot i tried it with a few other blocks in hand and nothing bad happened.  I did discover however that the weird effects from the screenshot in my first post are reproducible by dying with the item in hand.  These tests were done in a new world just to make sure it wasn't about the save file.
![2015-01-10_23 10 21](https://cloud.githubusercontent.com/assets/10481639/5694340/db45b888-991e-11e4-91d0-9967694bc178.png)
I'm not sure I understand what you meant by some things getting swapped under the hood. :P If you could explain a little more what you think happened perhaps it would help me explain it to the lootable bodies developer.  I'm pretty sure from what you've said so far that it is on their side.  Also, thank you so much for your quick response!

**Comment by KingLemming** [comment] 2015-01-11 05:00
I don't see any weird effects happening there. Could you please elaborate?

And basically what I mean is that somehow you have an item with say ID 2003 and metadata 32. When it's in a lootable body, that is showing up as ID 2004 instead (or something). 2004 doesn't have 32 metadata, so it freaks out. The ID is being swapped.

**Comment by Carbon-Key** [comment] 2015-01-11 05:07
The effects I was talking about were the ones from my first screenshot, the one with my body inverted and the nearby lakes up in the sky etc.  The screenshot with the three corpses is just to show nothing out of the ordinary happening with blocks that aren't the energy cell, sorry for the confusion.  

Thank you for the further explanation!  I think I get it now, i'll relay what I know of the issue to the lootable bodies developer and hopefully we can get it figured out.  Thank you for all your help!  Should I let you know in this thread what sort of answer I get from DrCyano?

**Comment by skyboy** [comment] 2015-01-11 07:06
The render issue is caused by lootable bodies not properly pushing all the necessary GL states before letting items render.

The metadata issue appears to be that lootable bodies is re-creating the item incorrectly and using the display damage value instead of the actual damage value (which is easily avoided by using the item it has (there's even a .copy() method if it needs copied) instead of attempting to re-create it in a wholly incorrect manner).

**Closed** 2015-01-11 07:06 UTC

**Comment by Carbon-Key** [comment] 2015-01-11 14:58
All right, I'll relay that information.  Thank you King and sky for all your help.  Keep up the awesome modding! :D

**Comment by cyanobacterium** [comment] 2015-01-20 12:18
DrCyano here.
Lootable Bodies damages all items where **ItemStack.isItemStackDamageable() == true** , there-by changing the metadata value if the damage value is used for metadata. 32 happens to be the default damage setting (32 points of item damage to each damageable item added to the corpse). The short-term solution is to upgrade to Lootable Bodies version 1.3.0 and set *item_damage_on_death=0* in the config file, but I'd really like to know how to detect whether a damageable item is safe to apply damage to (e.g. a pick-ax or helmet) and damage those items while leaving objects like your energy cell alone.

**Comment by skyboy** [comment] 2015-01-22 17:42
@cyanobacterium Your check isn't working then, TE's Energy Cell's ItemBlock calls `setHasSubtypes(true)` and items that have subtypes return false from isDamagable

**Comment by cyanobacterium** [comment] 2015-01-24 13:05
Carbon-Key fixed his problem by turning off item damage (config file option), adding extra confirmation that this is an issue with applying item damage to that item.

I had been using this to check whether an item is damageable:
```java
public static ItemStack applyItemDamage(ItemStack itemstack){
  if(additionalItemDamage == 0) return itemstack;
  if (itemstack != null && itemstack.isItemStackDamageable()) {
    final int newDamageValue = itemstack.getItemDamage() + additionalItemDamage;
    itemstack.setItemDamage(Math.min(newDamageValue, itemstack.getMaxDamage() - 1));
  }
}
```
Somehow, the above code still applied item damage to Carbon-Key's Energy Cell item. I'm now using the following to account for the possibility of subtypes on an itemstack that still appears damageable for some reason:
```java
public static ItemStack applyItemDamage(ItemStack itemstack){
  if(additionalItemDamage == 0) return itemstack;
    if (itemstack != null 
        && itemstack.isItemStackDamageable()
        && itemstack.getItem().isDamageable() 
        && (!itemstack.isStackable())
        && (!itemstack.getItem().getHasSubtypes())
        && (itemstack.getItem().getMaxDamage() > 0) ) {
    final int newDamageValue = itemstack.getItemDamage() + additionalItemDamage;
    itemstack.setItemDamage(Math.min(newDamageValue, itemstack.getMaxDamage() - 1));
  }
  return itemstack;
}
```
If you can think of an even better check, I'm all ears!  :)
