### ISSUE TITLE
Crash trying to rotate autonomous activator with cresent hammer

### ISSUE THREAD

**Issue by 61352151511** [CoFH/Feedback#290] opened 2015-03-11 14:30 UTC
It was facing upwards, I wanted to face downwards, and the cresent hammer didn't think that was a good idea.

http://pastebin.com/x3ymtJPs

**Comment by KingLemming** [comment] 2015-03-11 15:54
Duplicate of #257

**Closed by KingLemming** 2015-03-11 15:54 UTC

**Comment by 61352151511** [comment] 2015-03-11 19:18
The search function on github sucks, searched "auto" before posting this and got nothing, sorry
