### ISSUE TITLE
[TD] Signalum-plated itemducts randomly stop transmitting power

### ISSUE THREAD

**Issue by AntidermisMC** [CoFH/Feedback#929] opened 2018-02-16 15:58 UTC
Minecraft 1.12.2
Modpack : All The Mods 3 v5.7c
CofH Core : 4.3.10.5  
Thermal Dynamics : 2.3.10.4  

I have leadstone fluxducts bringing power to an automated system which uses some signalum plated fluxducts. They are visually connected.
Signalum plated itemducts only receive power for a short time, then, seemingly whenever their internal buffer fills the leadstone fluxducts stop feeding them power. They remain visually connected but don't receive power when their buffer empties, I have to manually disconnect then reconnect the junctions to have them exchanging power again. It does seem to bug too when using higher-tier fluxducts.

**Comment by KingLemming** [comment] 2018-02-16 16:09
Duplicate of #437. Not something I've ever been able to make happen.

**Closed by KingLemming** 2018-02-16 16:09 UTC
