### ISSUE TITLE
Server Crash with ducts

### ISSUE THREAD

**Issue by bigbaddevil7** [CoFH/Feedback#233] opened 2017-06-12 23:36 UTC
Sorry I cant add more info than this it was pulled from the latest FML server log from our server and don't know who was doing what. Need anymore info you know where to ping me. 

[19:27:17] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@74a781df:
java.lang.NullPointerException
    at cofh.thermaldynamics.duct.tiles.TileGrid.canConnectEnergy(TileGrid.java:1127) ~[TileGrid.class:?]
    at com.rwtema.extrautils2.utils.CapGetter$2.convertInstance(CapGetter.java:41) ~[CapGetter$2.class:?]
    at com.rwtema.extrautils2.utils.CapGetter$2.convertInstance(CapGetter.java:38) ~[CapGetter$2.class:?]
    at com.rwtema.extrautils2.utils.CapGetter$Converter.convert(CapGetter.java:162) ~[CapGetter$Converter.class:?]
    at com.rwtema.extrautils2.utils.CapGetter.getInterface(CapGetter.java:146) ~[CapGetter.class:?]
    at com.rwtema.extrautils2.utils.CapGetter$3.getInterface(CapGetter.java:54) ~[CapGetter$3.class:?]
    at com.rwtema.extrautils2.utils.CapGetter$3.getInterface(CapGetter.java:44) ~[CapGetter$3.class:?]
    at com.rwtema.extrautils2.power.energy.EnergyTransfer.onServerTick(EnergyTransfer.java:104) ~[EnergyTransfer.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_308_EnergyTransfer_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274) [FMLCommonHandler.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by KingLemming** [comment] 2017-06-12 23:47
Duplicate of #224. We'll have a fix later tonight. Sorry about that.

**Closed by KingLemming** 2017-06-12 23:47 UTC
