### ISSUE TITLE
Satchel Bugs

### ISSUE THREAD

**Issue by Akitori** [CoFH/Feedback#1247] opened 2018-08-09 15:50 UTC
So I got a crash similar to another issue, except i was a curious bugger. I wanted to see how replicatable it was, what caused it, why it happened, etc.

And my results are as follows:

![2018-08-08_14 33 01](https://user-images.githubusercontent.com/24502131/43910249-e91068ce-9bc1-11e8-8977-aa62fe9b0c16.png)

![2018-08-08_14 33 45](https://user-images.githubusercontent.com/24502131/43910255-ede2935e-9bc1-11e8-923f-9dba792051d2.png)

I feel this is a bug. Or at the least, a undocumented feature? It seems kinda strange to combine 2 of say, iron backpacks to get a gold. Stranger to get a iron and gold and get diamond. 

Oh, and modded dyes don't work on the satchels. (Like inspirations colored water)

**Comment by KingLemming** [comment] 2018-08-10 17:34
Duplicate of #1236. Underlying issue is the same.

**Closed by KingLemming** 2018-08-10 17:34 UTC

**Comment by KingLemming** [comment] 2018-08-14 04:57
To be clear though, if modded dyes aren't working, that's on them. They aren't properly oredicting as "dye".
