### ISSUE TITLE
Pixelmon crash

### ISSUE THREAD

**Issue by Badcholo** [CoFH/Feedback#599] opened 2015-06-11 19:47 UTC
Using the latest Pixelmon and thermal expansion causes a crash. Using much older versions works but causes a crash when looking into the energy cell. I'm making a pixelmon modpack and would love to use CoFH mods.

Logs and crash report with minimum mods installed.
https://www.dropbox.com/sh/cnoqfyrijctkfkf/AAAUHff0bMDWeHaq3KR6d68Ia?dl=1

**Comment by KingLemming** [comment] 2015-06-11 22:01
Duplicate of #571. This is 100% on Pixelmon but I don't think they're willing to fix it. Sorry. :(

**Closed by KingLemming** 2015-06-11 22:01 UTC

**Comment by Badcholo** [comment] 2015-06-13 06:34
crud, thanks
