### ISSUE TITLE
Client Side Render Crash

### ISSUE THREAD

**Issue by CamaroKing59** [CoFH/Feedback#230] opened 2017-06-12 13:40 UTC
https://pastebin.com/GvPAajB6

Minecraft Version:1.10.2
Thermal Dynamics Version: 1.10.2 - 2.0.1.33- universal
Forge Verison: 12.18.3.2316

**Comment by KingLemming** [comment] 2017-06-12 13:45
Duplicate of #223.

**Closed by KingLemming** 2017-06-12 13:45 UTC
Labels: duplicate
