### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by sanyashvets** [CoFH/Feedback#739] opened 2015-07-27 21:32 UTC
BC version: 7.0.17
MFR version: latest
Pastebin: http://pastebin.com/rWuF4wkH
My report to BC`s developers: https://github.com/BuildCraft/BuildCraft/issues/2918#issuecomment-125317808

**Comment by skyboy** [comment] 2015-07-28 15:26
Duplicate of https://github.com/CoFH/Feedback/issues/716

**Closed by skyboy** 2015-07-28 15:26 UTC
