### ISSUE TITLE
JEI recipes not shown for pulverizer, when basepower gets changed

### ISSUE THREAD

**Issue by Shandoo94** [CoFH/Feedback#1470] opened 2019-03-21 13:11 UTC
**Version**
Thermal Expansion 5.5.3.41
Forge 14.23.5.2815
JEI 4.15.0.269

**What happens**
The recipes for the pulverizer and its petrotheum specialisation aren't displayed in JEI. The recipes still work however.

**What should happen**
The recipes for the pulverizer and its petrotheum specialisation should be displayed in JEI.

**To reproduce the error**
1. Have the default vale for BasePower for the pulverizer in \config\cofh\thermalexpansin\common.cfg
2. Start Minecraft and see that the recipes are correctly displayed
3. Change BasePower (for me it is 125)
4. Start Minecraft and see that the recipes now don't get displayed anymore

**Images**
Screenshots of the pulverizer+augment gui. The curser can't be seen, however in both images the curser is above the processbar-arrow.
First is with default BasePower, second with BasePower=125

![2019-03-21_13 05 29](https://user-images.githubusercontent.com/21018028/54754083-f5cc2680-4be2-11e9-8c31-5fb3b2adc750.png)
default BasePower

![2019-03-21_13 51 55](https://user-images.githubusercontent.com/21018028/54754103-04b2d900-4be3-11e9-8dd0-85f3fa0c54e4.png)
BasePower=125

**Comment by Shandoo94** [comment] 2019-03-21 13:36
It seems the above mentioned Problem affects all machines. But only if the BasePower value of the pulverizer is changed.
Meaning, that changing BasePower for the pulverizer prevents the processingrecipes of all machines exept  the redstonefurnace to be dilsplayed.

**Comment by KingLemming** [comment] 2019-03-21 18:05
Pretty sure this is actually a duplicate of #1469.

**Closed by KingLemming** 2019-03-21 18:05 UTC

**Comment by Shandoo94** [comment] 2019-03-21 19:10
I can't find the error mentioned in #1469 anywhere in my logs. In a testmodpack I created the recipes  were displayed just fine, even with the edits to BasePower. The error did also occur with nearly every other mod diabled.
I now started to recreate my entire modpack from scratch. Even though most of the mods are added and the cofh configs were adjusted, the error did not jet occur.

**Comment by Shandoo94** [comment] 2019-03-21 20:05
I have found the culprit. It is Building Gadgets by Direwolf20. If I deactivate Building Gadgets the recipes are displayed normaly. If I activate Building Gadgets the recipes don't get displayed.
