### ISSUE TITLE
Blitz's fireball left floating in the sky

### ISSUE THREAD

**Issue by RyanP1991** [CoFH/Feedback#657] opened 2015-07-07 21:16 UTC
Hello, first time here submitting an issue so sorry if anything is out of place or missing.

I have just updated all the cofh mods to their latest versions:

CoFH Core - 3.0.3B2-294
CoFH Lib - 1.0.3B2-169
Thermal Dynamics - 1.1.0B2-149
Thermal Expansion - 4.0.2B2-210
Thermal Foundation - 1.2.0B1-96

Rest of the mods can be found here - http://minecraft.curseforge.com/modpacks/232056-the-ryrypatpatpackpack

Since you guys added the blitz I have been noticing its weird fireballs being left around when chunks unload. Below is a few selected screenshots of this happening. 

http://imgur.com/a/yANpy

**Comment by KingLemming** [comment] 2015-07-08 03:14
Can't seem to reproduce this at all. Everything despawns properly. :/

**Comment by KingLemming** [comment] 2015-07-08 03:28
I'm going to call this fixed in dev if only because I've added some code which will 100% take care of whatever is apparently happening. I really can't make it happen myself. :(

**Comment by wasweb** [comment] 2015-07-09 15:53
Not really. It's random, just noticed while flying around my base (magnum torch range!).
![Uploading 2015-07-09_17.46.32.png…]()
CoFHCore-[1.7.10]3.0.3B2-297
ThermalFoundation-[1.7.10]1.2.0B1-97
ThermalDynamics-[1.7.10]1.1.0B2-153
ThermalExpansion-[1.7.10]4.0.2B2-210

**Closed** 2015-07-12 00:39 UTC
Labels: fixed
