### ISSUE TITLE
Duplicate Dest. Redstone/ Ener. Glowstone w/ Missing textures

### ISSUE THREAD

**Issue by Voxel-Friend** [CoFH/Feedback#15] opened 2017-03-05 07:16 UTC
Destabilized Redstone and Energized Glowstone both have two entries in JEI. The ones with textures are not used in recipes and have not recipes themselves. The duplicates are used instead, but with no texture.

As a picture is worth a thousand words, here is my 2,000 word essay.

![2017-03-05_01 12 58](https://cloud.githubusercontent.com/assets/12395262/23585325/54c6876e-0141-11e7-819e-2c9e4c83e94d.png)
![2017-03-05_01 13 14](https://cloud.githubusercontent.com/assets/12395262/23585326/54c8035a-0141-11e7-88d3-16b011e44ec3.png)

**Comment by KingLemming** [comment] 2017-03-05 12:23
Need a modlist for this, because...this doesn't actually happen. At least, we don't seem to be the cause, but I'd like to know what is.

**Comment by HenryLoenwind** [comment] 2017-03-05 14:26
The extra fluids are Ender IO's. I had a look at this: While creating our variants should be skipped, this still happens because of the changed TF mod id. However, we still check if our fluid is the primary before going on and adding the normal recipes (e.g. the glowstone block casting). Which from the picture, I'd say is not happening (the bucket show the TF fluid, so it should be the primary). In any case, this should not influence the texture.

**Comment by KingLemming** [comment] 2017-03-05 16:16
Okay, so honest question - why does EnderIO specifically add its own version of TF Fluids when Tinker's is present, but apparently not otherwise?

**Comment by HenryLoenwind** [comment] 2017-03-05 16:23
They are only added when TiC is there because we have no machine to produce them. So without TiC they are useless and impossible to get. I added them only to support our alloying recipes with the TiC smeltery.

And while our fluids maybe have the better rendering (fog color, screen overlay), I think of yours as the "real" ones. So I `!Loader.isModLoaded("thermalfoundation")` them, too.

**Comment by KingLemming** [comment] 2017-03-05 16:26
You're more than welcome to PR render updates. Bear in mind that when I created those fluids, it was a miracle just to have them rendering at all.

**Comment by KingLemming** [comment] 2017-03-05 16:43
Closing this as it's not really on us.

**Closed by KingLemming** 2017-03-05 16:43 UTC
Labels: invalid
