### ISSUE TITLE
Translocation Plane

### ISSUE THREAD

**Issue by krakel** [CoFH/Feedback#5] opened 2015-01-08 20:30 UTC
I got the following error at placing the plane.
CoFHCore-[1.7.10]3.0.0B9-56.jar
CoFHLib-[1.7.10]1.0.0B8-40.jar
ThermalExpansion-[1.7.10]4.0.0B8-23.jar

java.lang.ClassCastException: mods.railcraft.common.blocks.hidden.TileHidden cannot be cast to thermalexpansion.block.plate.TilePlateBase
	at thermalexpansion.block.plate.BlockPlate.func_149719_a(BlockPlate.java:172)
	at cofh.core.block.BlockCoFHBase.func_149668_a(BlockCoFHBase.java:90)
	at net.minecraft.world.World.func_147472_a(World.java:3317)
	at net.minecraft.item.ItemBlock.func_150936_a(ItemBlock.java:159)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:333)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1436)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1942)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by KingLemming** [comment] 2015-01-08 23:19
Duplicate of #1 

Yay Railcraft's godforsaken hidden block.

**Closed** 2015-01-09 07:57 UTC
Labels: duplicate
