### ISSUE TITLE
Thermal Expansion Crash 5.1.2.3

### ISSUE THREAD

**Issue by ElectricBlue1** [CoFH/Feedback#246] opened 2017-06-15 23:22 UTC
Thermal Expansion crashes when i load up a pack i'm testing for a friend and its using Not Enough ID's so that isn't the issue, no other mods are have an error, checked whats crashing and i cant seem to fix it. Here is the crash log: https://pastebin.com/dAhzF9Re

**Comment by KingLemming** [comment] 2017-06-15 23:33
Duplicate of #240 and still not TE's fault. ;)

You have a mod doing improper oredict.

**Closed by KingLemming** 2017-06-15 23:33 UTC

**Comment by ElectricBlue1** [comment] 2017-06-15 23:44
Which mod is it?

**Comment by KingLemming** [comment] 2017-06-16 00:15
I'm afraid there's no way to know that exactly. The log suggests Extreme reactors, but it may not be directly the fault of that mod. There may be another mod doing cross-oredict in post-init, which is still 100% incorrect.

**Comment by drakray** [comment] 2017-06-16 16:57
My working modList, if it can help you https://pastebin.com/nWK9mjKj
(I'm using Extreme Reactor and it work, so problem is not there)
