### ISSUE TITLE
CohfTweaks Causes Invisible world

### ISSUE THREAD

**Issue by Iareawsome** [CoFH/Feedback#1229] opened 2016-08-04 21:22 UTC
When I removed it, every thing loaded fine. However, with it active, all block textures become invisible. I am still able to see mobs (hostile and neutral), and my hand with whatever it is holding.

**Comment by skyboy** [comment] 2016-08-05 02:24
This is usually caused by other performance-related mods, you must remove them for it to work; and one report of it coming from aether 2

**Comment by Iareawsome** [comment] 2016-08-05 02:32
I ran with only cofhtweaks and fastcraft installed. Will try without fastcraft when I get the chance.

**Comment by skyboy** [comment] 2016-08-05 02:48
Duplicate of https://github.com/CoFH/Feedback/issues/481

**Closed by skyboy** 2016-08-05 02:48 UTC
