### ISSUE TITLE
Lumium/signalum blend doesn't check what fluid is in the bucket for crafting

### ISSUE THREAD

**Issue by superfluke** [CoFH/Feedback#748] opened 2017-12-22 05:27 UTC
ThermalFoundation-1.12.2-2.3.7.18-universal
Forge 14.23.1.2573
![2017-12-22_00 21 15](https://user-images.githubusercontent.com/20022336/34286434-ad8a26c8-e6ae-11e7-9d76-ac89fc2af310.png)

As long as the bucket is full of some liquid, the lumium/signalum crafting recipes don't seem to check what fluid you are using for crafting.

**Comment by KingLemming** [comment] 2017-12-22 12:32
Duplicate of #743. This is on Forge.

**Closed by KingLemming** 2017-12-22 12:32 UTC
