### ISSUE TITLE
Thermal Dynamics FluidDuct npe

### ISSUE THREAD

**Issue by Terpo** [CoFH/Feedback#836] opened 2015-09-12 11:05 UTC
This crash happend the first time this night. There seem to be no other issue that has the same NPE.
I could not reproduce it because it happend 4am in the night. (nobody was only, maybe some kind of chunk loading / chunk border issue?)

Crashlog: http://pastebin.com/vcCfKF43

Forge: 1448
CofH Mods:
CoFHCore-[1.7.10]3.0.3-303.jar
CoFHLib-[1.7.10]1.0.3-175.jar
ThermalDynamics-[1.7.10]1.1.0-161.jar
ThermalExpansion-[1.7.10]4.0.3B1-218.jar
ThermalFoundation-[1.7.10]1.2.0-102.jar

Full modlist: http://blog.terpo.org/upload/mc/modlist.txt

**Comment by KingLemming** [comment] 2015-09-14 03:18
We've never seen it and can't reproduce. If you can recreate it, then alright, but as is, no clue I'm afraid. Could even be hardware corruption on the server.

**Comment by XFactHD** [comment] 2015-09-14 04:57
@Terpo what fluid did you try to transport.

**Comment by Terpo** [comment] 2015-09-14 07:22
Maybe steam or water, but I can't tell it exactly. We have a large map and without coordinates I can't even tell which base created the crash. In the same night, a boiler from railcraft did explode. 

@KingLemming I just wanted you to know that we had a crash. If I can reproduce it (what I don't think), I will post it ;).

**Comment by XFactHD** [comment] 2015-09-14 07:45
I heard that the explosion of railcraft boilers sometimes creates problems with special tile entitys.

**Comment by DPxKnightxZero** [comment] 2015-09-22 16:05
Okay so let me get the straight CoFH team; all posts I have seen relating to crashing you claim you have no idea why it is happening? Well that sounds like maybe your core mod plays with things it shouldn't for example forcing people to use an updated version of bspkrs core. it forces users to install 1.5 when the latest version is 1.6 Just making you think please don't take offense. Anyways thermal dynamics seems to be out of the loop in terms of updates maybe divert some attention to fixing it? Building it against the latest forge gradle etc. Anyways the mods you guys have created are unique and inventive please again I am not attempting to insult you guys just pushing you to think out of the box.

**Comment by KingLemming** [comment] 2015-10-05 22:01
@DpxKnightxZero - we have literally no idea what you're talking about. We don't have ANY dependency on bsprkrs core AT ALL. We don't force it on anybody.

**Comment by KingLemming** [comment] 2015-10-22 05:54
After doing a code review on this, and then determining that it's changed in dev as to be nearly unrecognizable, I've gotta close this down. No other reports thus far, so I'm almost positive this was an x-mod corner case.

To avoid any sort of FUD spreading, I'll shut this down until we get something a bit more concrete.

@Terpo - Thanks for the report. If you can reproduce again, please let us know.

**Closed by KingLemming** 2015-10-22 05:54 UTC
