### ISSUE TITLE
Pulverizer ticking crash

### ISSUE THREAD

**Issue by Serifina** [CoFH/Feedback#641] opened 2015-07-06 04:48 UTC
Since the latest updates, I've had a problem with a Pulverizer crashing the world while ticking. The crash log is here: http://pastebin.com/ND8w0L23 (I've had this happen 4 times now, with no apparent reliable trigger - I have only 4 pulverizers in the world, one sometimes processing sandstone, one processing cobble constantly, and one processing coal constantly, with the last currently just waiting as it's my ore processor). Full log located here: https://drive.google.com/file/d/0B57Rjw7BNxWdSUtvZ1RLWkU5aTA/view?usp=sharing

**Comment by KingLemming** [comment] 2015-07-06 04:55
Duplicate of #639. Basically caused by FML remapping IDs when it shouldn't.

**Closed by KingLemming** 2015-07-06 04:55 UTC
