### ISSUE TITLE
Tesseracts misbehaving on relog

### ISSUE THREAD

**Issue by artubi** [CoFH/Feedback#923] opened 2015-11-09 15:00 UTC
Hi,
Under certain circumstances or setups, relogging cause Tesseracts to behave oddly. I've reported this issue to SleepyTrousers/EnderIO/issues/2979 because I didn't properly test it.
However, link above is still relevant because the issue happens even with TE only setup.

Tested with:
CoFHCore-[1.7.10]3.0.3-303
ThermalExpansion-[1.7.10]4.0.3B1-218
ThermalFoundation-[1.7.10]1.2.0-102

Setup:
http://imgur.com/xSujChq
From left to right:
- Creative Energy Cell , set to max output 2000 RF/t
- "input" Tesseracts, set to same frequency 1, left one set to send, right one receive energy
- "battery" Resonant Energy Cell, left side set to input, right one to output
- "output" Tesseracts, set to same frequency 2, left one set to send, right one receive energy
- Resonant Energy Cell, set to max input 1000 RF/t

I will differ the Energy Cells as "battery" (middle) and "Cell" (right).
Normally, both battery and Cell should be charging at 1000 RF/t. However, after exiting the world and going back to it (relogging) the battery is discharging. Set the Cell max input to 0 RF/t and battery power lever should be "frozen" (it's charging and discharging at 2000 RF/t). Disable Tesseract on the right side of the battery (remove / provide redstone signal...) and the battery should be charging. Again, relog. Now, regardless of Cell input setting, battery is discharging at ~4000 RF/t (?). Disabling the Tesseract will stop the power drainage.

The issue is, that with this kind of setup, each relog cause the Tesseract to double (or add another 1000 RF/t) the amount of power that is supposed to send.

Notes:
- this happens even if Tesseracts are connected via energy pipes / conduits
- if we use EnderIO Capacitor Bank (or conduits with Power Monitors between the battery and Tesseracts) in this kind of setup, with each relog will show that battery input has decreased to 50% and output increased by 2X (or add another 1000 RF/t)
- this issue is only between Tesseract > battery > Tesseract
- there is no issue between last Tesseract and Cell, it will keep charging at 1000 RF/t
- this doesn't happen if we simplify the setup to Creative Energy Cell > Tesseract > Tesseract > Resonant Energy Cell
- this happen only with Tesseracts, EnderIO Trandimensional Receiver works fine
- can be fixed by simply restarting the game

**Comment by KingLemming** [comment] 2015-11-09 19:18
Duplicate of #729. Only happens in single player worlds when you do not fully exit Minecraft.

**Closed by KingLemming** 2015-11-09 19:18 UTC
