### ISSUE TITLE
Crash with the new update

### ISSUE THREAD

**Issue by NanayaQ** [CoFH/Feedback#1007] opened 2018-04-07 05:53 UTC
Just updated the whole thermal expansion suite:

https://pastebin.com/NguVsf71

So far I disable it and game runs fine atm...

**Comment by KingLemming** [comment] 2018-04-07 05:55
Duplicate of #1006. Please look before you post.

**Closed by KingLemming** 2018-04-07 05:55 UTC

**Comment by NanayaQ** [comment] 2018-04-07 05:59
Sorry about that when I was writing up the post I didnt see another one 10 minutes ago since i was double checking with the update.

**Comment by KingLemming** [comment] 2018-04-07 06:04
No worries.
