### ISSUE TITLE
[Cofh Tweaks] + Aether 2 = Transparent Blocks

### ISSUE THREAD

**Issue by Razorskills** [CoFH/Feedback#975] opened 2015-12-17 05:18 UTC
Hello! I am reporting an issue when using Aether 2 and Cofh Tweaks.

Basically, it causes the blocks around the player to be completely transparent, in the Recommended version of CoFHTweaks-[1.7.10]1.0.1-37 the player can see all blocks and entities inside the chunk they are standing in. All blocks and entities outside the chunk they are in are transparent/invisible. moving into the next chunk will allow the player to see that chunk, but also making the previous chunk transparent.

In the latest version of CoFHTweaks-[1.7.10]1.1.0B1-44 Now, the chunk the player is in, is also transparent.

I am not sure which mod is the root cause, but I do know cofh tweaks doesn't have an issue with my other 120 mods, I originally thought it might be Aether 2's issue. But after updating to the latest build of cofh tweaks, and having additional problems, it seems more likely to be cofh tweaks. So, I will post the issue to both parties and link them together. Hopefully the issue can be resolved between the two mods!

The versions I used for The Aether 2 and Gilded Games Util are:

- aether-1.7.10-1.5.2
- gilded-games-util-1.7.10-1.3.1

Here is a video of me showing exactly how to reproduce the issue, and what happens:
https://www.youtube.com/watch?v=zH0nKZsnThY&feature=youtu.be

In these tests, I was using Forge-10.13.4.1614

But I also tested it using the recommended forge 1558

Here is the post on the Aether 2 github issues https://github.com/gildedgames/aether-issues/issues/584

**Comment by skyboy** [comment] 2015-12-17 05:55
Duplicate of https://github.com/CoFH/Feedback/issues/491 (which apparently was not solved, people just didn't report back)

And exploring around their repos: https://github.com/gildedgames/threaded-lighting/blob/master/src/main/java/com/gildedgames/threadedlighting/asm/TLTransformer.java

CoFHTweaks is unable to access or generate its data to trace through what chunks are visible as a result of this mod. They should be able to be compatible with Tweaks, but I'm unable to put my code in over top of theirs and have it work.
If there's any constructors or methods I need to add to make compatibility easier, I can also do that.

**Closed by skyboy** 2015-12-17 05:55 UTC

**Comment by Razorskills** [comment] 2015-12-17 06:02
I think the repo your are looking at is not the correct one?
https://github.com/gildedgames/gilded-games-util/blob/master/src/main/java/com/gildedgames/util/threadedlighting/asm/TLTransformer.java

**Comment by skyboy** [comment] 2015-12-17 06:07
Same code, different repo. It's the source of the issue, however.

**Comment by Razorskills** [comment] 2016-01-09 19:25
As of CoFHTweaks-[1.7.10]1.1.0B2-71.jar this doesn't seem to be an issue after the "Deal better with chunk errors" commit

**Comment by skyboy** [comment] 2016-01-10 17:37
As a note, performance gains with tweaks when aether is present will be minimal to non-existent because tweaks is unable to compile the data it needs to give it's largest gains. There are still benefits, such as better render order and fewer to no non-rendered chunks (after it catches up); However, the entire world will render, where tweaks would normally make a good effort to hide things that are behind other things: usually to the effect of a 60-90% reduction in what's rendered.
