### ISSUE TITLE
Server OutOfMemoryError crash due to possible memory leak in ducts

### ISSUE THREAD

**Issue by MigukNamja** [CoFH/Feedback#406] opened 2017-07-21 09:15 UTC
I've gotten a couple of OutOfMemoryError server crashes lately, even after increasing Java's heap space.

Finding memory leaks in a mountain of code is not an easy task. So, I waited until I had at least a few crash logs before seriously digging into it. Of the crash logs with OutOfMemory, most of them have the following stack:

Stacktrace:
	at net.minecraft.world.World.func_180496_d(World.java:524)
	at net.minecraft.world.World.func_175685_c(World.java:466)
	at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:59)
	at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:200)
	at cofh.thermaldynamics.duct.tiles.DuctUnit.onNeighborBlockChange(DuctUnit.java:275)
	at cofh.thermaldynamics.multiblock.MultiBlockFormer.checkMultiBlock(MultiBlockFormer.java:43)
	at cofh.thermaldynamics.multiblock.MultiBlockFormer.formGrid(MultiBlockFormer.java:23)
	at cofh.thermaldynamics.duct.tiles.DuctUnit.formGrid(DuctUnit.java:244)

Here are a couple of crash logs:

[crash-2017-07-20_12.04.10-server.txt](https://pastebin.com/W45fJgcQ)
[crash-2017-07-20_23.19.21-server.txt](https://pastebin.com/KfPysKmS)

**Comment by KingLemming** [comment] 2017-07-21 14:46
Probably not us, to be perfectly honest. We might be the straw breaking the camel's back, but we aren't the ones building the mountain.

In all likelihood you have another mod leaking memory like crazy and then TD happens to be the thing that is pushing it over the edge. I say this because you're literally the only report of this, and we've done stress tests with millions of ducts. There wasn't any leaking.

**Comment by MigukNamja** [comment] 2017-07-21 18:25
I was taking a long shot and hoping you'd say either - "We fixed that bug in X.Y.Z" or "We just found the root cause and will be fixing it".

Alas, I can't disagree with your assessment. The only evidence I have is circumstantial - a handful of OutOfMemoryError crashes where TD just happens to be the last straw laid on the mountain camel before it keels over.

I will research the best I can on how to track down memory leaks in modded MC (if such a thing is even possible).

Closing this issue...

**Comment by KingLemming** [comment] 2017-07-21 18:29
We can leave this open as an investigation if you like, that's fine.

I'm just fairly sure it isn't us. And I do see Mekanism in that log...

Don't get me wrong, it's a good mod, but it really has had some issues. My theory is that its multiblocks do not properly unload and keep increasing their memory footprint.

**Comment by MigukNamja** [comment] 2017-07-21 18:48
Thanks much, KingLemming. I'll leave it open and will spend some time this weekend on this issue.

**Comment by KingLemming** [comment] 2017-08-02 20:46
Ever find anything on this?

**Comment by KingLemming** [comment] 2017-08-23 18:50
I'm going to go ahead and close this down because we just aren't seeing anything that suggests any leaking in our code. There have been other issues presented here where Mekanism has appeared to be the root cause, so that may be it, honestly.

**Closed by KingLemming** 2017-08-23 18:50 UTC
