### ISSUE TITLE
CRASH:  1.10.2 Thermal Expansion 1.10.2-5.1.7.10

### ISSUE THREAD

**Issue by AnthonyKane5528X** [CoFH/Feedback#305] opened 2017-06-27 03:06 UTC
Attempted to launch after updating the following
CoFHcore: 1.10.2-4.1.8.12
Thermal Expansion: 1.10.2-5.1.7.10

Game Crash while trying to load.

-Removed Thermal Expansion update.  Game loaded.
-Reversed CoFHcore update to previous version.  Attempted to load game. Game still loaded.

Pastebin:
https://pastebin.com/7kWzh4a4

Like I said.  I tried updating to the latest CoFHcore and Thermal Expansion versions and it caused my game to crash.  Upon reversing out the latest Thermal Expansion version the game loaded.  I reversed the CoFHcore update after that just to be on the safe side.

Hope this info helps.

**Comment by KingLemming** [comment] 2017-06-27 03:28
We are literally nowhere in that crash log.

Having said that, this seems to be a duplicate of #302.

**Closed by KingLemming** 2017-06-27 03:28 UTC
