### ISSUE TITLE
Error with ThermalDynamics and LogisticsPipes

### ISSUE THREAD

**Issue by dimitriy0810** [CoFH/Feedback#1065] opened 2016-02-13 11:46 UTC
When I install new versions of ThermalDynamics and LogisticsPipes, I get this error: http://paste.ee/p/2qGas. Versions: Forge-1.7.10-10.13.4.1614, Buildcraft-7.1.14, LogisticsPipes-0.9.3.72, CoFHCore-[1.7.10]3.1.1-324, ThermalDynamics-[1.7.10]1.2.0B1-168, ThermalExpansion-[1.7.10]4.1.2B1-239, ThermalFoundation-[1.7.10]1.2.2-111. With version ThermalDynamics-[1.7.10]1.2.0B2-169 there is the same error.

**Comment by skyboy** [comment] 2016-02-13 12:03
Duplicate of https://github.com/CoFH/Feedback/issues/1052

**Closed by skyboy** 2016-02-13 12:03 UTC
Labels: duplicate, TD

**Comment by dimitriy0810** [comment] 2016-02-13 12:08
And what should I do? Wait realese version of ThermalDynamics&

**Comment by skyboy** [comment] 2016-02-13 13:44
There is no problem with ThermalDynamics.

**Comment by dimitriy0810** [comment] 2016-02-13 13:49
https://github.com/RS485/LogisticsPipes/issues/910
