### ISSUE TITLE
[Thermal Expansion] Add configuration for dynamo fuels

### ISSUE THREAD

**Issue by OneEyeMaker** [CoFH/Feedback#717] opened 2017-12-11 10:33 UTC
Hello.
The subject is fairly simple. Many mods allow to modify energy production of its fuels.
For example:
- Config of Actually Additions allows to change energy production of 4 kinds of (Canola) Oil,
- Forestry has config option for biomass/ethanol energy density,
- Energy density of fuels from Immersive Engineering can be adjusted by config of Diesel Generator
and so on.

With all these config options, dynamos from Thermal Expansion can be either overpowered or useless for certain fuels.
So I suggest to add configuration file to allow *edit* energy production of any fuel used by dynamos.

**Comment by KingLemming** [comment] 2017-12-11 13:12
Duplicate of #638.

**Closed by KingLemming** 2017-12-11 13:12 UTC
