### ISSUE TITLE
Thermal Dynamics Crash Pulling Items out of Vanilla Chest.

### ISSUE THREAD

**Issue by enterprise12nx** [CoFH/Feedback#380] opened 2015-03-31 20:24 UTC
I have seen many reports of this error, and i havent seen any indication of it being worked on, but here is the crash report.

Crash: http://pastebin.com/zEV7xS2n

I had a vanilla chest connected to a harvester from MFR and then underneath, a pipe(carries items and energy, i forget the name) which had one of the very low tier item filter things(whatever the item is that you connect to a conduit to pull items out of an inventory, in this case a chest)

i had it set on redstone signal ignore, and connected to it was a hardened energy conduit that goes underneath the harvester so it receives power.

then it suddenly crashed.

**NOTE**
i am using all the latest versions of CoFH Core, Thermal Expansion, Thermal Foundation, Thermal Dynamics and Redstone Arsenal and MineFactory Reloaded.

**Mod List:**
Forge/FML by LexManos, cpw
Advanced Machines Immibis by Immibis
Advanced Repulsion Systems by immibis
Advanced Solar Panels by SeNtiMeL
Applied Energistics by AlgorithX2
Baubles by Azanor
Bdlib by bdew
BiblioCraft by Nuchaz
Big Reactors by Erogenous Beef
Binnie's Mods by Binnie
Biomes O' Plenty by TDWP_FTW, Adubbz
bspkrsCore by bspkrs
Buildcraft by CovertJaguar, SirSengir, Krapht, cpw, spacetoad
Carpenter's Blocks by Mineshopper
ChickenChunks by Chickenbones
Chisel by AUTOMATIC_MAIDEN
CodeChickenCore by Chickenbones
CodeChickenLib by Chickenbones
CoFH Core by CoFH team
ComputerCraft by dan200
CookieCore by ephys
CoroUtil by Corosauce
Dimensional Anchors by immibis
Doggy Talents by ProPercivalalb
Enchanting Plus by Freyjadono, mssodin23, GnRSlash, Qizzok, xkyouchoux
EnderIO by CrazyPants
EnderStorage by Chickenbones
Extra Cells by Leonelf
ExtraTiC by Glassmaker
Factorization by neptunepink
FastCraft by Player
Flans mod and official content packs by jamioflan
Forbidden Magic by SpitefulFox
Forestry by SirSengir
Forge Multipart by Chickenbones
Galacticraft by Micdoodle8
Gendustry by bdew
Gravitation Suite by SeNtiMeL
Growthcraft by Gwafu
HarvestCraft by MatrexsVigil, Rhodox
Hat Stand by iChun
Hats by iChun
iChunUtil by iChun
Immibis Core by immibis
Immibis's Microblocks by immibis
IndustrialCraft 2 by IC2 Dev Team
Inventory Tweaks by Kobata
IronChests by cpw
JABBA by ProfMobius
Liquid XP by immibis
Localized Weather & Stormfronts by Corosauce
LogisticsPipes by davboecki, AartBluestoke, ArtForz, GUIpsp, theZorro266
Magic Bees by MysteriousAges
Mantle by mDiyo, progwml6
Matmos by Hurricaaane
Mekanism by aidancbrady
MicdoodleCore by Micdoodle8
Minechem by ljdp
MineFactory Reloaded by skyboy026, powercrystals
Modular Powersuits by MachineMuse
Modular Powersuits Addons by eximius88, Andrew2448
MrCrayfish's Furniture Mod by Mr_Crayfish
Natura by mDiyo
NEI Addons by bdew
NEI Integration by Tonius
NetherOres by skyboy026, powercrystals
Not Enough Items by Chickenbones
NotEnoughCodecs by Mikeemoo
Nuclear Control by shedar
Numina by MachineMuse
OpenBlocks by Mikeemoo
OpenModsLib by Mikeemoo
OpenPeripheral Core by Mikeemoo
PneumaticCraft by MineMaarten
Power Converters by samrg472, powercrystals
Project Red by MrTJP, Chickenbones
QuarryPlus by yogpstop
Railcraft by CovertJaguar
Redstone Arsenal by TeamCoFH
Roguelike Dungeons by Greymerk
Simply Jetpacks by Tonius
Soul Shards Reborn by Moze_Intel
Steve's Carts 2 by Vswe
Thaumcarpentry by zot201
Thaumcraft by Azanor
Thaumic Tinkerer by pixlepix, nekosune, vazkii
ThaumicRevelations by Mortvana, MasterAbdoTGM50
The Mithril Mod by Dawars
Thermal Dynamics by TeamCoFH
Thermal Expansion by CoFH team
Thermal Foundation by TeamCoFH
TiC Tooltips by squeek502
Tinker's Construct by boni, mDiyo
Tinkers Steelworks by Toops, Ephys
TreeCapitator by bspkrs, DaftPVF
ttCore by tterrag
TubeStuff by immibis
Twilight Forest by Benimatic
Voxel Menu Music by The Voxel Box
VoxelLib by The Voxel Box
VoxelMap by The Voxel Box
VoxelMenu by The Voxel Box
Waila by ProfMobius
Waila Harvestability by squeek502
WAILAPlugins by tterrag
Wireless Redstone CBE by Chickenbones

**Comment by KingLemming** [comment] 2015-03-31 21:32
Duplicate of #291 which still has the wtf label because we can't reproduce this at all, sorry.

**Closed by KingLemming** 2015-03-31 21:32 UTC
Labels: duplicate

**Comment by enterprise12nx** [comment] 2015-03-31 21:35
odd, we have had it happen multiple times, have you tried doing it on cauldron?

**Comment by KingLemming** [comment] 2015-03-31 22:12
Nope. Have not. But frankly if it's a Cauldron-specific issue, it'll be unfixable. We aren't going to start special-casing code for a server which is in a legal grey area.

**Comment by enterprise12nx** [comment] 2015-03-31 22:44
ya i understand, i guess i will mcedit the block out

**Comment by KingLemming** [comment] 2015-03-31 23:04
I'm not positive that it's Cauldron, just that we haven't been able to repro it yet. I can maybe put a sanity check in there but shouldn't really have to; it sort of means something else has gone wrong and I'd just be hiding it.

**Comment by enterprise12nx** [comment] 2015-03-31 23:08
idk what a sanity check is, but ive been reporting bugs to authors left and right lol, hoping to get my server very stable, it is for the most part, my players seem to find the rarest of bugs lol.

so we keep getting game breaking bugs >.>
